### ISSUE TITLE
possibly wrong window type prevents grabbing focus in kwin

### ISSUE THREAD

**Issue by avxmw** [espanso/espanso#1005]
**Describe the bug**
On my openSUSE system I run the plasma desktop and kwin does not give focus to espanso search window when it spawns when the focus policy is 'focus follows mouse'.

**To Reproduce**
1. set focus policy in kwin to 'focus follows mouse'
2. spawn espanso search window
3. wonder why you can't type in it

**Expected behavior**
search window should get focus and accept input

**Setup information**
- OS: openSUSE Tumbleweed, updated to latest versions
- Version: espanso 2.1.3-alpha (installed via snap)

The problem seems to be that espanso sets a window type which kwin does not want to give focus to automatically. Using kwin's window rules to enforce the window as being seen as "normal window" or "dialog window" makes it work as expected.

Some more info including screenshots in this reddit post: https://www.reddit.com/r/kde/comments/t16r0n/how_to_automatically_focus_a_window_when_it_spawns/

I am not sure who is at fault here, kwin or espanso.

**Comment by federico-terzi** [comment]
Hey @avxmw,

I'm sorry you experienced this problem! It sounds like you found a working workaround, would you mind sharing it here as a form of documentation for others? :)

Cheers :)

**Comment by federico-terzi** [comment]
Also there was a recent update on this topic (see #829), perhaps upgrading to the new v2.1.4-beta would solve this problem (but it has not been released yet)

**Comment by federico-terzi** [comment]
@avxmw Thanks!

> I'm not sure why espanso sets _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY while krunner sets _NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL.

That's probably been solved by in #829, see: https://github.com/federico-terzi/espanso/commit/4e9b49c3ad03d4b124a232040093fe282e6db616

Thanks for sharing your workaround in the meantime, I'll be curious to see if the new version solves the problem for you

Cheers :)

**Comment by smeech** [comment]
Is this resolved by the current release?

**Comment by avxmw** [comment]
> Is this resolved by the current release?

Thanks for pinging me.

Indeed, updating to 2.2.1 (X11, AppImage) now works for me without special window rules on Tumbleweed 20240211 (plasma 5.27.10, frameworks 5.114.0, qt 5.15.12).

Guessing this also works on wayland? If so, I'd consider this resolved, yes.

**Comment by smeech** [comment]
I've done a little experimentation in a Fedora Wayland VM and everything worked fine except for the Wayland issues mentioned in the documentation (no app-specific configs etc.).
Thank you for closing the issue - we're trying to mop up the old ones to see what is still relevant, now we have a number of people working on the project .
