### ISSUE TITLE
failed to initialize injector module: could not open input method

### ISSUE THREAD

**Issue by parasbhanot** [espanso/espanso#1039]
Espanso no longer works after latest update . i have tried espanso-bin , espanso-git and plain espanso from Aur but none of them are working in Linux anymore.

os - Arch linux , 

i am getting the following when i give sudo espanso start 

```bash

✖  sudo espanso start

Unable to start espanso as a service as it's not been registered.
You can either register it first with `espanso service register` or
you can run it in unmanaged mode with `espanso service start --unmanaged`

NOTE: unmanaged mode means espanso does not rely on the system service manager
      to run, but as a result, you are in charge of starting/stopping espanso
      when needed.
unable to start service: not registered as a service
```

After giving sudo espanso service register i am getting the following 

```
~ ✖  sudo espanso service register

creating service file in "/root/.config/systemd/user/espanso.service"
enabling systemd service
Failed to connect to bus: No medium found
unable to register service: systemctl enable failed
```

And after giving the  sudo espanso service start --unmanaged command i get the following 
```

~ ✖  sudo espanso service start --unmanaged
unable to start service: timed out
```

Am i doing something wrong ?

**Comment by federico-terzi** [comment]
Hey @parasbhanot,

I'm sorry you experienced this problem! Please try the following:

* Install espanso from `espanso-git` AUR
* Run `espanso service unregister && espanso service register`
* Reboot your PC

Cheers :)

**Comment by parasbhanot** [comment]
Hi, i am not able to start the service even if registration is successful. 

```bash
  ✖  espanso service unregister && espanso service register
disabling espanso systemd service
Removed /home/parasbhanot/.config/systemd/user/default.target.wants/espanso.service.
deleting espanso systemd entry
service unregistered correctly!
creating service file in "/home/parasbhanot/.config/systemd/user/espanso.service"
enabling systemd service
Created symlink /home/parasbhanot/.config/systemd/user/default.target.wants/espanso.service → /home/parasbhanot/.config/systemd/user/espanso.service.
service registered correctly!
```
```
~ ✖  espanso start
unable to start service: timed out

~ took 5s ✖  espanso status
espanso is not running
```

The previous version of espanso is working fine .

**Comment by parasbhanot** [comment]
i have also noticed there is some bug in thread when i try to launch directly 

```bash
~ ✖  /usr/bin/espanso  launcher
12:58:43 [daemon(16059)] [INFO] reading configs from: "/home/parasbhanot/.config/espanso"
12:58:43 [daemon(16059)] [INFO] reading packages from: "/home/parasbhanot/.local/share/espanso/packages"
12:58:43 [daemon(16059)] [INFO] using runtime dir: "/home/parasbhanot/.local/share/espanso"
12:58:43 [daemon(16059)] [INFO] watching for changes in path: "/home/parasbhanot/.config/espanso"
12:58:43 [daemon(16059)] [INFO] espanso version: 2.1.5-beta
12:58:43 [daemon(16059)] [INFO] spawning the worker process...
12:58:43 [daemon(16059)] [INFO] binded to IPC unix socket: /home/parasbhanot/.local/share/espanso/espansodaemonv2.sock
12:58:43 [worker(16067)] [INFO] reading configs from: "/home/parasbhanot/.config/espanso"
12:58:43 [worker(16067)] [INFO] reading packages from: "/home/parasbhanot/.local/share/espanso/packages"
12:58:43 [worker(16067)] [INFO] using runtime dir: "/home/parasbhanot/.local/share/espanso"
12:58:43 [worker(16067)] [INFO] using X11AppInfoProvider
12:58:43 [worker(16067)] [INFO] binded to IPC unix socket: /home/parasbhanot/.local/share/espanso/espansoworkerv2.sock
12:58:43 [worker(16067)] [INFO] using X11Source
12:58:43 [worker(16067)] [INFO] monitoring the status of the daemon process
12:58:43 [worker(16067)] [INFO] using X11Injector
12:58:43 [worker(16067)] [ERROR] thread 'engine thread' panicked at 'failed to initialize injector module: could not open input method': espanso/src/cli/worker/engine/mod.rs:184
12:58:43 [worker(16067)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
12:58:43 [worker(16067)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
12:58:43 [worker(16067)] [ERROR] thread 'detect thread' panicked at 'unable to send to the source channel: "SendError(..)"': espanso/src/cli/worker/engine/funnel/mod.rs:104
12:58:43 [daemon(16059)] [ERROR] received unexpected exit code from worker 101, exiting
thread 'main' panicked at 'failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.', espanso/src/cli/launcher/mod.rs:213:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by federico-terzi** [comment]
@parasbhanot That's very interesting, thank you for sharing. It seems that Espanso can't open the input method on your environment. Looking at [this issue](https://github.com/alacritty/alacritty/issues/732#issuecomment-326708961), you might be able to start espanso by starting the IBus daemon manually with:

```
ibus-daemon
```

Does that help?

**Comment by parasbhanot** [comment]
i did not have ibus-daemon installed on my machine but even after installing and stating the ibus i am getting the same error . 

The previous version espanso is working fine without ibus .

**Comment by federico-terzi** [comment]
@parasbhanot I see, thanks! We'll investigate

**Comment by pacossac** [comment]
Hello,

I'm on Debian Bookworm/testing. 
After trying to install the .deb package which doesnt'work (as mentionned in Issue #1793) and flathub, which doesn't work neither, I tried from the source, like this method https://edafe.de/2023/09/how-to-install-espanso-from-source-on-debian-12-bookworm/

This time installation seems Ok and `espanso --version` respond espanso 2.2.1

But it was impossible to register. Seems to be the same problem : 
`Failed to connect to bus: Permission non accordée
unable to register service: systemctl enable failed
`

**Comment by AucaCoyan** [comment]
One thing that has changed since 2022 is that espanso doesn't need the root permissions to register the service (because it runs as a user with capabilities).
Try just `espanso service register` please!

Documentation here, at the last part of this title
https://espanso.org/docs/install/linux/#deb-x11

**Comment by guidovw** [comment]
I had the same issue as **@parasbhanot** (on Debian12). I solved it by `exit`, so that I was no longer a root user. Then `espanso service register` did work.
