### ISSUE TITLE
Espanso won't start: libgobject-2.0 undefined symbol

### ISSUE THREAD

**Issue by AlbeyAmakiir** [espanso/espanso#1047]
**Describe the bug**
Espanso fails to start. When I run from a terminal, I get only: `espanso: symbol lookup error: /usr/lib/libgobject-2.0.so.0: undefined symbol: g_atomic_rc_box_release_full` and it terminates. No other logs.

**Setup information**
- OS: ArcoLinux (Arch Linux)
- Espanso version: 2.1.4-1 from the package manager.

While checking previous issues, I've noticed stuff like this has come up a few times. Is there perhaps some process to catch these before they occur? Something with dependency settings on packages? (I don't know how that works.)

**Comment by federico-terzi** [comment]
Hey @AlbeyAmakiir,

Did you use the App image?

If so, please try downloading the nightly release from here: https://github.com/federico-terzi/espanso/actions/runs/2048796020 (under Linux X11 Artifacts), the rest of the installation process is the same :)

Let me know if that helps!

Will release the fix in the upcoming days

**Comment by AlbeyAmakiir** [comment]
I didn't use the AppImage. Got it via the package manager for Arch Linux, since that updates automatically and AppImages don't.

**Comment by jdoss** [comment]
I am seeing this on the latest release with the X11 Appimage with Fedora 36 Beta.

```
$ ./espanso version
./espanso: symbol lookup error: /lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref
```

my older version after the upgrade to Fedora 36 had a different error too:

```
$ espanso
espanso: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by federico-terzi** [comment]
@jdoss I'm sorry you experienced this problem! I'm releasing version 2.1.5-beta with a fix soon, should be available in ~2 hours
