### ISSUE TITLE
using shrug@ shortcut stuck and then types last copied item instead...

### ISSUE THREAD

**Issue by Yolakalemowa** [espanso/espanso#1049]
**Describe the bug**
I have two specific keymaps that are not working on SOME platforms:

![image](https://user-images.githubusercontent.com/41283612/160611008-72e1683e-0118-4210-8ae5-c577a6bc54bd.png)

these two commands, when executed on linux mint text editor or on linux mint notes (and some other platforms not sure where) it doesn't work. It gets stuck for a couple of seconds and then either just stays blank with the cursor disappeared or types the last copied item in the clipboard for some reason. (

**Reproduce**
1. I'm using linux mint. with the above commands (see screenshot). all other commands work fine except these two shruggies.
2. test on default text editor linux mint or the sticky notes app.

**Logs**
the logs do not show any activity about this cause the time when the command is executed and the cllipboard result given isn't even logged

**Setup information**
- OS: Mint
- Version: espanso 2.1.3-alpha

**Comment by ReaderGuy42** [comment]
I'm also on Linux Mint and something very similar happens to me! Though for me it's not the "shruggie", though I think it's when it's supposed to input non-standard symbols, e.g. "ḥ" (with the dot under the letter) or similar.
I'm on espanso 2.1.4-beta

Thanks :)

**Comment by federico-terzi** [comment]
Hey guys,

I'm sorry you experienced this problem! Could you please try installing the `xclip` utility (using your favorite package manager), then try adding this option in your `config/default.yml` file and see if that helps?

```
x11_use_xclip_backend: true
```

There's a known bug we're trying to solve, but we still haven't figured out the cause...
Cheers :)

**Comment by Yolakalemowa** [comment]
> non-standard symbols, e.g. "ḥ" (with the dot under the letter) or similar.

Dude! I've been trying to find a way to input these diactritic letters for ages with Espanso but didn't get any answer yet on reddit. What's the command you're using? I want to use left shift + the letter to input the corresponding diacritic letter. I tried everything but I don't know how Espanso allows you to use a modifier key in addition to a normal key to input. 

Left Shift + h = ḥ

**Comment by Yolakalemowa** [comment]
@federico-terzi 

Hi so I checked and I already had that utility installed so I added the command and it seems to have solved the issue but only for text editor. When tested in notes, problem persists.

btw, noob q: is there a quick way to update espanso to latest Beta? I'm currently on 2.1.3-alpha.

**Comment by ReaderGuy42** [comment]
> > non-standard symbols, e.g. "ḥ" (with the dot under the letter) or similar.
> 
> Dude! I've been trying to find a way to input these diactritic letters for ages with Espanso but didn't get any answer yet on reddit. What's the command you're using? I want to use left shift + the letter to input the corresponding diacritic letter. I tried everything but I don't know how Espanso allows you to use a modifier key in addition to a normal key to input.
> 
> Left Shift + h = ḥ

I'm not actually using Espanso for that part. If you're also on Cinnamon (not sure for the other Mint flavors) you can use the Compose key (see below for infos on that), and then use the key combo "Compose key" then "!" (exclamation) and then "h", which results in "ḥ".

You can find the compose key (or rather how to enable it) via "System Settings", then choose Keyboard Layout, then in the bottom right hit "Options", and then in that new window with many options the fifth from the bottom should be called "Position of Compose key". You then have to choose a key that should act as the Compose key which enables you to use that extra layer of symbols. And then you can just google for symbols you're trying to make with the Compose key. E.g. here's a list https://tstarling.com/stuff/ComposeKeys.html

Hope this helps!

**Comment by ReaderGuy42** [comment]
> Hey guys,
> 
> I'm sorry you experienced this problem! Could you please try installing the `xclip` utility (using your favorite package manager), then try adding this option in your `config/default.yml` file and see if that helps?
> 
> ```
> x11_use_xclip_backend: true
> ```
> 
> There's a known bug we're trying to solve, but we still haven't figured out the cause... Cheers :)

I enabled that option in default.yml (the thing was already installed for me too) but I can't yet tell if that has worked; I'll keep you posted. Thanks!

**Comment by Yolakalemowa** [comment]
@ReaderGuy42 Thanks for the reply. But I'd rather do it with Espanso cause I have my own shortcut system and I use a lot of diacritic letters... used to do it eaasily with auto hot key on windows... Isn't there a way to use a modifier key on espanso? @federico-terzi like I asked?

Left Shift + h = ḥ

**Comment by ReaderGuy42** [comment]
Not sure if I'm misunderstanding, but wouldn't "Left Shift + h" just make a capital H?
Until @federico-terzi answers, I'll give it a shot (but please correct me): I'm not sure but as far as I can tell, Espanso doesn't add an extra layer of keys, which I think is what you're after. 
But what you could do is create an Espanso trigger, such as ":h" (with a colon before hand, since it's unlikely that'll come up in regular words), to be replaced with the diacritic mark you're after. So that would look like this:
```
  - trigger: ":h"
    replace: "ḥ"
```
Then when you're typing you just have to remember to add in the colon (":") and it'll automatically replace it.
Does that help?

**Comment by Yolakalemowa** [comment]
@ReaderGuy42 I think part of the problem here is me not really understanding the Espanso technology. If you're familiar with AHK, when I command it to use the left shift + h it actually overrides the original function of the left shift which capitalizes. That became really useful for me cause I can even keep pressing left shift and all subsequent letters will come out with diacritics. As an academic this is very helpful for writing.

But until I figure out whether that's possible with Espanso, I guess I'll have to go with your solution. 

Thanks a lot again for taking the time!
