### ISSUE TITLE
Error during migration (Espanso v2.1.4-beta running on Ubuntu 20.04)

### ISSUE THREAD

**Issue by mattnolan001** [espanso/espanso#1051]
When I start the new Espanso (v2.1.4-beta running on Ubuntu 20.04) and then choose 'Backup and migrate' I receive an error. The log reads: 'main' panicked at 'unable to generate backup directory': espanso/src/cli/migrate.rs:181'. When I continue running v2.1.4 in compatibiltiy mode it seems to run fine.

**Comment by federico-terzi** [comment]
Hey @mattnolan001,

I'm sorry you experienced this problem! Could you please post the output of `espanso log` here?

Also, it would be super helpful if you could run `espanso migrate` in a terminal and post the output of the process here.

Cheers :)

**Comment by mattnolan001** [comment]
Log:

16:07:21 [service(22084)] [INFO] reading configs from: "/home/matt/.config/espanso"
16:07:21 [service(22084)] [INFO] reading packages from: "/home/matt/.local/share/espanso/packages"
16:07:21 [service(22084)] [INFO] using runtime dir: "/home/matt/.local/share/espanso"
16:07:26 [service(22084)] [ERROR] unable to start service: timed out
16:07:43 [migrate(22153)] [INFO] reading configs from: "/home/matt/.config/espanso"
16:07:43 [migrate(22153)] [INFO] reading packages from: "/home/matt/.local/share/espanso/packages"
16:07:43 [migrate(22153)] [INFO] using runtime dir: "/home/matt/.local/share/espanso"
16:07:43 [migrate(22153)] [WARN] espanso is reading the configuration using compatibility mode, thus some features might not be available
16:07:43 [migrate(22153)] [WARN] you can migrate to the new configuration format by running 'espanso migrate' in a terminal
16:07:43 [migrate(22153)] [INFO] --- MIGRATION STARTED ---
16:07:43 [migrate(22153)] [ERROR] thread 'main' panicked at 'unable to generate backup directory': espanso/src/cli/migrate.rs:181
16:07:43 [migrate(22153)] [ERROR] ERROR: 'main' panicked at 'unable to generate backup directory': espanso/src/cli/migrate.rs:181

I saw the same thing running from the command line. I've since manually recreated the folder structure for v2.1.4beta and everything runs fine.

Fantastic program by the way!

Matt

**Comment by federico-terzi** [comment]
@mattnolan001 Thanks! It seems espanso is unable to find your document directory. Could you please run the following in a terminal and post the output here? :)

```
echo $XDG_CONFIG_HOME
echo $XDG_DOCUMENTS_DIR
```

Related code: https://github.com/federico-terzi/espanso/blob/master/espanso/src/cli/migrate.rs#L181

**Comment by mattnolan001** [comment]
Neither returns anything.

**Comment by federico-terzi** [comment]
@mattnolan001 I see! thanks

Could you please try running the following command (make sure to double-check the Documents directory I've inserted below):

```
XDG_DOCUMENTS_DIR=/home/matt/Documents espanso migrate
```

**Comment by n8henrie** [comment]
After going down a bit of a rabbit hole with the `dirs` and `dirs_sys` crates, I figured out that I needed to `sudo pacman -S xdg-user-dirs` and then `xdg-user-dirs-update`, which creates `~/.config/user-dirs.dirs`. Once that was created, `dirs::document_dir()` stopped returning `None`[^1], and `espanso migrate` was able to succeed.

[^1]: https://github.com/federico-terzi/espanso/blob/5df94b5031d5b2ec0cb13424be600f418cbc0e07/espanso/src/cli/migrate.rs#L180

**Comment by federico-terzi** [comment]
@n8henrie Thank you for the investigation! I'd say we should try falling back to another directory if that one is not available, I'll add it to the roadmap

**Comment by n8henrie** [comment]
To be clear, that directory *was* available the whole time, but the crate you're depending on didn't know how to find it without those additional steps.

**Comment by smeech** [comment]
Given this Issue is now quite old, and I hope most people have migrated to v2, can it be closed as we're unlikely to do further work on it?

**Comment by n8henrie** [comment]
Probably reasonable. Can always point people to this issue for the workaround (at least for arch).
