### ISSUE TITLE
VSCodium on Windows 10

### ISSUE THREAD

**Issue by FranciscoTrigo** [espanso/espanso#1074]
**Describe the bug**
Espanso will replace with incomplete strings when used with VSCodium in Windows 10, similar to https://github.com/federico-terzi/espanso/issues/544
Seems to happen with Markdown files mostly (out of th eones I have tried)

**To Reproduce**
1. Use espanso in VSCodium, seems to happen with Markdown files mostly.

**Expected behavior**
Correct replacement of text.

**Setup information**
- OS: Windows 10
- Version: espanso 2.1.5-beta

I tried the fix proposed in the issue linked earlier with:

```name: vscodium
filter_exec: "VSCodium.exe"
backend: Clipboard
backspace_delay: 12
```

The behavior changed, but problem is still happening. For reference, espanso is working correctly with VSCode, just not with VSCodium.

**Comment by smeech** [comment]
I'll close this is favour of #675, which may have been resolved anyway. Let me know if this needs reopening.
