### ISSUE TITLE
none of packages work on 2.1.5-beta MacOS

### ISSUE THREAD

**Issue by Mattia1010** [espanso/espanso#1082]
**Describe the bug**
Just installed the new version (2.1.5-beta on MacOS, via Home-brew), and none of the packages seem to work. The snippets in the default base.yml configuration file are working as expected (replacements, dates, etc.).

Here's the log_screen:
<img width="1046" alt="log_screen_accents" src="https://user-images.githubusercontent.com/87578145/164965556-61663a95-57ab-4350-a4b5-dbbb54043843.png">

Can you help me?

**Setup information**
- OS: MacOS Monterey 12.3.1
- Version: 2.1.5-beta

**Comment by federico-terzi** [comment]
Hey @Mattia1010,

I'm sorry you experienced this problem! A couple of questions:

* Could you please type `#acfg#` and post the output here?
* What keyboard layout are you using?

Cheers :)

**Comment by Mattia1010** [comment]
Hi @federico-terzi ,
qwerty layout, language set to english (US).

Here's the #afcg# output:

[espanso config: "/Users/mattia/Library/Application Support/espanso/config/default.yml"]

backend: Auto
enable: true
paste_shortcut: None
inject_delay: None
key_delay: None
apply_patch: true
word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\u{16}"]

preserve_clipboard: true
clipboard_threshold: 100
disable_x11_fast_inject: false
pre_paste_delay: 100
paste_shortcut_event_delay: 10
toggle_key: None
auto_restart: true
restore_clipboard_delay: 300 
post_form_delay: 200 
post_search_delay: 200 
backspace_limit: 5
search_trigger: None
search_shortcut: Some("ALT+SPACE")
keyboard_layout: None

show_icon: true
show_notifications: true
secure_input_notification: true

x11_use_xclip_backend: false
win32_exclude_orphan_events: true
win32_keyboard_layout_cache_interval: 2000

match_paths: [
    "/Users/mattia/Library/Application Support/espanso/match/base.yml",
]



Grazie :)

**Comment by federico-terzi** [comment]
@Mattia1010 Interesting, thanks! It seems that Espanso is unable to load the packages

Could you please post the output of `ls -lR "/Users/mattia/Library/Application Support/espanso"` here?

**Comment by smeech** [comment]
Is this still an issue with the current release or can we close it?

**Comment by Mattia1010** [comment]
not an issue anymore, from a long time to be fair :)

**Comment by smeech** [comment]
That's what I thought. Thank you for taking the trouble to reply.
