### ISSUE TITLE
Espanso (MacOS) doesn't recognise accessibility options are checked.

### ISSUE THREAD

**Issue by Auratelience** [espanso/espanso#1089]
**Describe the bug**
I have installed the Espanso app (both from the website and with Homebrew). It opens successfully to the Allow Accessibility page, but does not move past it once the boxes are checked, even after closing and reopening the app.

**To Reproduce**
1. Install Espanso for Mac
2. Launch

**Expected Behaviour**
Updating to configuration page, either immediately or after a restart of the app.

**Environment Info**
MacOS Monterey v12.3.1
Homebrew v3.4.9
Espanso v2.1.5-beta

Thank you in advance, Auratelience

**Comment by federico-terzi** [comment]
Hey @Auratelience,

I'm sorry you experienced this problem! Could you please try unchecking and re-checking the Espanso checkbox in the accessibility page? Sometimes it also help to remove Espanso from the list and re-adding it

Cheers :)

**Comment by Auratelience** [comment]
Hi,
I have tried checking and unchecking the boxes, and have removed it from the list. Espanso still doesn't seem to notice the changes.

Thanks

**Comment by federico-terzi** [comment]
Please also try killing Espanso and then restarting the system, sometimes that help :)

**Comment by carlotrimarchi** [comment]
@Auratelience did you manage to solve this? I've been experiencing the same issue since updating to MacOs Monterey

**Comment by Auratelience** [comment]
No I did not. I gave up and  just used Text Replacement as a workaround currently. Restart didn't work however.

**Comment by revolter** [comment]
I stumbled upon this (or a similar) issue after updating to 2.1.7-beta, and I had to remove espanso from the list (I had 2 entries there), and then run `espanso service register` for it to work.

**Comment by ilyapas** [comment]
I had the same issue with macOs Sonoma 14.1 and Espanso 2.1.8. Solved it following revolter's advice. A hint directly in the app would have been helpful 🙂

**Comment by federico-terzi** [comment]
Unfortunately, macOS it's a bit finicky with the accessibility APIs, not much we can do to solve it except checking/unchecking and restarting :(

**Comment by smeech** [comment]
Is this still a problem with the current release? Can we close the Issue, or does the documentation need amending?

**Comment by Auratelience** [comment]
I've found all things are working well now. I will close the issue.

**Comment by smeech** [comment]
Thank you
