### ISSUE TITLE
quotes as first

### ISSUE THREAD

**Issue by rafaeltgt** [espanso/espanso#1092]
**Describe the bug**
Hello, I'm willing to use this match below and expecting to get as output `'':'',`, but the output I'm getting is `:,`
`    replace: "'':'',"`

If I switch the backend to 'Clipboard' I get the correct output. Is there a way to use this match using default backend ? 

**Logs**
12:07:13 [daemon(18874)] [INFO] spawning the worker process...
12:07:13 [worker(22202)] [INFO] reading configs from: "/home/rafael/.config/espanso"
12:07:13 [worker(22202)] [INFO] reading packages from: "/home/rafael/.config/espanso/match/packages"
12:07:13 [worker(22202)] [INFO] using runtime dir: "/home/rafael/.cache/espanso"
12:07:13 [worker(22202)] [INFO] using X11AppInfoProvider
12:07:13 [worker(22202)] [INFO] binded to IPC unix socket: /home/rafael/.cache/espanso/espansoworkerv2.sock
12:07:13 [worker(22202)] [INFO] using X11Source
12:07:13 [worker(22202)] [INFO] monitoring the status of the daemon process
12:07:13 [worker(22202)] [INFO] using X11Injector
12:07:14 [worker(22202)] [INFO] using X11Clipboard

**Setup information**
- OS: Linux, X11, Gnome 42.0
- Version: espanso 2.1.5-beta

**Comment by smeech** [comment]
If the clipboard backend works for this trigger, then add the recently documented property:
```
    force_mode: clipboard
```
to your trigger code. This won't affect your global settings.
