### ISSUE TITLE
Import External Configs similar to External Matches

### ISSUE THREAD

**Issue by ibehnam** [espanso/espanso#1098]
Basically the title. I think it should be straightforward to make Espanso load external configs the same way that it imports external match files.

I have created an external config YAML with the following:
```
toggle_key: OFF
undo_backspace: false
backend: Inject
auto_restart: true
```
But when I add it to `~/Library/Application Support/espanso/config/default.yml`, those configs are not loaded.

**Comment by smeech** [comment]
Is this still an issue with the current release or can we close it?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
