### ISSUE TITLE
unable to start service: launchctl exited with non-zero code `exit status: 3`

### ISSUE THREAD

**Issue by Gattomarino** [espanso/espanso#1099]
Espanso will not start after my very first install on Catalina 10.15.7, this is the error message:
unable to start service: launchctl exited with non-zero code `exit status: 3`

Any suggetions? thx!

**Comment by ismailfateen** [comment]
Same thing here, used to work on Monterey, not working on macos ventura beta

**Comment by KKKo1877** [comment]
I have to register twice, but it worked! Thx!!

**Comment by grigoryosifov** [comment]
If you reinstalled/updated Espanso (as I did after upgrading to macOS Tahoe), macOS can keep a stale Accessibility permission.

In addition to running `espanso service register`, go to System Settings → Privacy & Security → Accessibility, remove Espanso, then add it back with the “+” and enable it. This refreshes the permission and fixes the silent failure.

<img width="521" height="545" alt="Image" src="https://github.com/user-attachments/assets/44b0c12c-cd05-4214-9904-19fb4cb2530d" />

**Comment by laricoDGT** [comment]
> espanso service register

solved
