### ISSUE TITLE
Espanso `unable to start service: timed out` on macOS, perhaps related to custom $PATH issues.

### ISSUE THREAD

**Issue by SamuelSwartzberg** [espanso/espanso#1100]
**Describe the bug**
When running `espanso start` or `espanso restart`, it fails with `unable to start service: timed out`. Stopping works normally.

**To Reproduce**
run `espanso start` or `espanso restart` while espanso is not running.

**Expected behavior**
Espanso should start :P

**Logs**

```
12:24:01 [service(74003)] [INFO] reading configs from: "/Users/sam/.config/espanso"
12:24:01 [service(74003)] [INFO] reading packages from: "/Users/sam/.config/espanso/match/packages"
12:24:01 [service(74003)] [INFO] using runtime dir: "/Users/sam/Library/Application Support/espanso"
12:24:06 [service(74003)] [ERROR] unable to start service: timed out
```

**Setup information**
- OS: macOS Monterey 12.0.1
- Version: espanso 2.1.4-beta

**Triage**
During setup, I chose the don't add to path option, as I have a fairly complex .profile setup and was scared of what it might do with that. Instead, I manually added `/Applications/Espanso.app/Contents/MacOS` to my path. Interfacing with espanso works, however starting doesn't, as described above. It is possible to start espanso by running `open /Applications/Espanso.app` or opening Espanso.app in the GUI.  
FWIW, my .profile may require user input (yeah, I know, I'll fix it eventually), so if espanso for some reason loads .profile internally when starting, that could be causing the timeout.  
This issue has been occurring since I upgraded to v2, I just have been to lazy to file an issue until now.

**Comment by federico-terzi** [comment]
Hey @SamuelSwartzberg,

Thanks for reporting this issue!
That's really interesting, yes espanso _might_ load the content of `.profile` in certain occasions (such as when running a shell script), but IIRC it doesn't on startup
I suspect this might be due to the way you added Espanso to the PATH (usually on macOS Espanso creates a symlink in `/usr/local/bin` which points to the executable, rather than adding the folder to the path)

Cheers :)

**Comment by SamuelSwartzberg** [comment]
Huh, I also thought adding a path into `Applications` to my PATH was weird, but I didn't/don't have that symlink. I added it with `sudo ln -s /Applications/Espanso.app/Contents/MacOS/espanso /usr/local/bin/espanso`, but still, no dice. Even after removing the dir from PATH so that `which espanso` points to `/usr/local/bin/espanso`, it still gives the exact same error and log output.

**Comment by SamuelSwartzberg** [comment]
Ah, but it seems that reinstalling via homebrew produces a symlink in `/opt/homebrew/bin/espanso` (I really should have mentioned that I'm using Apple silicon now that I think about it), which is on-PATH for most Apple silicon homebrew users and seems to work. Could we add this to documentation and a note to the setup wizard what people have to add to their PATH if they choose to not add it automatically?
