### ISSUE TITLE
Windows 11: can't trigger powershell scripts via espanso

### ISSUE THREAD

**Issue by nocorners** [espanso/espanso#1103]
**Describe the bug**

`<script> cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170`
That is despite Execution Policy being set to Remote Signed (the typical fix in PS for that error message)

Not sure if this could be a PS bug instead, I just expected the expansion to work with the script. Had no trouble doing the same with WSL.

**To Reproduce**

1. have Windows 11, PowerShell 7.2.3,  Espanso 2.1.5-beta installed
2. set Execution Policy in admin PowerShell to Remote Signed
3. use a trigger with script. My case: combined with clipboard, meant to process a long messy URL into a readable markdown link. Script is basically a couple of RegEx replacements:
  ```
    - trigger: ":link"
      replace: "{{output}}"
      force_clipboard: true
      vars:
        - name: clip
          type: clipboard
        - name: output
          type: shell
          params:
            cmd: "<path to script.ps1> -url '{{clip}}'"
            shell: powershell
  ```
3. trigger the `:link`
4. get `[Espanso]: An error occurred during rendering, please examine the logs for more information.`
5. in logs, see `<script> cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170`

**Expected behavior**

Expected the script to run ok.

**Logs**

```
13:38:50 [worker(20072)] [ERROR] shell command exited with code: exit code: 1 and error: C:\Users\user\AppData\Roaming\espanso\match\scripts\script.ps1 : File C:\Users\user\AppData\Roaming\espanso\match\scripts\script.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170. 
At line:1 char:1
+ C:\Users\user\AppData\Roaming\espanso\match\scripts\script ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

13:38:50 [worker(20072)] [WARN] extension 'shell' on var: 'output' reported an error: command reported error: '`C:\Users\user\AppData\Roaming\espanso\match\scripts\script.ps1 : File C:\Users\user\AppData\Roaming\espanso\match\scripts\script.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ C:\Users\user\AppData\Roaming\espanso\match\scripts\script ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
`'
13:38:50 [worker(20072)] [ERROR] error during rendering: rendering error

Caused by:
    command reported error: '`C:\Users\user\AppData\Roaming\espanso\match\scripts\script.ps1 : File C:\Users\user\AppData\Roaming\espanso\match\scripts\script.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    At line:1 char:1
    + C:\Users\user\AppData\Roaming\espanso\match\scripts\script ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : SecurityError: (:) [], PSSecurityException
        + FullyQualifiedErrorId : UnauthorizedAccess
    `'
```

**Setup information**

- OS: Windows 11 (with PowerShell 7.2.3)
- Version: Espanso 2.1.5-beta

**Comment by andrewcincotta** [comment]
Have you been able to solve this yet?

**Comment by nocorners** [comment]
The issue was on my work laptop. I have since switched to Linux, meaning I can't give you much useful info off the bat. (Also, Espanso on Linux works great!)I do have access to Windows machines, though. If I get any free-ish time at work, I will get you data on reproducibility. I'm not too great with Powershell, so user error is also a possibility unless I can prove otherwise.Dne 29. 11. 2022 23:49 napsal uživatel Andrew Cincotta ***@***.***>:
Have you been able to solve this yet?

**Comment by AucaCoyan** [comment]
Hi! We updated the pwsh engine with espanso. Could you try with the new version? feel free to reopen the issue!
