### ISSUE TITLE
Powershell is used instead of command prompt using the "cmd" command

### ISSUE THREAD

**Issue by linearproblem** [espanso/espanso#1124]
**Describe the bug**
When using the cmd parameter, powershell is used to execute the command rather than command prompt which causes errors on my computer. 

`matches:
  - trigger: ":wtc"
    replace: "{{output}}"
    vars:

      - name: output
        type: shell
        params:
          cmd: curl -s whatthecommit.com/index.txt
`

**To Reproduce**
The command above and other ones using cmd have the same error.  This is from the *wtc* plugin. 
Just after typing ":wtc", mentioned as I don't think this is isolated to the single plugin. 

**Expected behavior**
The command works correctly on command prompt, but not on powershell. 

**Screenshots**
I've added the command when entered into powershell (which is the same as the error in the espanso log file), as well as the expected output from the command prompt window.

![Error-Espanso](https://user-images.githubusercontent.com/47994813/171365923-fb9f7c5c-d05f-4191-9fad-0bd2ff79ff7f.png)

**Logs**
```
18:23:40 [worker(11884)] [ERROR] error during rendering: rendering error

Caused by:
    command reported error: '`Invoke-WebRequest : Cannot process command because of one or more missing mandatory parameters: Uri.
    At line:1 char:1
    + curl -s whatthecommit.com/index.txt
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
        + FullyQualifiedErrorId : MissingMandatoryParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
     
    `'
```

**Setup information**
- OS: Windows 11 Education Edition, mentioned as it may act differently to Windows Home. 
- Version: 2.1.5-beta

**Comment by federico-terzi** [comment]
Hey @linearproblem,

I'm sorry you experienced this problem! That's interesting, in the meantime you might want to try the `shell: cmd` option: https://espanso.org/docs/matches/extensions/#choosing-the-shell

Cheers :)
