### ISSUE TITLE
Waking Mac from Sleep Locks up Espanso Access

### ISSUE THREAD

**Issue by mbeaty-sf** [espanso/espanso#1125]
**Describe the bug**
When waking my Mac from sleep, Espanso 2.1.5 beta seems to lock up and I am unable to access it from the menu bar, or through my assigned search_shortcut. (For the record I am using a Meh key modifier, so my search_shortcut is set to SHIFT+ALT+CTRL+SPACE)

When I check the logs, immediately after sleep, this is what I see:

```
12:19:39 [worker(30840)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
12:21:01 [worker(30840)] [INFO] secure input has been disabled
```

**To Reproduce**
1. Start Espanso
2. Ensure that you can pull up the search window through shortcut
3. Put computer to sleep
4. Wake computer
5. Attempt to access Espanso search window through shortcut key, or access Espanso through menu icon and see that it will not open
6. Attempt to run command in terminal: `espanso restart` and receive:
```
unable to stop espanso: worker timed out
espanso is already running!
```

**Expected behavior**
After waking from sleep I expect Espanso to be accessible

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
```
12:09:56 [daemon(30839)] [INFO] reading configs from: "/Users/mbeaty/Library/Preferences/espanso"
12:09:56 [daemon(30839)] [INFO] reading packages from: "/Users/mbeaty/Library/Preferences/espanso/match/packages"
12:09:56 [daemon(30839)] [INFO] using runtime dir: "/Users/mbeaty/Library/Application Support/espanso"
12:09:56 [daemon(30839)] [INFO] watching for changes in path: "/Users/mbeaty/Library/Preferences/espanso"
12:09:56 [daemon(30839)] [INFO] espanso version: 2.1.5-beta
12:09:56 [daemon(30839)] [INFO] spawning the worker process...
12:09:56 [daemon(30839)] [INFO] binded to IPC unix socket: /Users/mbeaty/Library/Application Support/espanso/espansodaemonv2.sock
12:09:56 [worker(30840)] [INFO] reading configs from: "/Users/mbeaty/Library/Preferences/espanso"
12:09:56 [worker(30840)] [INFO] reading packages from: "/Users/mbeaty/Library/Preferences/espanso/match/packages"
12:09:56 [worker(30840)] [INFO] using runtime dir: "/Users/mbeaty/Library/Application Support/espanso"
12:09:56 [worker(30840)] [INFO] binded to IPC unix socket: /Users/mbeaty/Library/Application Support/espanso/espansoworkerv2.sock
12:09:56 [worker(30840)] [INFO] using CocoaAppInfoProvider
12:09:56 [worker(30840)] [INFO] monitoring the status of the daemon process
12:09:56 [worker(30840)] [INFO] monitoring the status of secure input
12:09:56 [worker(30840)] [INFO] using CocoaSource
12:09:56 [worker(30840)] [INFO] using MacInjector
12:09:56 [worker(30840)] [INFO] using CocoaClipboard
**<<<sleep>>>**
**<<<wake>>>**
12:19:39 [worker(30840)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
12:21:01 [worker(30840)] [INFO] secure input has been disabled
12:26:56 [worker(30840)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
12:30:31 [service(36340)] [INFO] reading configs from: "/Users/mbeaty/Library/Preferences/espanso"
12:30:31 [service(36340)] [INFO] reading packages from: "/Users/mbeaty/Library/Preferences/espanso/match/packages"
12:30:31 [service(36340)] [INFO] using runtime dir: "/Users/mbeaty/Library/Application Support/espanso"
12:30:34 [service(36340)] [ERROR] unable to stop espanso: worker timed out
12:30:34 [service(36340)] [ERROR] espanso is already running!
```

**Setup information**
- OS: macOS 12.4
- Version: espanso 2.1.5-beta

**Comment by mbeaty-sf** [comment]
Just to add as well, in this state, I have to force quit and re-open espanso before I can interact with it again.

**Comment by federico-terzi** [comment]
Hey @mbeaty-sf,

Thanks for reporting this issue! Could you please post a screenshot of the Espanso icon after you wake up from sleep?

Cheers :)

**Comment by mbeaty-sf** [comment]
So after waking it again, it actually may not necessarily be the sleep/wake that is causing this but something with secure input? When I check the log, sometimes it seems to say "Google Chrome" and sometimes it seems to be "logwindow" as mentioned in the error I shared above. In both instances, the icon does not change and still appears as:

![image](https://user-images.githubusercontent.com/53280203/173444998-d8daf127-e2f7-4745-8690-03b35737ce83.png)

It's just that when I go to use my "search window" hotkey after (I believe) the secure input error, it locks up and if I click the menu bar icon, there is no dropdown, nothing appears.

**Comment by mbeaty-sf** [comment]
I think I may have inadvertently combined 2 issues in this one... It seems that sometimes the log shows the secure input, and that could very well be because of a browser's password manage, and clicking into a tab on Chrome is conflicting with the password manager,[as you have documented here](https://espanso.org/docs/troubleshooting/secure-input/#:~:text=Secure%20Input%20is%20a%20macOS,such%20as%20a%20password%20field.), but what seems to happen more often is I can occasionally launch the search bar with my hotkey, but then the second time I attempt it, it won't load, and espanso locks up (but the icon doesn't change). I also don't see the "SecureInput auto-fixer" in my menu when I launch 

When I run `espanso log` no action is appearing, it just shows the log at the point of launch with nothing out of the ordinary. So I am not sure if SecureInput is to blame here, or if it is something to do with my hotkey choice.

**Comment by mbeaty-sf** [comment]
Also this error does sometimes appear:

```
11:04:04 [worker(5754)] [INFO] secure input has been disabled
11:05:16 [worker(5754)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
```

**Comment by mbeaty-sf** [comment]
After updating to the most recent beta, his hotkey is no longer crashing/locking up espanso. Will update if anything changes.
