### ISSUE TITLE
Documentation enhancement: Windows path to configuration can be simplified

### ISSUE THREAD

**Issue by e-r-n-i-e** [espanso/espanso#1126]
The path to the config files on Windows in the documentation can be simplified:
`%AppData%\espanso`
This resolves to `C:\Users\YOURUSERNAME\AppData\Roaming\espanso`

See [https://espanso.org/docs/get-started/#configuration](url)

**Comment by federico-terzi** [comment]
Hey @e-r-n-i-e,

Thank you for the feedback! That's a good point, my only concern is that for non-technical users, `%AppData%\espanso` might be harder to understand. What do you think?

Cheers :)

**Comment by IdiosApps** [comment]
In `Developer Powershell for VS` I get 🚫 
```
cd %AppData%
cd : Cannot find path 'C:\Users\idiosapps\%AppData%' because it does not exist.
At line:1 char:1
```
In git terminal with MINGW64 I get 🚫 
```
 cd %AppData%
bash: cd: %AppData%: No such file or directory
```
In `Developer Command Prompt` it works ✅ 
```
cd %AppData%
C:\Users\idiosapps\AppData\Roaming>
```

Given that it doesn't work in 2 of 3 cases - I'm hesitant to recommend it. It's a bit brittle, and as noted above it could make the experience much trickier.

**Comment by e-r-n-i-e** [comment]
That %appdata% does not work with PowerShell surprises me, but hey - this is Microsoft.

The most comon way to use %AppData% is probably to press Win+R and enter %Appdata% into the dialogue. But given the fact that this does not work with PowerShell (or MinGW) it might be best to add it as an alternative. The problem with the current documentation is that the folder "AppData" is hidden by default. So if a non-technical user tries to navigate to the path using Windows Explorer he/she won't find it.

Proposal:
+ Windows:
  + Press Win+R (the Windows logo key and "R" simultaneously) to open the Run App. In the "Open" field, enter "%AppData%\espanso" (without the quotation marks) and press Enter or click OK to open the folder in Windows Explorer.
  + If you prefer to use PowerShell you should use the path C:\Users\<YOUR_USERNAME>\AppData\Roaming\espanso (you need to replace <YOUR_USERNAME> with the name of your Windows account).
