### ISSUE TITLE
Synchronizing Espanso with Dropbox on MacOS causes inability to restart Espanso

### ISSUE THREAD

**Issue by avi-cenna** [espanso/espanso#1127]
**Describe the bug**
I am unable to restart Espanso after creating the symlink for Dropbox. I was able to resolve the issue by simply moving the Espanso app into the trash, and then reinstalling Espanso using the official bundle. After reinstalling Espanso, it automatically detected the symlink to the config folder without error.

**To Reproduce**
I ran commands similar to the block below per the official documentation, but was unable to restart Espanso after creating the symlink. I believe I stopped Espanso by right-clicking the icon in Mac and then clicking "exit" before creating the symlink.

```bash
~/Dropbox
❯ ln -s /Users/johndoe/Dropbox/espanso "/Users/johndoe/Library/Application Support/espanso"

~/Dropbox
❯ espanso restart
espanso is not running!
unable to start service: launchctl exited with non-zero code `exit status: 3`

~/Dropbox
❯ espanso start
unable to start service: launchctl exited with non-zero code `exit status: 3`
```

**Setup information**
- OS: MacOS Monterey 12.4
- Version: espanso 2.1.5-beta

**Comment by fharper** [comment]
@avi-cenna : turn on accessibility for espanso in the macOS security settings, and try to register again. Worked for me.

**Comment by avi-cenna** [comment]
I am going to close this since I still use espanso and haven't run into any trouble lately. Thanks!
