### ISSUE TITLE
Choice extension not working

### ISSUE THREAD

**Issue by karanrajpal14** [espanso/espanso#1141]
**Describe the bug**
I've been trying to set-up an expansion using the choice extension but for some reason, I cannot get it to work at all.
Here's one of the expansions I'm using to test this right now:
```yaml
  - trigger: ":ctest"
    label: "[Test] Choice List"
    replace: "{{selection}}"
    vars:
      - name: selection
        type: choice
        params:
          values:
              - "Xylophone"
              - "Cat"
              - "Rambutan"
              - "Alarm"
```

But, when I type out the trigger, nothing happens at all. No error or anything like that.
Logs don't mention anything either so I'm not sure if I'm doing something wrong.
Would you please help me with this? I can provide more details if necessary.

**To Reproduce**
Just add the above to your `base.yml` and type `:ctest` anywhere

**Expected behavior**
Choice extension shows up and allows you to select one of the choices

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem
```
...
...
09:26:05 [worker(871)] [INFO] secure input has been disabled
09:33:34 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Control, 59)], sending compensating events...
09:33:50 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
09:51:06 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Control, 59)], sending compensating events...
10:45:57 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:02:05 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:03:02 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:04:06 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:05:19 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:07:37 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:19:17 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Control, 59)], sending compensating events...
11:33:59 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:34:27 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:37:49 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:42:03 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
11:44:05 [worker(871)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
```

**Setup information**
- OS: `MacOS Big Sur 11.6.6`
- Version: `espanso 2.1.5-beta`

**Comment by federico-terzi** [comment]
@karanrajpal14 I'm sorry you experienced this problem! Your example is working correctly for me, so there might be something different between our systems. Is the search bar working as expected for you?

**Comment by karanrajpal14** [comment]
Yes, the search bar works just fine but I don't see the test example in that as well. Not sure if something's missing on my system. Is there any way I can provide some more detailed logs to see what the issue is?

**Comment by federico-terzi** [comment]
@karanrajpal14 Sorry for the late reply! Could you please try to:
* Trigger the match you posted as example
* Check if a new Espanso crash dump appears, as described here? https://apple.stackexchange.com/questions/26480/where-can-i-find-my-crash-logs#:~:text=To%20find%20the%20crash%20files,Library%2FLogs%2FDiagnosticReports%20).

I'm wondering if a segmentation fault is happening with those parameters

**Comment by smeech** [comment]
Is this still a problem with the current release? I'll close it for now, but am happy to reopen if necessary.
