### ISSUE TITLE
Issue with spaces in ONLYOFFICE Desktop Editors

### ISSUE THREAD

**Issue by Silverhawk85** [espanso/espanso#1146]
I use the ONLYOFFICE Desktop Editors v7.1.0.215 on my Windows 10 laptop and it seems as if the Document and Form template App don't recognize spaces between words when I use Espanso v2.1.5-beta. The words are all put together with no spaces in one line.

In the Spreadsheet and Presentation App it works fine.

This might also be an issue on the ONLYOFFICE side?

**Comment by smeech** [comment]
Is this still a problem with the current release?
Many of these problems can be resolved via [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) for individual triggers (leading to changes in the `backend:` globally or in app-specific configurations), and occasionally with other [options](https://espanso.org/docs/configuration/options/). 
Have you tried those?

**Comment by Silverhawk85** [comment]
Sorry I cant answer that, because I switched from Windows to Linux Mint over a year ago. For me the problem is solved. : )
