### ISSUE TITLE
I'm not able to open Espanso after installing it.

### ISSUE THREAD

**Issue by cardosodealmeida** [espanso/espanso#1155]
**Describe the bug**
I'm not being able to open espanso.

**To Reproduce**
1. I Installed using Homebrew
2. On the terminal I got 🍺  espanso was successfully installed!
3. When I try to open espanso I get the message "Espanso can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."
4. When I click the right button and select open nothing happens. 

<img width="293" alt="Screenshot 2022-06-28 at 09 17 04" src="https://user-images.githubusercontent.com/25393356/176131317-364edb57-6748-4b65-b8e4-9da141371336.png">

**Expected behavior**
I should be able to open the app.

**Setup information**
- OS: What OS are you using? macOS Monterey
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
Version v2.1.5-beta

**Comment by federico-terzi** [comment]
Hey @cardosodealmeida,

Thanks for reporting this issue! Are you running on a M1 or Intel based mac?

Cheers :)

**Comment by cardosodealmeida** [comment]
Hi Federico!

Thanks for taking the time to reply me. It’s Saturday, I don’t want to take you from your leisure time. We can speak Monday if you want.

I’m running on M1 Mac.

Kind regards,
Manuel

No dia 02/07/2022, às 12:36, Federico Terzi ***@***.***> escreveu:

﻿

Hey @cardosodealmeida<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcardosodealmeida&data=05%7C01%7C%7Cd15245a3c0eb4613744808da5c1f12bd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637923585772681616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Dh16r0mSVKg6kCpVYO3wWWUGBSQJUN%2FzioxcZrS5y38%3D&reserved=0>,

Thanks for reporting this issue! Are you running on a M1 or Intel based mac?

Cheers :)

**Comment by Khadeeejah** [comment]
I just installed Espanso on an M1 Mac running Monterey and ran into this issue. I was able to resolve it by right clicking on Espanso, which shows the same dialog but now, it has the Open button. Click that.

After that I ran into the issue highlighted in #1099.
