### ISSUE TITLE
Compatibility mode

### ISSUE THREAD

**Issue by DutchPete** [espanso/espanso#1160]
I have installed Espanso v.2 on Linux. A month ago Espanso's GUI would open every time I would launch the app. In the bottom left corner there is a compatibility mode - I used it because I made my yaml rules in v0.7.

The GUI does not open anymore even though espanso is running. How can I open the GUI?

**Comment by federico-terzi** [comment]
Hey @DutchPete,

It seems Espanso is not detecting a legacy configuration anymore, Could you please post the output of `espanso log` here?

Cheers :)

**Comment by DutchPete** [comment]
Hi Federico,

see attachment.




Jul 2, 2022, 11:29 by ***@***.***:
