### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#1276]
Hey all!

To better support the Espanso community, I'm moving existing feature requests to GitHub's [Discussions](https://github.com/federico-terzi/espanso/discussions), so that they can be upvoted and prioritized based on the interest of the community.

If you want to create a new feature request, please do so in the [Discussions](https://github.com/federico-terzi/espanso/discussions) section, and feel free to upvote the features you would like the most! This way, we can periodically reprioritize our efforts to meet community needs better.

Happy expanding!
Federico

**Comment by RokeJulianLockhart** [comment]
As https://github.com/espanso/espanso/discussions/1755#discussion-5889717 states:

> I can't subscribe solely to issue closure in a discussion.

**Comment by AucaCoyan** [comment]
Correct! I [copy here the response](https://github.com/espanso/espanso/discussions/1755#discussioncomment-7669223) to give some context
> Every repo manages issues differently, and this is the way we chose to manage feature requests. It "loses" notification customization, but "wins" votes from the users, and we value more the community feedback than if we close or not a feature request issue (not bugs!)

**Comment by phorcys420** [comment]
> Correct! I [copy here the response](https://github.com/espanso/espanso/discussions/1755#discussioncomment-7669223) to give some context
> > Every repo manages issues differently, and this is the way we chose to manage feature requests. It "loses" notification customization, but "wins" votes from the users, and we value more the community feedback than if we close or not a feature request issue (not bugs!)

Not if the espanso repo used issues with a "feature-request" flair and reactions (usually 👍) to mimic upvotes, that's what a lot of repos do, maybe that's suitable for this project?

**Comment by AucaCoyan** [comment]
We now deprecated the forums and opened again issues to feature requests!
