### ISSUE TITLE
:>> shortcut not displ;ayed correctly in search window

### ISSUE THREAD

**Issue by ScottKillen** [espanso/espanso#1278]
**Describe the bug**
I have a match defined with the trigger ":>>". In the search window the trigger displays as ":"

**To Reproduce**
1. Define a match with a trigger of ":>>"
2. Call up the search window.
3. Notice the incorrect test in the window.

**Expected behavior**
I expect the trigger ":>>" will be displayed the same way that ":<<" is.

**Screenshots**
![image](https://user-images.githubusercontent.com/1509989/177010319-7ca01c1e-975f-492c-8429-dc2f7a0bea04.png)

**Logs**
N/A

**Setup information**
- OS: Windows 11
- Version: 2.1.5-beta

**Comment by smeech** [comment]
This no longer seems to be a problem. I'll close the Issue, but am happy to reopen it if necessary.

![Screenshot_2024-02-15_23-30-02](https://github.com/espanso/espanso/assets/47302288/f90a47e7-c8d1-4c20-95c0-f11a791935ab)
