### ISSUE TITLE
Espanso is unable to find keyboard layout under manjaro kde 5.24.5 with wayland session

### ISSUE THREAD

**Issue by vroger11** [espanso/espanso#1280]
**Describe the bug**
Espanso can't surcharge keywords as it is unable to detect my keyboard layout.

**To Reproduce**
1. use french keyboard layout. (I don't know for other keyboards)
2. Be on a wayland session.
3. launch espanso

As a workaround, I add the following line in my `config/default.yml` file:
```
keyboard_layout: { layout: fr }
```

**Expected behavior**
Espanso find automatically my keyboard layout under Wayland session.

**Logs**
```
10:30:24 [worker(5972)] [INFO] reading configs from: "/home/vroger/.config/espanso"
10:30:24 [worker(5972)] [INFO] reading packages from: "/home/vroger/.local/share/espanso/packages"
10:30:24 [worker(5972)] [INFO] using runtime dir: "/home/vroger/.local/share/espanso"
10:30:24 [worker(5972)] [INFO] binded to IPC unix socket: /home/vroger/.local/share/espanso/espansoworkerv2.sock
10:30:24 [worker(5972)] [INFO] using WaylandAppInfoProvider
10:30:24 [worker(5972)] [INFO] monitoring the status of the daemon process
10:30:24 [worker(5972)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
10:30:24 [worker(5972)] [INFO] using EVDEVSource
10:30:25 [worker(5972)] [INFO] Querying modifier status...
10:30:25 [worker(5972)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
10:30:25 [worker(5972)] [INFO] using EVDEVInjector
10:30:25 [worker(5972)] [INFO] using WaylandFallbackClipboard
```

**Setup information**
- Manjaro with kde 5.24.5 under plasma wayland session
- espanso 2.1.5-beta

**Comment by Vistaus** [comment]
Similar to the bug I reported: #1057

**Comment by vroger11** [comment]
It seems slightly different as espanso is running in my case and a restart shut down espanso first. Also, except the surcharge of keywords (which is the main purpose of espanso) other functionalities work (like the search bar and notifications).

**Comment by Vistaus** [comment]
That's why I said "similar" rather than "is the same as".

**Comment by vroger11** [comment]
I did not know how similar it was, and I mainly commented for others to quickly seeing the difference, no offense intended 😉

**Comment by smeech** [comment]
This is a [documented](https://espanso.org/docs/install/linux/#final-steps) limitation of the current situation with Wayland. I'll close the issue for now.
