### ISSUE TITLE
Hash symbol `#` does not get expanded

### ISSUE THREAD

**Issue by awehrung** [espanso/espanso#1285]
**Describe the bug**

Text replacements that contain a hash symbol (or pound sign) `#` are triggered correctly but the replacement text does not include the symbol. I encounter this bug when triggering the replacement in text editor and browser, it works as expected in the terminal.

I've had a coworker test this on their machine (same espanso version, same OS) and they do not get the bug. Any idea what could cause this? Thanks a lot in advance!

**To Reproduce**

From `match/default.yml`:

```yaml
  - trigger: ":1hash"
    replace: "Test \\#1"
  - trigger: ":2hash"
    replace: "Test #2"
  - trigger: ":3hash"
    replace: 'Test \#3'
  - trigger: ":4hash"
    replace: 'Test #4'
  - trigger: ":5hash"
    replace: "Test \u00235"
```
None of those triggers let a `#` appear when using in text editor or browser. Instead I get the following:

```
Test \1
Test 2
Test \3
Test 4
Test 5
```

**Expected behavior**

The hash symbol `#` appears correctly in replacement texts; I want to use this to speed up some repetitive markdown tasks.

**Screenshots**

n/a

**Logs**

Normal restart logs as far as I can see:

```
10:23:10 [daemon(3230)] [INFO] configuration change detected, restarting worker process...
10:23:10 [worker(302721)] [INFO] engine eventloop has terminated, propagating exit event...
10:23:10 [worker(302721)] [INFO] waiting for engine exit mode...
10:23:10 [worker(302721)] [INFO] exiting worker process...
10:23:10 [daemon(3230)] [INFO] spawning the worker process...
10:23:10 [worker(304278)] [INFO] reading configs from: "/home/REDACTED/.config/espanso"
10:23:10 [worker(304278)] [INFO] reading packages from: "/home/REDACTED/.config/espanso/match/packages"
10:23:10 [worker(304278)] [INFO] using runtime dir: "/home/REDACTED/.cache/espanso"
10:23:10 [worker(304278)] [INFO] binded to IPC unix socket: /home/REDACTED/.cache/espanso/espansoworkerv2.sock
10:23:10 [worker(304278)] [INFO] using X11AppInfoProvider
10:23:10 [worker(304278)] [INFO] monitoring the status of the daemon process
10:23:10 [worker(304278)] [INFO] using X11Source
10:23:10 [worker(304278)] [INFO] using X11Injector
10:23:11 [worker(304278)] [INFO] using X11Clipboard
10:23:31 [service(304893)] [INFO] reading configs from: "/home/REDACTED/.config/espanso"
10:23:31 [service(304893)] [INFO] reading packages from: "/home/REDACTED/.config/espanso/match/packages"
10:23:31 [service(304893)] [INFO] using runtime dir: "/home/REDACTED/.cache/espanso"
10:23:31 [service(304893)] [INFO] espanso is running
```

**Setup information**
- OS: Ubuntu 20.04
- Version: espanso 2.1.5-beta

**Comment by awehrung** [comment]
I just noticed that `2.1.6-beta` has been released last night; the new option `x11_use_xdotool_backend` solved my problem. Thanks a lot, keep up the amazing work!

**Comment by andreystepanov** [comment]
For anyone else who also couldn't figure out why it isn't working inside  terminal (`kitty` in my case), just use `disable_x11_fast_inject = true`, and it would fix it (tested with just this option, to make sure nothing else is relevant to this issue).

It was expanding just fine outside of terminal, though.

And previously mentioned option `x11_use_xdotool_backend = true` didn't do it for my environment (`kitty` under `NixOS`).
