### ISSUE TITLE
Can't open on MacOS 12.4

### ISSUE THREAD

**Issue by fightyz** [espanso/espanso#1295]
**Describe the bug**
After install (no matter from brew or .zip), espanso just crash when open.

**To Reproduce**
1. open espanso from Application folder

**Expected behavior**
Open normally.

**Screenshots**
![open_espanso](https://user-images.githubusercontent.com/1697504/178924055-65810a34-9442-4d5e-9f9c-2d77c2c02cb1.gif)

**Logs**
can't get log, `espanso log` output:
```shell
$ espanso log
thread 'main' panicked at 'unable to create config directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }', espanso-path/src/lib.rs:48:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Setup information**
- OS: What OS are you using?
MacOS 12.4
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
espanso 2.1.6-beta

**Comment by fightyz** [comment]
I figure it out: I have make a soft link to the ` ~/Library/Application Support/espanso`. But the link's target destination is wrong.

**Comment by fatlazycat** [comment]
@fightyz  Sorry can I asked what you did with to fix this. Just got this on Sonoma with espanso 2.1.8. Thanks
