### ISSUE TITLE
Heads up - wxgtk2 has been withdrawn on Archlinux/Manjaro/Endeavour etc.

### ISSUE THREAD

**Issue by xircon** [espanso/espanso#1297]
Don't know if it is a problem, updated before I came to work,  I was using the AUR git version.

Will check properly when I get home this evening.

https://forum.endeavouros.com/t/wxwidgets-3-2-update-may-need-manual-intervention/29249

Yup, dead:
```
espanso: error while loading shared libraries: libwx_baseu-3.0.so.0: cannot open shared object file: No such file or directory
```
Reverting with timeshift and adding wx to ignorepkg.

**Comment by slmb3** [comment]
You don't need to downgrade wx.
Update your `PKGBUILD` [to use `wxgtk3` instead of `wxgtk2`](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=espanso&id=2889e07108e4002c9914a3ee3e9a9c192e0343d4) then rebuild package.

**Comment by xircon** [comment]
Thankyou, hadn't considered that!!
