### ISSUE TITLE
Only first characters are typed in some apps

### ISSUE THREAD

**Issue by nathanlct** [espanso/espanso#1304]
**Describe the bug**

Characters seem to be injected block by block, but I haven't seen a customizable block size in the config. Some apps seem to not type out the whole block.

**To Reproduce**

```yml
matches:
  - trigger: "test"
    replace: "abcdefghijklmnopqrstuvwxyz"
```

Typing test outputs "abcuvw". This happens to me on MacOS in the Anki app. I haven't seen the issue in any other app so far.

**Expected behavior**

Expecting the whole alphabet to be typed. This seems to only output the first 3 characters of each block of 20 characters (I tried with other strings and it was consistent with that). When I set an `inject_delay: 500` for instance, blocks of 20 characters are typed instantly with a delay of 500ms between them. This is using the `backend: Inject` (the copy/paste backend works). I would have expected a 500ms delay but instead the injection happens block by block. The "bug" is likely on the Anki app's side, with some characters being pre-processed somehow. I'm thinking that inserting character by character instead of by blocks would work, so is there a way to customize the length of the block, which seems to be 20 here? 

**Logs**
No logs, just some characters are missed by the app I'm typing in and I'm wondering how I could make it work. 

**Setup information**
- OS: macOS Monterey 12.3.1.
- Version: espanso 2.1.5-beta

**Comment by Floydius** [comment]
fyi, i had this issue also, where only the first character of any replacement text (including dates) would be printed when triggered.

I found the issue is that I had another program running in the background (KeyboardUnchatter) to reduce duplicated keystrokes on my mechanical keyboard.  looks like something about the former was cancelling out what espanso was doing.

**Comment by smeech** [comment]
I'm trying to address, mop up, and prioritise the old Issues here.
Unless this is still a problem, I'll close this one - I'll happily reopen it if necessary.
In addition to @Floydius comment, many of these problems can be resolved via [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) for individual triggers (leading to changes in the `backend:` globally or in app-specific configurations), and occasionally with other [options](https://espanso.org/docs/configuration/options/).
