### ISSUE TITLE
`off`, `OFF`, and null search and toggle values

### ISSUE THREAD

**Issue by kemitchell** [espanso/espanso#1305]
Thanks for Espanso!

I've run into two small problems with 2.1.6-beta:

- Espanso will fail with an error when `search_shortcut` is set to `null` in configuration.

- Espanso will interpret `search_trigger: off` as setting the search trigger to `o`,`f`,`f`, rather than disabling it. The [documentation](https://espanso.org/docs/configuration/options/#customizing-the-search-trigger) is incorrect on this point.

I'd strongly recommend avoiding using `off` or `OFF` as magic values in YAML-based configuration, because the YAML spec defines them as synonyms for `false`. See https://yaml.org/type/bool.html

I spent a little time trying to find out whether serde_json interprets `off` and `OFF` per spec or not. Unfortunately I ran out of time.

I did find that Espanso handles conforming configuration values in `espanso-config/src/config/resolve.rs`. A number of `Some("off")` and `Some("OFF")` patterns in `match` arms should likely be replaced with checks for `serde_json`'s `Null` and `Bool` types.

**Comment by federico-terzi** [comment]
Hey @kemitchell,

Thanks for reporting this issue! Indeed, False/null values might have been a better choice to disable this feature, though I guess we'll live with "OFF" for a while due to backward compatibility reasons. The fact that it doesn't work is strange, are you using compatibility mode?

Cheers :)

**Comment by smeech** [comment]
I'm trying to address, mop up, and prioritise the old Issues here.
Unless this is still a problem, I'll close this one - I'll happily reopen it if necessary.
