### ISSUE TITLE
Forms not displayed on Windows (2.1.6 beta)

### ISSUE THREAD

**Issue by chrisweis** [espanso/espanso#1320]
**Describe the bug**
Forms are not interactive when displayed, when Espanso is installed in one Windows user profile and run in another user profile.

**To Reproduce**
1. Install Espanso (via chocolatey: "choco install espanso" in one user profile, then use Espanso in another user profile)
2. Add forms examples from the documentation to config file (https://espanso.org/docs/matches/forms/)
3. Type the command in Notepad (such as :greet or :form)
4. A form is displayed that doesn't allow input.

**Expected behavior**
Form should be interactive (allow text entry or use of a dropdown, for example).

**Screenshots**
![image](https://user-images.githubusercontent.com/13931731/181995073-4337099c-d78e-4a59-bd91-94170d5f5c8d.png)

**Logs**
Note: Espanso was installed via Windows profile UserA, a different user than my profile UserB using Espanso.

C:\Users\UserA\AppData\Local\Programs\espanso>19:56:35 [ INFO] espanso version 0.7.3
19:56:35 [ INFO] using config path: C:\Users\UserB\AppData\Roaming\espanso
19:56:35 [ INFO] using package path: C:\Users\UserB\AppData\Local\espanso\packages
19:56:35 [ INFO] spawning worker process...
19:56:35 [ INFO] Binding to named pipe: \\.\pipe\espansodaemon
19:56:35 [ INFO] initializing worker process...
19:56:35 [ INFO] Initializing Espanso resources in C:\Users\UserB\AppData\Local\espanso
19:56:35 [ INFO] Extracted bmp icon to: C:\Users\UserB\AppData\Local\espanso\espansoicon.bmp
19:56:35 [ INFO] Extracted 'ico' icon to: C:\Users\UserB\AppData\Local\espanso\espanso.ico
19:56:35 [ INFO] Extracted 'red ico' icon to: C:\Users\UserB\AppData\Local\espanso\espansored.ico
19:56:35 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
19:56:35 [ INFO] watching for changes in path: C:\Users\UserB\AppData\Roaming\espanso
19:56:36 [ INFO] Using modulo at "C:\\Users\\UserA\\AppData\\Local\\Programs\\espanso\\modulo"
19:56:36 [ INFO] worker is running!
20:00:35 [ INFO] change detected, restarting worker process...
20:00:35 [ INFO] terminating worker process
20:00:35 [ INFO] initializing worker process...
20:00:35 [ INFO] Initializing Espanso resources in C:\Users\UserB\AppData\Local\espanso
20:00:35 [ INFO] BMP already initialized, skipping.
20:00:35 [ INFO] ICO already initialized, skipping.
20:00:35 [ INFO] red ICO already initialized, skipping.
20:00:35 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
20:00:36 [ INFO] Using modulo at "C:\\Users\\UserA\\AppData\\Local\\Programs\\espanso\\modulo"
20:00:36 [ INFO] worker is running!
20:02:45 [ INFO] change detected, restarting worker process...
20:02:45 [ INFO] terminating worker process
20:02:45 [ INFO] initializing worker process...
20:02:45 [ INFO] Initializing Espanso resources in C:\Users\UserB\AppData\Local\espanso
20:02:45 [ INFO] BMP already initialized, skipping.
20:02:45 [ INFO] ICO already initialized, skipping.
20:02:45 [ INFO] red ICO already initialized, skipping.
20:02:45 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
20:02:46 [ INFO] Using modulo at "C:\\Users\\UserA\\AppData\\Local\\Programs\\espanso\\modulo"
20:02:46 [ INFO] worker is running!
20:03:22 [ERROR] Could not render match: :greet
20:03:30 [ERROR] Could not render match: :greet
20:03:56 [ERROR] Could not render match: :greet
20:04:16 [ INFO] change detected, restarting worker process...
20:04:16 [ INFO] terminating worker process
20:04:17 [ INFO] initializing worker process...
20:04:17 [ INFO] Initializing Espanso resources in C:\Users\UserB\AppData\Local\espanso
20:04:17 [ INFO] BMP already initialized, skipping.
20:04:17 [ INFO] ICO already initialized, skipping.
20:04:17 [ INFO] red ICO already initialized, skipping.
20:04:17 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
20:04:17 [ INFO] Using modulo at "C:\\Users\\UserA\\AppData\\Local\\Programs\\espanso\\modulo"
20:04:17 [ INFO] worker is running!
20:04:26 [ERROR] Could not render match: :greet
20:05:05 [ INFO] change detected, restarting worker process...
20:05:05 [ INFO] terminating worker process
20:05:06 [ INFO] initializing worker process...
20:05:06 [ INFO] Initializing Espanso resources in C:\Users\UserB\AppData\Local\espanso
20:05:06 [ INFO] BMP already initialized, skipping.
20:05:06 [ INFO] ICO already initialized, skipping.
20:05:06 [ INFO] red ICO already initialized, skipping.
20:05:06 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
20:05:06 [ INFO] Using modulo at "C:\\Users\\UserA\\AppData\\Local\\Programs\\espanso\\modulo"
20:05:06 [ INFO] worker is running!
20:05:18 [ INFO] change detected, restarting worker process...
20:05:18 [ INFO] terminating worker process
20:05:18 [ INFO] initializing worker process...
20:05:18 [ INFO] Initializing Espanso resources in C:\Users\UserB\AppData\Local\espanso
20:05:18 [ INFO] BMP already initialized, skipping.
20:05:18 [ INFO] ICO already initialized, skipping.
20:05:18 [ INFO] red ICO already initialized, skipping.
20:05:18 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
20:05:19 [ INFO] Using modulo at "C:\\Users\\UserA\\AppData\\Local\\Programs\\espanso\\modulo"
20:05:19 [ INFO] worker is running!
20:05:52 [ERROR] Could not render match: :form
20:17:17 [ERROR] Could not render match: :form
20:17:31 [ERROR] Could not render match: :form
20:18:35 [ERROR] Could not render match: :form
20:19:05 [ERROR] Could not render match: :form
20:19:35 [ERROR] Could not render match: :form
20:22:40 [ERROR] Could not render match: :form
20:22:50 [ERROR] Could not render match: :form

**Setup information**
- OS: Windows 11 (21H2)
- Version: 2.1.6 beta

**Comment by Pete5x5** [comment]
@chrisweis I was having the same issue until I realized that chocolatey is installing the legacy version of espanso.  If I'm not mistaken it looks like your logs are also showing the legacy version (0.7.3).

Try uninstalling the chocolatey version (choco uninstall espanso) and install the new version from https://espanso.org/install/

Hope that helps!

**Comment by chrisweis** [comment]
That fixed it!  Thanks @Pete5x5!
![image](https://user-images.githubusercontent.com/13931731/186039149-d48b5134-3f34-4538-95e2-360cfa822dae.png)

BTW, you've probably heard this before, I think Espanso would be a LOT easier if there was a link from the to open the folder containing the config:
![image](https://user-images.githubusercontent.com/13931731/186039249-b0dd4d9f-3670-4cd6-b8ed-d0b122597d1e.png)

**Comment by Pete5x5** [comment]
This is not really the same thing, but it might help: you can open the config easily by using `espanso edit` in your terminal.  See https://espanso.org/docs/configuration/basics/#editing-cli-shortcut 

Also, you should mark this issue as resolved 😃

**Comment by chrisweis** [comment]
Thanks!
