### ISSUE TITLE
Installed package doesn't work

### ISSUE THREAD

**Issue by mturilin** [espanso/espanso#1325]
Environment:
- MacOS 12.4 on Intel MBP
- Lastest espanso.

Scenario:
1. install espanso
2. enable it the mac security settings to launch and accessibility options
3. check that it's working (:espanso expands!)
4. Install `basic-emojis` by typing `espanso install basic-emojis" -- success
5. restart espanso
6. type ":ook" in text editor

Expected:
the text replaced with thumps up emojis

Observed:
No expansion

**Comment by mturilin** [comment]
Logs:
```
12:59:23 [worker(88719)] [INFO] engine eventloop has terminated, propagating exit event...
12:59:23 [worker(88719)] [INFO] waiting for engine exit mode...
12:59:23 [worker(88719)] [INFO] exiting worker (to be restarted)
12:59:23 [daemon(87742)] [INFO] worker requested a restart, spawning a new one...
12:59:23 [daemon(87742)] [INFO] spawning the worker process...
12:59:23 [worker(88780)] [INFO] reading configs from: "/Users/mikhail/Library/Application Support/espanso"
12:59:23 [worker(88780)] [INFO] reading packages from: "/Users/mikhail/Library/Application Support/espanso/packages"
12:59:23 [worker(88780)] [INFO] using runtime dir: "/Users/mikhail/Library/Application Support/espanso"
12:59:23 [worker(88780)] [INFO] system info: Darwin v12.4 - kernel: 21.5.0
12:59:23 [worker(88780)] [INFO] using CocoaAppInfoProvider
12:59:23 [worker(88780)] [INFO] binded to IPC unix socket: /Users/mikhail/Library/Application Support/espanso/espansoworkerv2.sock
12:59:23 [worker(88780)] [INFO] using CocoaSource
12:59:23 [worker(88780)] [INFO] monitoring the status of secure input
12:59:23 [worker(88780)] [INFO] monitoring the status of the daemon process
12:59:23 [worker(88780)] [INFO] using MacInjector
12:59:23 [worker(88780)] [INFO] using CocoaClipboard
```

**Comment by MaximilianKindshofer** [comment]
Same here; if I add the lines to base.yml is works fine; but the package directory doesn't

**Comment by pocc** [comment]
I am also experiencing this issue.

**Comment by LifeBalanceGuru** [comment]
I think the emoji packages require an ending colon as well.
`:smile:`

**Comment by smeech** [comment]
> I think the emoji packages require an ending colon as well. `:smile:`

That's not the case now (https://github.com/espanso/hub/blob/main/packages/basic-emojis/0.1.0/package.yml).

I'm unable to reproduce the problem here, which might relate to my different OS (Linux), or the new release. Is it still a problem?
