### ISSUE TITLE
Expansion is not correct - mainly colons and slashes

### ISSUE THREAD

**Issue by patrykpalej** [espanso/espanso#1328]
When patterns trigger, the expansion is not always correct. For example:
`:inan` -> `:import numpy as np`
although the colon in the beginning is not present in my expansion.

Another example:
`<my pattern>` -> `/pa/th/to/myf/ile` instead of `/path/to/my/file`

Sometimes this problem doesn't occur, it's like 50-50.

### How to reproduce and expected behavior
Here is a fragment of one of my config yaml files:
```
# Automatically generated by espanso migration tool
# Original file: user/python.yml

matches:
  - trigger: ":inan"
    replace: import numpy as np
  - trigger: ":ipap"
    replace: import pandas as pd
```
The expansion should be as declared.

### Environment
Ubuntu 20.04 X11
espanso 2.1.5-beta (I had 2.1.6 but downgraded to give it a try) installed using .deb
https://espanso.org/docs/install/linux/#deb-x11

### Logs
`espanso log`

```
10:22:11 [daemon(148521)] [INFO] reading configs from: "/home/addepto/.config/espanso"
10:22:11 [daemon(148521)] [INFO] reading packages from: "/home/addepto/.config/espanso/match/packages"
10:22:11 [daemon(148521)] [INFO] using runtime dir: "/home/addepto/.cache/espanso"
10:22:11 [daemon(148521)] [INFO] watching for changes in path: "/home/addepto/.config/espanso"
10:22:11 [daemon(148521)] [INFO] espanso version: 2.1.5-beta
10:22:11 [daemon(148521)] [INFO] spawning the worker process...
10:22:11 [daemon(148521)] [INFO] binded to IPC unix socket: /home/addepto/.cache/espanso/espansodaemonv2.sock
10:22:11 [worker(148529)] [INFO] reading configs from: "/home/addepto/.config/espanso"
10:22:11 [worker(148529)] [INFO] reading packages from: "/home/addepto/.config/espanso/match/packages"
10:22:11 [worker(148529)] [INFO] using runtime dir: "/home/addepto/.cache/espanso"
10:22:11 [worker(148529)] [INFO] binded to IPC unix socket: /home/addepto/.cache/espanso/espansoworkerv2.sock
10:22:11 [worker(148529)] [INFO] using X11AppInfoProvider
10:22:11 [worker(148529)] [INFO] monitoring the status of the daemon process
10:22:11 [worker(148529)] [INFO] using X11Source
10:22:11 [worker(148529)] [INFO] using X11Injector
10:22:12 [worker(148529)] [INFO] using X11Clipboard
```

**Comment by smeech** [comment]
I'm trying to address, mop up, and prioritise the old Issues here.
Unless this is still a problem, I'll close this one - I'll happily reopen it if necessary.
Many of these problems can be resolved via [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) for individual triggers (leading to changes in the `backend:` globally or in app-specific configurations), and occasionally with other [options](https://espanso.org/docs/configuration/options/). 
Have you tried those?
