### ISSUE TITLE
Clarify "Found duplicate 'name'" error

### ISSUE THREAD

**Issue by katrinleinweber** [espanso/espanso#1337]
**Describe the bug**

See https://github.com/espanso/espanso/pull/1333

**To Reproduce**

I didn't manage to reproduce it after submitting the above PR, but I believe a) below is relevant in any case.

**Expected behavior**

a) A clearer error message, stating what exactly `Found duplicate 'name'` means in [espanso-config/src/legacy/config.rs](https://github.com/espanso/espanso/blame/930bf807b5802218adff3d0a73e339233182e6dc/espanso-config/src/legacy/config.rs#L769-L780). A filename? A YAML key or value? This would help users figure out what they need to adjust in their config or packages.

b) Or: Correct handling the new package format in compatibility mode. Adding code for this may help prevent further issues like this during the transition.

**Screenshots**

> Found duplicate 'name' in '~/Library/Preferences/espanso/match/packages/…unrelated…/_manifest.yml', please use different names

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

**Setup information**
- OS: macOS 10.15
- Version: 2.1.6-beta

**Comment by smeech** [comment]
I'm trying to address, mop up, and prioritise the old Issues here.
This one seems to relate to migration from the legacy version, which most people will have done after all this time. I agree it's unhelpful.
Unless this is still a problem, may I close this one? - I'll happily reopen it if necessary.
