### ISSUE TITLE
Issue with `word: true` after clearing the terminal

### ISSUE THREAD

**Issue by ByScripts** [espanso/espanso#1357]
**Describe the bug**

On macOS Terminal, or iTerm2 (not tested on Windows/Linux), when using the `word: true` option, there is a problem when typing the shorthand just after clearing the terminal.

When using the `CTRL + L` shortcut, it seems an invisible character is inserted at the beginning. So when typing the trigger, nothing happens.

When using `clear` command, then typing the trigger, it will be replaced. But then, if pressing backspace, a new line is inserted.

**To Reproduce**

Using `CTRL + L`:
1. Define a shorthand (ie: `trigger: foo`, `replace: bar`, `word: true`)
2. Open a terminal
3. Clear the screen with `CTRL + L`
4. Type the shorthand `foo`
5. It will not be replaced
6. Hit backspace exactly 3 times, type `foo`, still not replaced
7. Hit backspace 4 times, type `foo`, it will be replaced.

Using `clear` command:
1. Define a shorthand (ie: `trigger: foo`, `replace: bar`, `word: true`)
2. Open a terminal (tested with iTerm2 and macOS Terminal)
3. Clear the screen `clear` command
4. Type the shorthand `foo`
5. It will be replaced
6. Hit backspace, a new line is sent.

**Expected behavior**

The trigger should be replaced correctly in any case. And a new line should not be send when pressing backspace.

**Screenshots**

![Capture 2022-08-30 at 11 56 35](https://user-images.githubusercontent.com/19408/187408411-74d29d28-ec5d-40cf-a0bc-20052e38973b.gif)

**Logs**

Nothing in log

**Setup information**
- OS: macOS
- Version: 2.1.6-beta

**Comment by smeech** [comment]
I've confirmed the behaviour here (Linux, xfce4-terminal).
 \<ctrl-L> isn't a shortcut for `clear` or `clear -x` but a Form-Feed control character, which leaves the FF character still present, which, like many others, isn't recognised by Espanso as the character before a word.
If you want to resolve this, add a FF character ("\u000c") to the list of `word_separators:` in your default.yml [options](https://espanso.org/docs/configuration/options/).
I'll correct the text in the docs, but the format of the sequence needed is `[" ", ",", ".", "?", "!", "\r", "\n", "\t", "'", "\"", "\x0c"]`, for example.

**Comment by smeech** [comment]
We're updating the code and the documentation to include this (and a few other separators).
Thank you for bringing this to our attention.
