### ISSUE TITLE
I thought I deleted espanso but no, and it's making my logfiles huge

### ISSUE THREAD

**Issue by physicophilic** [espanso/espanso#1371]
**Describe the bug**

I had removed the software, but its somewhere persisting, and making syslog files huge.

The file is filled with entries like
```
Sep  9 11:48:04 Force systemd[19668]: espanso.service: Scheduled restart job, restart counter is at 587.
Sep  9 11:48:04 Force systemd[19668]: Stopped espanso daemon.
Sep  9 11:48:04 Force systemd[19668]: Started espanso daemon.
Sep  9 11:48:04 Force systemd[102833]: espanso.service: Failed to execute command: No such file or directory
Sep  9 11:48:04 Force systemd[102833]: espanso.service: Failed at step EXEC spawning /usr/bin/espanso: No such file or directory
Sep  9 11:48:04 Force systemd[19668]: espanso.service: Main process exited, code=exited, status=203/EXEC
Sep  9 11:48:04 Force systemd[19668]: espanso.service: Failed with result 'exit-code'.
Sep  9 11:48:07 Force systemd[19668]: espanso.service: Scheduled restart job, restart counter is at 588.
Sep  9 11:48:07 Force systemd[19668]: Stopped espanso daemon.
Sep  9 11:48:07 Force systemd[19668]: Started espanso daemon.
Sep  9 11:48:07 Force systemd[102950]: espanso.service: Failed to execute command: No such file or directory
Sep  9 11:48:07 Force systemd[102950]: espanso.service: Failed at step EXEC spawning /usr/bin/espanso: No such file or directory
Sep  9 11:48:07 Force systemd[19668]: espanso.service: Main process exited, code=exited, status=203/EXEC
Sep  9 11:48:07 Force systemd[19668]: espanso.service: Failed with result 'exit-code'.
```

**To Reproduce**
I'm sorry, I've not used this software for more than an year. I don't remember how I reached here. 

**Expected behavior**
I want to remove espanso.

**Logs**
There's no espanso in PATH; searching for it in `/` returns many entries in `proc` and one in `var/snapd`

**Setup information**
- OS: Ubuntu 22.04

**Comment by mikeoertli** [comment]
This is a complete shot in the dark, but prior to uninstalling, did you unregister the service with `espanso service unregister`? I wonder if that would resolve the issue that appears to be a service trying repeatedly to start/run but failing because the actual application is no longer present.

**Comment by physicophilic** [comment]
I might not have. Should I reinstall, unregister, and then uninstall?

**Comment by federico-terzi** [comment]
@physicophilic I'm sorry you experienced this problem! Please try running `systemctl --user disable espanso` and see if that helps :)

**Comment by physicophilic** [comment]
It worked. Thanks! :)
