### ISSUE TITLE
Please don't trim trailing whitespaces

### ISSUE THREAD

**Issue by rsuzuki0** [espanso/espanso#1380]
**Describe the bug**
When the match's replace text contains a line that ends with whitespaces,  older versions of espanso left them intact when pasting the text, but at some point of 0.7.x they get stripped.

Please reverse this, or at least make it configurable.

When the replace text is a blank form that gets manually filled in, and when some of the lines are like:

Item 1:_
Item 2:_

(where _ is actually a space made visible for this example)

I used to be able to just move the cursor at the end of those lines and fill in the rest, but I now have to hit a space before adding the stuff since the space is stripped.

**Comment by jpaulickcz** [comment]
Maybe a feasible workaround for the meantime (haven't tried it) would be using the [cursor hint](https://espanso.org/docs/matches/basics/#cursor-hints)?

I.e. the instead of:
```bash
# Reason
  - trigger: ":reason"
    replace: "Reason the issue was declined: "
```

use

```bash
# Reason
  - trigger: ":reason"
    replace: "Reason the issue was declined: $|$"
```

**Comment by rsuzuki0** [comment]
Many of my use cases where this issue arises is multi-line text that begins with
|    replace: |
and there are multiple lines where I want whitespaces at the end.

**Comment by dharrison27** [comment]
> replace: |

Ok so does the cursor hint not work for matches with multiple lines?

`replace: |
              Reason the issue was declined: $|$
              Signed, Dr. Hyde`

**Comment by rsuzuki0** [comment]
Did you notice this in my previous comment?

> there are multiple lines where I want whitespaces at the end.

**Comment by smeech** [comment]
This doesn't appear to be an issue with the current release, so I will close this. Let me know if this isn't correct.
