### ISSUE TITLE
Bug: `extra_exclude` and `extra_include` do not work reliably

### ISSUE THREAD

**Issue by chrisgrieser** [espanso/espanso#1381]
**Describe the bug**
`extra_exclude` and `extra_include` seem to be very unreliable. For some files they work, for other files they do not. Whether using `filter_class`, `filter_exec`, or `filter_title` does not seem to matter. Restarting or reinstalling Espanso also does not seem to matter.

What's weird to me is that I have a bunch of files with include/exclude rules, and *some* of them work, others don't, and even after a lot of experimenting, when it will work and when it will not.

**To Reproduce**
this one does not correctly include
```yml
filter_class: Mimestream

extra_include:
  - "../match/_email.yml"
```

```yml
filter_exec: Obsidian

extra_exclude:
  - "../match/spelling.yml"
```

```
title: 'New Message'
exec: '/Applications/Mimestream.app'
class: 'com.mimestream.Mimestream'

title: 'Lorem Ipsum - Main Vault - Obsidian v0.16.3'
exec: '/Applications/Obsidian.app'
class: 'md.obsidian'
```

**Expected behavior**
`extra_exclude` and `extra_include` should work correctly

**Logs**
I have a lot of warnings of this sort in the logs, don't know if they are related.
```
 12:20:17 [worker(78820)] [WARN] detected inconsistent modifier state for keys [(Meta, 55), (Shift, 56)], sending compensating events...
12:22:27 [worker(78820)] [WARN] detected inconsistent modifier state for keys [(Alt, 58)], sending compensating events...
12:30:49 [worker(78820)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
...
```

**Setup information**
- OS: macOS 12.5.1
- Version: espanso 2.1.6-beta

**Comment by federico-terzi** [comment]
Hey @chrisgrieser,

I'm sorry you experienced this problem! Could you please try going into Obsidian/Mimestream/etc and type `#acfg#`? At the bottom of the window that opens, there are the "match paths", which are the configs espanso is loading for the current application.
If you could post them here, that would be very helpful! 

Cheers :)

**Comment by chrisgrieser** [comment]
Hi,

thanks for the quick response! here is the respective section for Mimestream:
```log
match_paths: [
    "/Users/chrisgrieser/dotfiles/espanso/match/jxa.yml",
    "/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Dotfolder/private dotfiles/espanso-private.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/cheatsheet.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/markdown.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/capitalization.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/spelling.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/base.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/alfred.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/lorem-ipsum.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/emojis-and-ascii.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/temp.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/mac-symbols.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/css.yml",
    "/Users/chrisgrieser/dotfiles/espanso/match/snippets.yml",
]
```

`_email.yml` is not included there. Similarly, for Obsidian in the other example, `spelling.yml` does not seem to be excluded. (`espanso-private.yml` is actually a symlinked file, if that's relevant)

I tried restarting Espanso, and the result is the same. Also, in case it's relevant, I noticed that espanso actually has multiple processes running?
<img width="1009" alt="Pasted image 2022-09-18 20 57 34" src="https://user-images.githubusercontent.com/73286100/190924018-bd25bcd1-82a6-4fd7-80c1-6923b6f46387.png">

**Comment by chrisgrieser** [comment]
Another thing I noticed is that `espanso restart` does not seem to work – espanso quits, but does not successfully starts again, showing the error message:
```zsh
unable to start service: launchctl exited with non-zero code `exit status: 3`
```

**Comment by smeech** [comment]
Is this still an issue with the current release, or can we close it?

**Comment by chrisgrieser** [comment]
Currently does not occur anymore

**Comment by smeech** [comment]
> extra_include:

It's possible the problem was the lack of an "s" on the ends of the keys - they should have been `extra_includes:` and `extra_excludes:`.
