### ISSUE TITLE
espanso constantly recreates espanso\default.yml and runs in compatibility mode on Win 11

### ISSUE THREAD

**Issue by jonmseaman** [espanso/espanso#1384]
**Describe the bug**
When using espanso on Windows 11, I use a symbolic link to sync my espanso config.

**To Reproduce**
1. Create symbolic link from `C:\Users\jonms\AppData\Roaming\espanso` to `C:\Users\jonms\Workspace\.config\espanso`
    `New-Item -Type SymbolicLink -Path C:\Users\jonms\AppData\Roaming\espanso -Target ~\Workspace\.config\espanso`
    or mklink /J  C:\Users\jonms\AppData\Roaming\espanso C:\Users\jonms\Workspace\.config\espanso
3. Use config to do substitutions.
4. After a few minutes, espanso will create a default.yml file at `C:\Users\jonms\AppData\Roaming\espanso\default.yml` and start using 
that instead.

This does not reproduce when not using a symbolic link.

**Expected behavior**
Espanso continues using the new config files.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
```
21:15:26 [worker(4472)] [INFO] reading configs from: "C:\\Users\\jonms\\AppData\\Roaming\\espanso"
21:15:26 [worker(4472)] [INFO] reading packages from: "C:\\Users\\jonms\\AppData\\Local\\espanso\\packages"
21:15:26 [worker(4472)] [INFO] using runtime dir: "C:\\Users\\jonms\\AppData\\Local\\espanso"
21:15:26 [worker(4472)] [INFO] system info: Windows v10 (22000) - kernel: 22000
21:15:26 [worker(4472)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
21:15:26 [worker(4472)] [INFO] using Win32AppInfoProvider
21:15:26 [worker(4472)] [INFO] monitoring the status of the daemon process
21:15:26 [worker(4472)] [INFO] using Win32Source
21:15:26 [worker(4472)] [INFO] using Win32Injector
21:15:26 [worker(4472)] [INFO] using Win32Clipboard
```

**Setup information**
- OS: Windows 11
- Version: espanso 2.1.7-beta

**Comment by federico-terzi** [comment]
Hey @jonmseaman,

Thanks for reporting this issue! Could you please post how the `~\Workspace\.config\espanso` directory structure looks like?

Cheers :)

**Comment by jonmseaman** [comment]
Here is the directory structure.

- 📁`~/Workspace/.config/espanso`
  - 📁`config/`
    - 📄`default.yml`
  - 📁`match/`
    - 📄`base.yml`
  - 📄`README.md` - File I created with commands to install the symbolic link.
  - 📄`default.yml` - file created a few minutes after starting espanso

**Comment by jonmseaman** [comment]
One Workaround to this is to not use a symbolic link. I sync my config with a git repo, so I was able to clone to `C:\Users\jonms\AppData\Roaming\espanso` instead of in my home directory.

**Comment by smeech** [comment]
Is this still an issue with the current release, or can we close it?

**Comment by jonmseaman** [comment]
It isn't affecting me anymore. It seems like espanso just didn't like the symbolic link, but works otherwise.
