### ISSUE TITLE
Default search_trigger (jkj) isn't documented, and disabling it (with "off") doesn't work

### ISSUE THREAD

**Issue by jpetazzo** [espanso/espanso#1389]
**Describe the bug**

When typing "jkj", the search box shows up. 

(Story time: it took me months to realize that it was Espanso's search box, because somehow, it only happened while I was screensharing in video calls or live streams, and my Espanso completions contain some personal data; so when it happened I just made it disappear as fast as possible. Eventually I watched a recording to see what that popup box was, and I realized it was Espanso! I didn't know about this search feature so it took me a while to know what to look for in the docs.)

I tried to disable it by putting `search_trigger: off` in my configuration, as indicated in the [docs](https://espanso.org/docs/configuration/options/#customizing-the-search-trigger) but now when I type "off" it shows the search bar 😅

**To Reproduce**

1. Put `search_trigger: off` in configuration
2. Restart espanso
3. Type `off`

**Expected behavior**

Search bar doesn't show up when turned off

**Setup information**

- OS: ArchLinux
- Version: espanso 2.1.7-beta

**Additional notes**

I don't know if many people are using the default binding `jkj`.
_Personally_ I think it's confusing; perhaps it should be off, or set to something that people don't type accidentally (it's very easy to type jkj since these keys are often used for navigation in `vi` and other editors with similar bindings). 
But I don't want to break other people's existing workflows!

**Comment by jpetazzo** [comment]
The `off` issue seems to be a duplicate of #1046.

So we're left with the documentation part (and the question of whether the default is a good choice or not, but I don't know about that! 😅)

**Comment by jpetazzo** [comment]
... OK, after completing the ugprade+migration of my Espanso configuration, it looks like `jkj` doesn't trigger the search bar anymore. Perhaps this only happens when using a "legacy" configuration file?

I'll let you judge if this can be closed or if it should be investigated/debugged further.

Thank you!

**Comment by smeech** [comment]
The `search_trigger: off` triggering Issue has been resolved in the current release, and it's now the default.
I'll close this Issue, if that's OK.
