### ISSUE TITLE
[ BUG ] Espanso won't start if the config file is on an unmounted drive

### ISSUE THREAD

**Issue by ibehnam** [espanso/espanso#1395]
I'm on macOS and have my config file on Google Drive. When GDrive is not running, Espanso won't start at all. It's understandable but maybe a better error message would let the user know that the cloud drive isn't mounted. 

Also, since it takes some time for GDrive to load after each reboot, Espanso won't start automatically at login.

**Comment by joh6nn** [comment]
My take on this is that adding the ability to detect the drive not being mounted is a lot of additional complexity for a very specific corner case. I think maybe the simplest thing here would be to replace the auto-start entry for espanso with one that runs an AppleScript (or similar) that waits until the drive has been mounted, and then launches espanso

**Comment by smeech** [comment]
I agree a better error message would be appropriate but I think @joh6nn's suggestion is a good one.
I'll close this for now but would be happy to reopen it if you think appropriate.
