### ISSUE TITLE
2.1.7-beta can not be started on MacOS 12.5, and always asks for Accessibility permission.

### ISSUE THREAD

**Issue by fightyz** [espanso/espanso#1397]
**Describe the bug**
I have upgraded espanso from 2.1.6 to 2.1.7-beta through Homebrew. After successfully installed, I open the espanso.app. It asks Accessibility permissions:
![image](https://user-images.githubusercontent.com/1697504/193971994-5578cd26-a084-4b94-84af-7b129de0fd82.png)
I re-grant the permissions:
![image](https://user-images.githubusercontent.com/1697504/193976357-a87784ed-6670-4b14-a044-b892c397932e.png)

but espanso.app is not launched yet.

Everytime I open espanso.app, it always asks for Accessibility permissions just like above. No matter how many times I grant, espanso won't start.

I have tried to re-install espanso, the bug is still there.

**To Reproduce**
just like above.

**Expected behavior**
espanso.app can launch successfully.

**Screenshots**
![espanso bug](https://user-images.githubusercontent.com/1697504/193975636-402f667b-4427-432e-8f29-ddf77528bdb5.gif)

**Logs**
$ espanso --version
espanso 2.1.7-beta

$ espanso log
09:20:39 [daemon(1525)] [INFO] reading configs from: "/Users/djimacos/Library/Application Support/espanso"
09:20:39 [daemon(1525)] [INFO] reading packages from: "/Users/djimacos/Library/Application Support/espanso/match/packages"
09:20:39 [daemon(1525)] [INFO] using runtime dir: "/Users/djimacos/Library/Caches/espanso"
09:20:39 [daemon(1525)] [INFO] system info: Darwin v12.5 - kernel: 21.6.0
09:20:39 [daemon(1525)] [INFO] watching for changes in path: "/Users/djimacos/Library/Application Support/espanso"
09:20:39 [daemon(1525)] [INFO] espanso version: 2.1.6-beta
09:20:39 [daemon(1525)] [INFO] spawning the worker process...
09:20:39 [daemon(1525)] [INFO] binded to IPC unix socket: /Users/djimacos/Library/Caches/espanso/espansodaemonv2.sock
09:20:39 [worker(1552)] [INFO] reading configs from: "/Users/djimacos/Library/Application Support/espanso"
09:20:39 [worker(1552)] [INFO] reading packages from: "/Users/djimacos/Library/Application Support/espanso/match/packages"
09:20:39 [worker(1552)] [INFO] using runtime dir: "/Users/djimacos/Library/Caches/espanso"
09:20:39 [worker(1552)] [INFO] system info: Darwin v12.5 - kernel: 21.6.0
09:20:39 [worker(1552)] [INFO] using CocoaAppInfoProvider
09:20:39 [worker(1552)] [INFO] binded to IPC unix socket: /Users/djimacos/Library/Caches/espanso/espansoworkerv2.sock
09:20:40 [worker(1552)] [INFO] using CocoaSource
09:20:40 [worker(1552)] [INFO] monitoring the status of the daemon process
09:20:40 [worker(1552)] [INFO] monitoring the status of secure input
09:20:40 [worker(1552)] [INFO] using MacInjector
09:20:40 [worker(1552)] [INFO] using CocoaClipboard
09:24:00 [worker(1552)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'SecurityAgent', but there are cases in which the detection is unreliable. Full path: /System/Library/Frameworks/Security.framework/Versions/A/MachServices/SecurityAgent.bundle/Contents/MacOS/SecurityAgent
09:24:02 [worker(1552)] [INFO] secure input has been disabled
10:11:33 [worker(1552)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
10:11:43 [worker(1552)] [INFO] secure input has been disabled

> I have noticed that it's version is 2.1.6-beta in the log, but 2.1.7-beta in the output of `espanso --version`. I think it's because that I have never started 2.1.7-beta successfully, so the log is 2.1.6-beta's.

**Setup information**
- OS: MacOS 12.5
- Version: 2.1.7-beta

**Comment by fightyz** [comment]
Here is info from brew:
```shell
$ brew reinstall espanso
==> Caveats
espanso is not signed and requires Accessibility access,
so you will need to re-grant Accessibility access every time the app is updated.

Enable or re-enable it in:
  System Preferences → Security & Privacy → Privacy → Accessibility
To re-enable, untick and retick espanso.app.

==> Downloading https://github.com/espanso/espanso/releases/download/v2.1.7-beta/Espanso-Mac-Intel.zip
Already downloaded: /Users/djimacos/Library/Caches/Homebrew/downloads/b767b03e11da8b7886652a888705f3166add620e465dc9e065a9948d95f185d9--Espanso-Mac-Intel.zip
==> Uninstalling Cask espanso
==> Backing App 'Espanso.app' up to '/usr/local/Caskroom/espanso/2.1.7-beta/Espanso.app'
==> Removing App '/Applications/Espanso.app'
==> Unlinking Binary '/usr/local/bin/espanso'
==> Purging files for version 2.1.7-beta of Cask espanso
==> Installing Cask espanso
==> Moving App 'Espanso.app' to '/Applications/Espanso.app'
==> Linking Binary 'espanso' to '/usr/local/bin/espanso'
🍺  espanso was successfully installed!
```

**Comment by federico-terzi** [comment]
Hey @fightyz,

I'm sorry you experienced this problem! Please try removing the Espanso entry from the accessibility entirely (with the minus button). Then restart Espanso and re-enable it, usually this helps

Cheers :)
