### ISSUE TITLE
Fuzzy Search trigger's 

### ISSUE THREAD

**Issue by sl5net** [espanso/espanso#1403]
Fuzzy Search trigger's 

1. something (maybe `:searchTriggers`) to start a fuzzy search over all (or some) triggers
and us it in the beautiful search-bar  💓 (not Fuzzy at the moment) https://espanso.org/docs/configuration/options/#customizing-the-search-bar
2. run the trigger

inspiration:
https://youtu.be/elLsl8lj0K8?t=126
https://www.youtube.com/watch?v=LCVe4l1Cs2o&t=2139s
https://stackoverflow.com/questions/53345266/generate-search-words-from-text-with-camelcase-by-using-regex

**Comment by smeech** [comment]
I think the current release's implementation is better, so I'll close this issue, but am happy to reopen it if necessary.
