### ISSUE TITLE
Allow Users to Configure the Conditions Needed for Matches with "word: true" to expand.

### ISSUE THREAD

**Issue by CillySu** [espanso/espanso#1411]
First of all, I am not an experienced github user, nor am I a dev — so I apologise in advance if this is the wrong location to post this, or if I'm breaking 100s of conventions in the below: 

I use `word: true` for a large number of my triggers, I find it much more beneficial as it allows me to have multiple expansions with the same starting characters.

With `word: true` enabled I am able to use "v" → vein and "vu" → venule, for example. This obviously would require a prepending in the absence of word: true such as ":v".

As of right now, the only way to expand `word: true` is if our trigger is **both** _prepended_ **and** _appended_ by `<SPC>`,  this presents a number of issues:

1. Expansions will not expand if they are the first character in a line, as they are not prepended by a whitespace. This is problematic when using **bulleted or numbered lists**, or when not writing in long-form paragraphs, as beginning on a new line is rather common. When writing in **bulleted or numbered lists**, text editors will often not initiate a new list item if `<RETURN ↵>` is sent to a line ending in whitespace, instead the user is kicked out of the bullet/numbered list. The workaround is that the user has to press `<SPC>` to expand the trigger, then press `<SPC>` again (because if they try do press `< DEL ⌫ >` the expansion will contract back to the trigger) and then press `< DEL ⌫ >` twice to undo their two whitespaces, then finally press `<RETURN ↵>` to add a new line to their bulleted list. This is my no. 1 issue with writing with `word: true`
2. Sometimes I wish for a trigger to expand if appended by `<SPC>` but irrespective of the preceding content (or the reverse, where there is a space before but I don't care about what comes after)

For example:
```
- trigger: "dyn"
   replace: "dynamics"
```
where the intended use is for the user to type `"pharmacodyn<SPC>" → "pharmacodynamics"`, but to **NOT** have espanso expand when typing "dynamo", for example.

3. Triggers will not expand if they are followed by certain characters which should probably be expected as default intended behaviour, such as colon, semicolon, closing brackets, `<TAB⇥>`.
4. It does not facilitate the expansion of a trigger into a shortened form of the expansion (think of trigger "pco" → "pharmaco ") with the intention of the user typing "pco`<SPC>`dynamics" to achieve "pharmacodynamics" or "pco`<SPC>`kinetics" to achieve "pharmacokinetics" — this is not possible in `word: true` current behaviour because the expansion appends the space automatically.

I understand that no. 4 can be remedied by using:
```
- trigger: "pco"
   replace: "pharmaco$|$"
   word: true
```

and this works quite well. But I have a solution i propose to be of better utility.

My suggestion is, a **master config** for `word: true` behaviour in the user's config file as well as the ability for packages to override this behaviour (if permitted by the user) in the package.yml.

**I would suggest having the ability to have a key or set of keys** (I would likely use `<TAB ⇥>`) **which allows me to expand the trigger without espanso injecting the whitespace after the expansion** (e.g — "pharmaco_" where _ is the space).

Examples:
```
#In default.yml or package.yml
word_boundaries: [TAB, ENTER, SPACE, SHIFT, "}", "]", ">", "\"", "/", "-"]
word_defaults: [true, pre, post, append]
# true = triggers obey word:true by default unless explicitly stated otherwise
# pre = requires leading whitespace for expansion of trigger
# post = requires trailing whitespace for expansion of trigger
# append = whitespace is injected after expansion

#In default.yml
word_override: true
# allows the user to permit packages to override their defaults for the package's expansions
```

```
# In base.yml
matches:
   - trigger: "trigger"
     replace: "expansion"
     word: [true, pre, post, append]
     # Permit the overriding of package and user defaults if word_override is true in default.yml
```

I personally would have `word: true` expand with closing parentheses ` } ` ` / ` ` ] ` ` > ` ` )` and quotation marks but ideally for power-users this should be user-definable.

It is possible that some of this proposed behaviour strays beyond what `word: true` was intended to do, in this case I believe a new config option should be permitted.

**Comment by CillySu** [comment]
I have since found the `word_separators` option, my apologies.

I have since set the following.
`word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\r\n", "\t", "}", "]", ">", "%", ")", 22]`
in my `defaults.yml` 

This allows the use of `TAB ⇥` for expanding, however this still results in the erroneous addition of two whitespace after pressing `TAB ⇥` unless $|$ is present at the end of the `replace: ` field.

I believe it would be helpful if `word_separators` would/could be divided into separators for _before_ and _after_ the trigger.

I have since added $|$ to almost all my `replace: ` fields.

**Comment by Gremious** [comment]
> PS: What does 22 mean in the word_separators: ?

Got curious so I checked. In code it seems to be `22u8 as char`:

https://github.com/espanso/espanso/blob/3f6444c8b5c0004287b9deb6b6a1aa414b1a36e4/espanso-config/src/legacy/config.rs#L73-L75

So - raw ASCII codes in case you want an invisible space seperator or something weird like that ig

**Comment by smeech** [comment]
Thank you.
Most of your issues are addressed by adjusting the list of `word_separators:`, as you suggest, and we're in the process of updating the code and documentation to add ", ', \t, and form-feed as defaults. The newline issue is not a problem with the current release.
Regarding item 4, most of us would use a prefix or suffix character or other workaround.
Thank you very much for your suggestion to include closing parentheses - I've added a comment to the pending pull request. 
I'll close this for now, if that's OK.
