### ISSUE TITLE
Failure to introduce colons (:) on output variable

### ISSUE THREAD

**Issue by ggonzalez-vintra** [espanso/espanso#1422]
**Describe the bug**
When an output variable to be printed on the replacement contains the characted `:` (colons), they are removed from the string.

**To Reproduce**
1. add onto yaml:

```
- regex: ":url\\((?P<input>.*)\\)"
replace: "{{input}} -> {{output_url}}"
vars:
- name: output_url
type: shell
params:
cmd: "curl -s --request GET 'https://api.publicapis.org/random'  | jq -r '.entries[0].Link'"
```

2. type somewhere outside of a terminal `url(Some url)` 

**Expected behavior**
Replacement is performed, showing `Some url -> https://xyz.com`

**Actual behavior**
Replacement is performed, but the url outputted does not have the colons: `Some url -> https//xyz.com`

**Screenshots**
![Peek 2022-10-27 12-23](https://user-images.githubusercontent.com/80257958/198260218-068188c5-8855-4491-b436-f92245b9481f.gif)

**Logs**
No logs on `espanso logs` relevant on this case

**Setup information**
- OS: Ubuntu 18.04
- Version: espanso 2.1.6-beta

**Comment by denishem** [comment]
I'm having the same issue, but with Firefox. My keyboard layout is french, if that's relevant.
```yaml
 - trigger: ":url"
    replace: "https://some-url.com/{{paste}}"
    vars:
      - name: paste
        type: clipboard
```
With `http://foo.bar` in the clipboard
Produces: `http//some-url.com/http//foo.bar`

Things I tried that didn't work:
- `backend: Clipboard`
- `backspace_delay`
- `pre_paste_delay`
- `x11_use_xclip_backend: true`
- `fast_inject: false`
- `undo_backspace: false`

**Setup**
OS: Arch Linux
Version: espanso 2.1.8

**Comment by smeech** [comment]
It's been a while, and I wasn't able to reproduce the problem here (Linux Mint Xfce). Is this still a problem with the current release?
You can now test triggers using [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) for individual triggers (leading to changes in the `backend:` globally or in app-specific configurations), and occasionally with other [options](https://espanso.org/docs/configuration/options/).

**Comment by dshemnv** [comment]
No more issues on my side. I have `backend: Clipboard` enabled globally.

**Comment by smeech** [comment]
This is now an old issue, so I'll close it for now. Happy to reopen if @ggonzalez-vintra or others are still having problems we can't resolve.

**Comment by diegoisanzo** [comment]
I am experiencing a similar problem with Linux Mint Cinnamon 22.3 (X11), this one does not add nor the colon neither the plus sign, only the 1.

```
   - trigger: "ñy"
     replace: ":+1"
```
