### ISSUE TITLE
Literal Block Problem

### ISSUE THREAD

**Issue by liberninja** [espanso/espanso#1425]
I'm noticing that when I use the literal block feature it automatically hits enter after the expansion. Is there a way to prevent this?
For example, this will print the two lines then do a carriage return rather than leaving the cursor at the end of the 2nd line.

```
  - trigger: ":test"
    replace: |
              first line
              second line
```

**Comment by smeech** [comment]
Sorry it's been so long since your posting.
As you've probably discovered by now, you can suppress the trailing newline with `|-` above the expansion text. See https://yaml-multiline.info/.

**Comment by liberninja** [comment]
> Sorry it's been so long since your posting. As you've probably discovered by now, you can suppress the trailing newline with `|-` above the expansion text. See https://yaml-multiline.info/.

Fantastic, thank you!
