### ISSUE TITLE
Espanso does not work on MacOS Ventura.

### ISSUE THREAD

**Issue by cocoonkid** [espanso/espanso#1430]
**Describe the bug**

Installed Espanso, added correct accessibility permissions 
Wizard appeared, ran wizard and test worked.
Since I have option + space already in use I manually clicked the tray icon "Launch Bar" option.
Then it does nothing, tray icon is still there but the context menu does't work anymore either.

I noticed 3 processes running in the activity monitor and killed them. 
Restarting espanso now doesn't even spawn these processes anymore.

The whole thing only starts again after rebooting.

I tried already removing the accessibility permissions and adding them again and also removing Espanso completely from the permissions and readding it.

I added `search_shortcut: CMD+ALT+SPACE` to the configuration base.yml but that did not fix it.

As soon as I click "open search bar" it crashes. Only the tray icon is still left without functions.

While this happens there are no new log entries.

❯ espanso start
`unable to start service: launchctl exited with non-zero code `exit status: 3``

**Logs**
❯ espanso log
```
08:57:06 [daemon(1651)] [INFO] reading configs from: "/Users/cocoonkid/Library/Application Support/espanso"
08:57:06 [daemon(1651)] [INFO] reading packages from: "/Users/cocoonkid/Library/Application Support/espanso/match/packages"
08:57:06 [daemon(1651)] [INFO] using runtime dir: "/Users/cocoonkid/Library/Caches/espanso"
08:57:06 [daemon(1651)] [INFO] system info: Darwin v13.0 - kernel: 22.1.0
08:57:06 [daemon(1651)] [INFO] espanso version: 2.1.7-beta
08:57:06 [daemon(1651)] [INFO] spawning the worker process...
08:57:06 [daemon(1651)] [INFO] watching for changes in path: "/Users/cocoonkid/Library/Application Support/espanso"
08:57:06 [daemon(1651)] [INFO] binded to IPC unix socket: /Users/cocoonkid/Library/Caches/espanso/espansodaemonv2.sock
08:57:06 [worker(1652)] [INFO] reading configs from: "/Users/cocoonkid/Library/Application Support/espanso"
08:57:06 [worker(1652)] [INFO] reading packages from: "/Users/cocoonkid/Library/Application Support/espanso/match/packages"
08:57:06 [worker(1652)] [INFO] using runtime dir: "/Users/cocoonkid/Library/Caches/espanso"
08:57:06 [worker(1652)] [INFO] system info: Darwin v13.0 - kernel: 22.1.0
08:57:06 [worker(1652)] [INFO] using CocoaAppInfoProvider
08:57:06 [worker(1652)] [INFO] binded to IPC unix socket: /Users/cocoonkid/Library/Caches/espanso/espansoworkerv2.sock
08:57:06 [worker(1652)] [INFO] using CocoaSource
08:57:06 [worker(1652)] [INFO] monitoring the status of secure input
08:57:06 [worker(1652)] [INFO] monitoring the status of the daemon process
08:57:06 [worker(1652)] [INFO] using MacInjector
08:57:06 [worker(1652)] [INFO] using CocoaClipboard
08:58:18 [worker(1652)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
08:59:54 [daemon(1651)] [ERROR] received unexpected exit code from worker 90, exiting
```

**Setup information**
- OS: MacoOS Ventura
- Version: 2.1.7-beta

Thanks for this tool. It's amazing ayways!

**Comment by federico-terzi** [comment]
Hey :) Please update to the latest version (2.1.8), yesterday we shipped a fix for that :)

**Comment by cocoonkid** [comment]
@federico-terzi  Thanks for the swift reply. The homebrew formula isn't yet up to date that's why i missed the latest version.


Yes it fixed the problem!  Thanks!
