### ISSUE TITLE
Espanso 2.1.7-beta does not work on Windows while using ReNeo (1.5.4)

### ISSUE THREAD

**Issue by mruessler** [espanso/espanso#1432]
Hi there,
since the update to version 2, Espanso has stopped working for me. That means, I cannot trigger replacements anymore. I am using a Windows machine with ReNeo 1.5.4 (https://github.com/Rojetto/ReNeo) and Espanso 2.1.7-beta. My ReNeo layout is neo2 (›neo‹ in ReNeo).
Before the update, Espanso happily worked along Reneo without any problem. Deactivating ReNeo via icon lets me use Espanso shortcuts.
The search shortcut works as well and lets me insert replacements.
My `default.yml`:
```
toggle_key: OFF
undo_backspace: false
search_shortcut: ALT+META+SPACE
```
Logs do not show any particular error:
```
15:33:17 [daemon(4260)] [INFO] configuration change detected, restarting worker process...
15:33:17 [worker(17144)] [INFO] engine eventloop has terminated, propagating exit event...
15:33:17 [worker(17144)] [INFO] waiting for engine exit mode...
15:33:17 [worker(17144)] [INFO] exiting worker process...
15:33:17 [daemon(4260)] [INFO] spawning the worker process...
15:33:17 [worker(3444)] [INFO] reading configs from: "C:\\Users\\M\\AppData\\Roaming\\espanso"
15:33:17 [worker(3444)] [INFO] reading packages from: "C:\\Users\\M\\AppData\\Roaming\\espanso\\match\\packages"
15:33:17 [worker(3444)] [INFO] using runtime dir: "C:\\Users\\M\\AppData\\Local\\espanso"
15:33:17 [worker(3444)] [INFO] system info: Windows v10 (19044) - kernel: 19044
15:33:17 [worker(3444)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
15:33:17 [worker(3444)] [INFO] using Win32AppInfoProvider
15:33:17 [worker(3444)] [INFO] monitoring the status of the daemon process
15:33:17 [worker(3444)] [INFO] using Win32Source
15:33:17 [worker(3444)] [INFO] using Win32Injector
15:33:17 [worker(3444)] [INFO] using Win32Clipboard
```
I found a comment when searching for ReNeo issues: https://github.com/espanso/espanso/issues/680#issuecomment-1118212560
I then created a simple replacement in `base.yml` without any additional layers:
```
matches:
  - trigger: "dd"
    replace: "ee"
```
It does not work.
Since it has work previously, I am assuming that Espanso implements trigger detection differently now.

**Comment by nakami** [comment]
Did the situation change for you? Did you switch to a different text expander? I'm facing the same problem.

**Comment by m-haug** [comment]
I just had the same problem after tinkering with my neo configuration. Whatever the problem actually is, switching to the native keyboard driver (https://www.neo-layout.org/Einrichtung/kbdneo/) partially fixed it. I can use my previous triggers again.

It seems that espanso does not like whatever ReNeo does to achieve its magic.

**Comment by smeech** [comment]
Many of these problems can now be resolved by testing [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) for individual triggers (leading to changes in the `backend:` globally or in app-specific configurations), and occasionally with other [options](https://espanso.org/docs/configuration/options/). 
Have you tried those?
Is this still an issue with the current release, or can we close it?
