### ISSUE TITLE
WSL any input above 103 characters are not pasted

### ISSUE THREAD

**Issue by thorko** [espanso/espanso#1460]
When I run a trigger on a WSL1 ubuntu machine anything more than 103 characters are not pasted into the window. It doesn't matter if  I use the yaml syntax or all in one line.
Anything less than 103 characters is working and pated into the terminal window.
I'm running Windows 10 and WSL1

**Comment by joh6nn** [comment]
can you confirm the following:

- are you able to paste your desired string into WSL1 manually, without espanso ?
- does the following string work as an expansion: "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" ?

**Comment by joh6nn** [comment]
can you confirm the following:

- are you able to paste your desired string into WSL1 manually, without espanso ?
- does the following string work as an expansion: "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" ?

**Comment by thorko** [comment]
Has been a setting in Espanso
clipboard_threshold: 100
Setting it to 800 worked
