### ISSUE TITLE
Espanso fail to start with code 101

### ISSUE THREAD

**Issue by vroger11** [espanso/espanso#1461]
**Describe the bug**
Espanso fail to start with exit code 101. Furthermore, `espanso status` return 101.

**To Reproduce**
1. launch espanso: `espanso start`

**Expected behavior**
It should works

**Logs**
thread 'main' panicked at 'unable to create config directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }', espanso-path/src/lib.rs:48:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Setup information**
- OS: 
  - OS: Manjaro Linux x86_64 
  - Kernel: 6.0.8-1-MANJARO 
  - DE: Plasma 5.26.3 
  - WM: KWin 

- Version: espanso 2.1.8

**Comment by smeech** [comment]
Is this still a problem with the current release? I realise some time has passed since you posted this.

**Comment by cleiter** [comment]
I had the same problem. Turns out I had an empty `~/.config/espanso` file for some reason, but espanso expects it to be a directory. Removing the file solved the problem.

**Comment by smeech** [comment]
Thank you.

As there's been no response from @vroger11 I assume he solved the problem or moved on.

I'l close the Issue.
