### ISSUE TITLE
documentation: multiple includes

### ISSUE THREAD

**Issue by icf20** [espanso/espanso#1479]
from https://espanso.org/docs/configuration/include-and-exclude/
```
filter_exec: "chrome"

extra_includes:
  - "../match/_email.yml"

```

how does the multiple includes work ?

**Comment by nemonein** [comment]
I may be wrong, but this works for me. Tested this on macOS 13.3.
For example, let's say that I want to apply the rules(matches) for two applications, such as Chrome and firefox.

```
filter_exec: '/Applications/Google Chrome.app|/Applications/Firefox.app'

includes: # OR extra_includes
  - "../match/_web-browsers.yml"
 ```

The **KEY** is OR operation.

---
Oh, I think I misunderstood your question.
If you want to INCLUDE several yml files, then also use regex. I haven't tested this, but I think it will work.

```
extra_includes:
  - "../match/_multi-.*.yml"
 ```
Try something like this.

**Comment by federico-terzi** [comment]
Hey :) 

The extra_includes field is a list, so you can also add multiple entries:

```
extra_includes:
  - "../match/_email.yml"
  - "another_entry.yml"
```

**Comment by nemonein** [comment]
Thanks @federico-terzi. It will be great if you include this on the user's documentation.
