### ISSUE TITLE
Problem when autocompleting mentions on GitLab/GitHub

### ISSUE THREAD

**Issue by ddieulivol** [espanso/espanso#1483]
**Context**

GitLab/GitHub allow autocompletion of names when mentioned with `@`, e.g. `@mattn`.

I have setup a match that would allow me to ask for a review to somebody:

```shell
# What I would type
:rr @mattn 

# What it would look like
Hey @mattn, Could you please review this MR? Thanks in advance :slight_smile: 
/assign_reviewer @mattn
```

**Describe the bug**

When the mention is autocompleted by GitHub/GitLab, it somehow doesn't trigger the match I configured. If I type the mention entirely, the match will trigger.

**To Reproduce**

1. Configure this match:

```
  - regex: ":rr (?P<reviewer>@[\_\\w-]+) "
    replace: |
              Hey {{reviewer}}, Could you please review this MR? Thanks in advance :slight_smile: 
              /assign_reviewer {{reviewer}}
```

1. Try to type `:rr @mattn ` without autocompletion in GitHub. The match should trigger.
1. Try to type `:rr @mattn ` with the mention autocompletion in GitHub: the match will NOT trigger.

**Expected behavior**
The autocompletion from websites should be taken as if I typed the text myself.

**Screenshots**

![Screenshot 2022-12-22 at 09 36 08](https://user-images.githubusercontent.com/120561341/209092629-66127e2a-2ec4-456b-9666-88bd4c7ce6ac.png)

**Logs**

```shell
09:36:09 [worker(6158)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
09:36:16 [worker(6158)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
09:36:18 [worker(6158)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
09:36:47 [worker(6158)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
```

**Setup information**
- OS: `MacOS Ventura 13.1`
- Version: `espanso 2.1.8`

**Comment by ddieulivol** [comment]
I now realize there's a more fundamental problem related to copy/pasting...

* If I type entirely `:rr @two `, everything works as expected.
* If I copy/paste the `@two`, it will not work: `:rr @two `
* If I copy/paste the `:rr`, it will not work either!:

@federico-terzi What do you think about this? Are we only listening to "typed keyboard events"?

**Comment by smeech** [comment]
I'm afraid Espanso only listens for keystrokes, and is not aware of pasted text (by whatever means), apart from the keystroke (e.g. \<ctrl-v>) that invokes it.
May I close this issue?

**Comment by ddieulivol** [comment]
> I'm afraid Espanso only listens for keystrokes, and is not aware of pasted text (by whatever means), apart from the keystroke (e.g. <ctrl-v>) that invokes it. May I close this issue?

Sure thing!
