### ISSUE TITLE
Fails to compile X11 version on 32 bit linux

### ISSUE THREAD

**Issue by cheseremtitus24** [espanso/espanso#1502]
**Describe the bug**
Compiling for 32bit linux version = Linux  5.15.0-kali2-686-pae #1 SMP Debian 5.15.5-2kali2 (2021-12-22) i686 GNU/Linux

**To Reproduce**
1. compile on the below platform
Linux  5.15.0-kali2-686-pae #1 SMP Debian 5.15.5-2kali2 (2021-12-22) i686 GNU/Linux
user@kali:~/Downloads/espanso-2.1.8$ cargo make create-app-image --profile release

**Expected behavior**
Compilation should be able to produce an espanso executable that is build for 32bit linux.

**Screenshots**
[d](url)

**Logs**
generates the following error while compiling
```error[E0308]: mismatched types

espanso-inject/src/x11/default/mod.rs:205:15
    |
200 |             Xutf8LookupString(
    |             ----------------- arguments to this function are incorrect
...
205 |               &mut sym,
    |               ^^^^^^^^ expected `u32`, found `u64`
error[E0308]: mismatched types
   --> espanso-inject/src/x11/default/mod.rs:284:15
    |
279 |             Xutf8LookupString(
    |             ----------------- arguments to this function are incorrect
...
284 |               &mut sym,
    |               ^^^^^^^^ expected `u32`, found `u64`
    |
    = note:    expected raw pointer `*mut u32`
            found mutable reference `&mut u64`
note: function defined here
   --> espanso-inject/src/x11/ffi.rs:115:10


```

**Setup information**
- OS: Linux  5.15.0-kali2-686-pae #1 SMP Debian 5.15.5-2kali2 (2021-12-22) i686 GNU/Linux
- Version: espanso-2.1.8

**Comment by AucaCoyan** [comment]
Closing because of age
