### ISSUE TITLE
🚨 Is Espanso Abandonded?

### ISSUE THREAD

**Issue by ibehnam** [espanso/espanso#1506]
There are tens of open issues with literally zero answer from the developers. Does it mean that the project is abandoned?

It would be really sad because this app has been a productivity booster for me (and I'm sure, for thousands of people). But unfortunately, it hasn't been updated to work properly on macOS Ventura. For instance, I opened an issue a few weeks ago about the fact that Espanso doesn't start/restart properly on Ventura. `espanso start` gives this:

```
unable to start service: launchctl exited with non-zero code `exit status: 3`
```

But this hasn't been resolved (and I'm not an expert to know what to look for to solve this issue).

**Comment by federico-terzi** [comment]
Hey @ibehnam,

I'm really sorry I haven't been responsive in the past few months, I've been going through a particularly busy period of my life and had to slow down side projects to avoid burning out :) 

Hopefully, things will improve in the near future, but in the meantime:
1. I'm happy to review bug fixes PR if anyone wants to give it a try
2. I still try to allocate some time for critical bugs

I still have plans and improvements for this project, so I wouldn't define it as abandoned by any means :)

Regarding your problem, I might have missed the issue on GitHub (I still try to read them). I'm on macOS Ventura and it's working well for me, so you might want to reinstall espanso https://github.com/espanso/espanso/issues/1430

Cheers :)

**Comment by ibehnam** [comment]
It's good to hear from you and I hope your work load allows you to keep up the good work on this awesome app as well!  Unfortunately, the issue on my Mac didn't go away by re-installing the app. Something about `espanso stop` and `espanso start` is causing the problem.

**Update**
I realized that when we do `espanso stop`, then `espanso start` won't work anymore. In that case, we must re-open the app and that seems to make Espanso start again. So the issue is definitely in the `espanso start` command.
