### ISSUE TITLE
Dashes "---" are not written to output in a "match" trigger

### ISSUE THREAD

**Issue by 5472qaywsx** [espanso/espanso#1524]
**Describe the bug**
Dashes "---" are not written to output in a "match" trigger

**To Reproduce**
1. set the following "match" directive:
   - trigger: "valeddm"
    replace: |
             ---
             Buona giornata e buon lavoro
             Name Surname
2. The first line "\---" appears as "" (that is, nothing appears as text replacement)
3. also tried with: \---, "---", "\---", same result (dashes never appear, other signs appear)
4. also tried this:
    replace: "---\nBuona giornata e buon lavoro\nName Surname", same result (no dashes)

**Expected behavior**
I would have expected the dashes to appear on screen with other text.

**Setup information**
- OS: Ubuntu 22.04, Linux 5.15.0
- Version: Espanso 2.1.8

**Comment by jwigg-netscout** [comment]
Yaml uses `---` to indicate document structure: https://yaml.org/spec/1.2.2/#22-structures . Because of this, you may need to escape the dashes in order to use them in your match output. Try the following and see if that helps:

`\---`

`\-\-\-`

**Comment by 5472qaywsx** [comment]
Thank you, tried your advice, but without success: dashes never appear in the expanded text.
As dashes are something special in Yaml, I ended up changing the three dashes with three underscores, for my signature expansion. Solved (with a workaround) for me.
