### ISSUE TITLE
Multiline not working with markdown

### ISSUE THREAD

**Issue by ZerkerEOD** [espanso/espanso#1538]
**Describe the bug**
Using the markdown and the multiline char of | does not paste in new line characters.

**To Reproduce**
```
  - trigger: ":testing"
    markdown: |-
      Plaintext Protocol <br /> 
      Plaintext *protocols*
      Testing this  
      with two spaces
      Testing with \ 
      doesn't work
      Testing with \n
      doesn't work
    label: "Testing"
```

![image](https://user-images.githubusercontent.com/26573385/221718550-8574f150-0069-4bee-81b6-b9480dafb493.png)

**Expected behavior**
Be able to have new lines when doing markdown either with multiline or using quotes and standard \n.

**Screenshots**
Screenshot above to show the output of the testing.l

**Logs**
```
18:12:19 [daemon(4824)] [INFO] configuration change detected, restarting worker process...
18:12:19 [worker(15464)] [INFO] engine eventloop has terminated, propagating exit event...
18:12:19 [worker(15464)] [INFO] waiting for engine exit mode...
18:12:19 [worker(15464)] [INFO] exiting worker process...
18:12:19 [daemon(4824)] [INFO] spawning the worker process...
18:12:19 [worker(1244)] [INFO] reading configs from: "C:\\Users\\[REDACTED]\\AppData\\Roaming\\espanso"
18:12:19 [worker(1244)] [INFO] reading packages from: "C:\\Users\\[REDACTED]\\AppData\\Roaming\\espanso\\match\\packages"
18:12:19 [worker(1244)] [INFO] using runtime dir: "C:\\Users\\[REDACTED]\\AppData\\Local\\espanso"
18:12:19 [worker(1244)] [INFO] system info: Windows v10 (22623) - kernel: 22623
18:12:20 [worker(1244)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
18:12:20 [worker(1244)] [INFO] using Win32AppInfoProvider
18:12:20 [worker(1244)] [INFO] monitoring the status of the daemon process
18:12:20 [worker(1244)] [INFO] using Win32Source
18:12:20 [worker(1244)] [INFO] using Win32Injector
18:12:20 [worker(1244)] [INFO] using Win32Clipboard
```

**Setup information**
- OS: Problem is being testing on Windows 11. Trying to paste into Microsoft word.
- Version: espanso 2.1.6-beta

**Comment by jwigg-netscout** [comment]
I believe this would be expected behavior in Markdown: https://itsfoss.com/markdown-new-line/ . 

Try the following and see if it renders correctly for you:

```yaml
  - trigger: ":testing"
    markdown: |-
      These 2 lines  
      should be joined

      But these next lines

      should be separate

    label: "Testing"
```

**Comment by ZerkerEOD** [comment]
> I believe this would be expected behavior in Markdown: https://itsfoss.com/markdown-new-line/ .
> 
> Try the following and see if it renders correctly for you:
> 
> ```yaml
>   - trigger: ":testing"
>     markdown: |-
>       These 2 lines  
>       should be joined
> 
>       But these next lines
> 
>       should be separate
> 
>     label: "Testing"
> ```

That fixed it for me! Thanks for the help, I love this product and I have been getting all my coworkers to use it!
