### ISSUE TITLE
Trigger behavior changed and now showing clipboard history UI

### ISSUE THREAD

**Issue by goodtimeshaxor** [espanso/espanso#1540]
**Describe the bug**
espanso suddenly started opening a clipboard history UI whenever it recognizes a trigger. 

**Expected behavior**
It used to simply replace the typed trigger with what I wanted to replace it with in the config file

**Logs**
11:04:38 [daemon(16328)] [INFO] reading configs from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso"
11:04:38 [daemon(16328)] [INFO] reading packages from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso\\match\\packages"
11:04:38 [daemon(16328)] [INFO] using runtime dir: "C:\\Users\\Admin\\AppData\\Local\\espanso"
11:04:38 [daemon(16328)] [INFO] system info: Windows v10 (19045) - kernel: 19045
11:04:38 [daemon(16328)] [INFO] watching for changes in path: "C:\\Users\\Admin\\AppData\\Roaming\\espanso"
11:04:38 [daemon(16328)] [INFO] espanso version: 2.1.8
11:04:38 [daemon(16328)] [INFO] spawning the worker process...
11:04:38 [daemon(16328)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
11:04:38 [worker(15444)] [INFO] reading configs from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso"
11:04:38 [worker(15444)] [INFO] reading packages from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso\\match\\packages"
11:04:38 [worker(15444)] [INFO] using runtime dir: "C:\\Users\\Admin\\AppData\\Local\\espanso"
11:04:38 [worker(15444)] [INFO] system info: Windows v10 (19045) - kernel: 19045
11:04:38 [worker(15444)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
11:04:38 [worker(15444)] [INFO] monitoring the status of the daemon process
11:04:38 [worker(15444)] [INFO] using Win32AppInfoProvider
11:04:38 [worker(15444)] [INFO] using Win32Source
11:04:38 [worker(15444)] [INFO] using Win32Injector
11:04:38 [worker(15444)] [INFO] using Win32Clipboard
11:06:22 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
11:16:40 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
11:38:19 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
11:40:12 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
12:46:13 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
12:56:54 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
13:08:43 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
13:10:13 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
13:39:16 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
14:02:51 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
14:07:27 [worker(15444)] [WARN] detected outdated modifier records for Shift, releasing the state
00:06:23 [daemon(16328)] [INFO] configuration change detected, restarting worker process...
00:06:23 [worker(15444)] [INFO] engine eventloop has terminated, propagating exit event...
00:06:23 [worker(15444)] [INFO] waiting for engine exit mode...
00:06:23 [worker(15444)] [INFO] exiting worker process...
00:06:23 [daemon(16328)] [INFO] spawning the worker process...
00:06:23 [worker(21264)] [INFO] reading configs from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso"
00:06:23 [worker(21264)] [INFO] reading packages from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso\\match\\packages"
00:06:23 [worker(21264)] [INFO] using runtime dir: "C:\\Users\\Admin\\AppData\\Local\\espanso"
00:06:23 [worker(21264)] [INFO] system info: Windows v10 (19045) - kernel: 19045
00:06:23 [worker(21264)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
00:06:23 [worker(21264)] [INFO] using Win32AppInfoProvider
00:06:23 [worker(21264)] [INFO] monitoring the status of the daemon process
00:06:23 [worker(21264)] [INFO] using Win32Source
00:06:23 [worker(21264)] [INFO] using Win32Injector
00:06:23 [worker(21264)] [INFO] using Win32Clipboard
00:06:29 [worker(21264)] [INFO] engine eventloop has terminated, propagating exit event...
00:06:29 [worker(21264)] [INFO] waiting for engine exit mode...
00:06:29 [worker(21264)] [INFO] exiting worker (to be restarted)
00:06:29 [daemon(16328)] [INFO] worker requested a restart, spawning a new one...
00:06:29 [daemon(16328)] [INFO] spawning the worker process...
00:06:29 [worker(1276)] [INFO] reading configs from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso"
00:06:29 [worker(1276)] [INFO] reading packages from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso\\match\\packages"
00:06:29 [worker(1276)] [INFO] using runtime dir: "C:\\Users\\Admin\\AppData\\Local\\espanso"
00:06:29 [worker(1276)] [INFO] system info: Windows v10 (19045) - kernel: 19045
00:06:29 [worker(1276)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
00:06:29 [worker(1276)] [INFO] using Win32AppInfoProvider
00:06:29 [worker(1276)] [INFO] monitoring the status of the daemon process
00:06:29 [worker(1276)] [INFO] using Win32Source
00:06:29 [worker(1276)] [INFO] using Win32Injector
00:06:29 [worker(1276)] [INFO] using Win32Clipboard
00:06:35 [daemon(16328)] [INFO] configuration change detected, restarting worker process...
00:06:35 [worker(1276)] [INFO] engine eventloop has terminated, propagating exit event...
00:06:35 [worker(1276)] [INFO] waiting for engine exit mode...
00:06:35 [worker(1276)] [INFO] exiting worker process...
00:06:35 [daemon(16328)] [INFO] spawning the worker process...
00:06:35 [worker(17412)] [INFO] reading configs from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso"
00:06:35 [worker(17412)] [INFO] reading packages from: "C:\\Users\\Admin\\AppData\\Roaming\\espanso\\match\\packages"
00:06:35 [worker(17412)] [INFO] using runtime dir: "C:\\Users\\Admin\\AppData\\Local\\espanso"
00:06:35 [worker(17412)] [INFO] system info: Windows v10 (19045) - kernel: 19045
00:06:35 [worker(17412)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
00:06:35 [worker(17412)] [INFO] using Win32AppInfoProvider
00:06:35 [worker(17412)] [INFO] monitoring the status of the daemon process
00:06:35 [worker(17412)] [INFO] using Win32Source
00:06:35 [worker(17412)] [INFO] using Win32Injector
00:06:35 [worker(17412)] [INFO] using Win32Clipboard

**Setup information**
- OS: Windows 10 Pro
- Version: 2.1.8

**Comment by goodtimeshaxor** [comment]
My control key was swapped with my GUI key. And that was causing the clipboard to open instead of pasting my text instantly.

**Comment by kpym** [comment]
@goodtimeshaxor you can probably close this issue ;)
