### ISSUE TITLE
Regex sample not working

### ISSUE THREAD

**Issue by GrafDogi** [espanso/espanso#1542]
A month ago I began to use your helpful program!
Thanks for that!

Once in a while I am trying out what you described in your espanso docs.

I wanted to try out the following:

`  - regex: ":greet\\(.*\\)"`
`    replace: "Hi John!"`

So I typed `:greetDogi`, but nothing happened :-(

Did I do something wrong?
Thanks for any help!

**Comment by jwigg-netscout** [comment]
I believe the correct trigger for the given regex would `:greet(Dogi)` . Can you confirm whether that works for you?

**Comment by GrafDogi** [comment]
Ah yes, you are right. I forgot to use/mention the parentheses.
Thanks, works now!


But I swear, yesterday it didn't! :-o
