### ISSUE TITLE
Text not expanding in elevated Powershell

### ISSUE THREAD

**Issue by BURG3R5** [espanso/espanso#1548]
**Describe the bug**
I'm running an elevated powershell in Windows Terminal and trying to use espanso to contract commands, but they just don't expand when used there. Every other place they work properly. (Tested regular command prompt and powershell - works. Tested elevated powershell and command prompt - doesn't work)

**To Reproduce**
1. Run Powershell as Adminstrator
2. Type `:espanso`

**Expected behavior**
Text should be replaced by `Hi there!`

**Setup information**
- OS: Windows 10 22H2
- Version: 2.1.8

**Comment by joh6nn** [comment]
This is expected behavior due to Windows security design, see #1576. TL;DR: if it were possible for apps running without elevated privs to send input to apps running with elevated privs, then it would be possible for malware to send input to elevated apps, too 🤷

**Comment by BURG3R5** [comment]
Makes sense, thanks!
