### ISSUE TITLE
Espanso catches Alt code (Alt+Numpad) in Windows

### ISSUE THREAD

**Issue by llvs** [espanso/espanso#1556]
Dear Espanso devs,

Thank you for that nice tool! 
When I want to insert a special character like a long dash "–", I do so using the Alt+NumPad way (in that case Alt+0150).
As long as Espanso is running, it seems to catch the entering of the Alt codes and none of them work. Exiting Espanso restores the normal behavior and starting Espanso again makes the Alt codes unavailable again.

Best regards
llvs

**Comment by KAGEYAM4** [comment]
refer to this #988

**Comment by smeech** [comment]
I'll close this for now as I believe this was fixed, but if the problem persists with the current version of Espanso, we can reopen it.
