### ISSUE TITLE
Unable to type alt+number codes when espanso is running

### ISSUE THREAD

**Issue by apgrom** [espanso/espanso#1588]
**Describe the bug**
Unable to type alt+064 to type @ or alt+241 to type ñ

**To Reproduce**
1. run espanso
2. Open any app e.g. notepad and try to type the characters above

**Expected behavior**
Be able to do this without deactivating espanso

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
08:47:21 [daemon(5824)] [INFO] reading configs from: "C:\\Users\\adp\\AppData\\Roaming\\espanso"
08:47:21 [daemon(5824)] [INFO] reading packages from: "C:\\Users\\adp\\AppData\\Roaming\\espanso\\match\\packages"
08:47:21 [daemon(5824)] [INFO] using runtime dir: "C:\\Users\\adp\\AppData\\Local\\espanso"
08:47:21 [daemon(5824)] [INFO] system info: Windows v10 (19044) - kernel: 19044
08:47:21 [daemon(5824)] [INFO] watching for changes in path: "C:\\Users\\adp\\AppData\\Roaming\\espanso"
08:47:21 [daemon(5824)] [INFO] espanso version: 2.1.8
08:47:21 [daemon(5824)] [INFO] spawning the worker process...
08:47:21 [daemon(5824)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
08:47:21 [worker(21740)] [INFO] reading configs from: "C:\\Users\\adp\\AppData\\Roaming\\espanso"
08:47:21 [worker(21740)] [INFO] reading packages from: "C:\\Users\\adp\\AppData\\Roaming\\espanso\\match\\packages"
08:47:21 [worker(21740)] [INFO] using runtime dir: "C:\\Users\\adp\\AppData\\Local\\espanso"
08:47:21 [worker(21740)] [INFO] system info: Windows v10 (19044) - kernel: 19044
08:47:21 [worker(21740)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
08:47:21 [worker(21740)] [INFO] using Win32AppInfoProvider
08:47:21 [worker(21740)] [INFO] monitoring the status of the daemon process
08:47:21 [worker(21740)] [INFO] using Win32Source
08:47:21 [worker(21740)] [INFO] using Win32Injector
08:47:21 [worker(21740)] [INFO] using Win32Clipboard

**Setup information**
- OS: Windows 10 
- Version:  espanso 2.1.8

**Comment by 13324** [comment]
This seems to be a known problem. See #988 and #1277 for further details.

**Comment by kpym** [comment]
This could be closed, just like the others:

#1060 → #988 
#1151 → #988 
#1556 → #988

But the question is, what is the status of #1277?

**Comment by federico-terzi** [comment]
@apgrom Please try adding this line to your configuration :)

```
emulate_alt_codes: true
```

> But the question is, what is the status of https://github.com/espanso/espanso/pull/1277?

@kpym It's available in the latest version, but disabled by default. We should probably enable this by default in the next release :)
