### ISSUE TITLE
Wrong output using Cursor Hint feature

### ISSUE THREAD

**Issue by jgroboredo** [espanso/espanso#1597]
**Describe the bug**
After a fresh installation of  `espanso`, I appended a simple Cursor Hint based expansion to the `base.yml` file:

```
- trigger: ":("
  replace: "($|$)"
```

without modifying anything else. The output of the trigger is: `)=` (this was even obtained using `espanso`). However, after running `espanso restart`, I obtain the expected behavior: `()` (obtained again using `espanso`).

I can repeat this behavior every time I restart my computer. After running `espanso restart` for the first time after booting, it never happens again.

> Note: This type of weird behavior only seems to happen when using the Cursor Hint feature.

**To Reproduce**
1. Install espanso (I have tried building from source and the AppImage);
2. Append to the `base.yml` the following lines:

    ```
    - trigger: ":("
      replace: "($|$)"
   ```

3. Use the trigger `:(`.

**Expected behavior**
It should expand the trigger to `()` with the cursor in the middle without the need of restarting `espanso`. 

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
The logs don't show any issues:
```
16:20:24 [daemon(5150)] [INFO] reading configs from: "/home/goncalo/.config/espanso"
16:20:24 [daemon(5150)] [INFO] reading packages from: "/home/goncalo/.config/espanso/match/packages"
16:20:24 [daemon(5150)] [INFO] using runtime dir: "/home/goncalo/.cache/espanso"
16:20:24 [daemon(5150)] [INFO] system info: Arch Linux v - kernel: 6.2.13-arch1-1
16:20:24 [daemon(5150)] [INFO] watching for changes in path: "/home/goncalo/.config/espanso"
16:20:24 [daemon(5150)] [INFO] espanso version: 2.2.0
16:20:24 [daemon(5150)] [INFO] spawning the worker process...
16:20:24 [daemon(5150)] [INFO] binded to IPC unix socket: /home/goncalo/.cache/espanso/espansodaemonv2.sock
16:20:25 [worker(5158)] [INFO] reading configs from: "/home/goncalo/.config/espanso"
16:20:25 [worker(5158)] [INFO] reading packages from: "/home/goncalo/.config/espanso/match/packages"
16:20:25 [worker(5158)] [INFO] using runtime dir: "/home/goncalo/.cache/espanso"
16:20:25 [worker(5158)] [INFO] system info: Arch Linux v - kernel: 6.2.13-arch1-1
16:20:25 [worker(5158)] [INFO] binded to IPC unix socket: /home/goncalo/.cache/espanso/espansoworkerv2.sock
16:20:25 [worker(5158)] [INFO] using X11AppInfoProvider
16:20:25 [worker(5158)] [INFO] monitoring the status of the daemon process
16:20:25 [worker(5158)] [INFO] using X11Source
16:20:25 [worker(5158)] [INFO] using X11ProxyInjector
16:20:26 [worker(5158)] [INFO] using X11Clipboard
```

**Setup information**
- OS: Arch Linux v - kernel: 6.2.13-arch1-1 (using i3 wm)
- Version: 2.2.0

**Comment by jgroboredo** [comment]
After further analyzing the logs, I actually left something out which might be relevant (but is not shown with `espanso log`).

The output of `systemctl --user status espanso` is the following:

```
mai 01 22:03:13 goncalo espanso[1598]: 22:03:13 [worker(1598)] [INFO] system info: Arch Linux v - kernel: 6.2.13-arch1-1
mai 01 22:03:13 goncalo espanso[1598]: 22:03:13 [worker(1598)] [INFO] using X11AppInfoProvider
mai 01 22:03:13 goncalo espanso[1598]: 22:03:13 [worker(1598)] [INFO] binded to IPC unix socket: /home/goncalo/.cache/espanso/espansoworkerv2.sock
mai 01 22:03:13 goncalo espanso[1598]: 22:03:13 [worker(1598)] [INFO] using X11Source
mai 01 22:03:13 goncalo espanso[1598]: 22:03:13 [worker(1598)] [INFO] monitoring the status of the daemon process
mai 01 22:03:13 goncalo espanso[1598]: 22:03:13 [worker(1598)] [INFO] using X11ProxyInjector
mai 01 22:03:13 goncalo espanso[1598]: 22:03:13 [worker(1598)] [INFO] using X11Clipboard
mai 01 22:03:23 goncalo espanso[1598]: get_active_window reported an error
mai 01 22:03:23 goncalo espanso[1598]: get_active_window reported an error
mai 01 22:03:23 goncalo espanso[1598]: get_active_window reported an error
``` 
Delaying `espanso.service` by adding:

```
ExecStartPre=/bin/sleep 10
```
solves the problem. 

I start i3 roughly by running `startx` in my `.zprofile` , where my `.xinitrc` basically just runs `exec i3`.
It seems that, at the time `espanso` daemon is started, something isn't yet ready. 

Thanks for all the help you can give to this problem!

**Comment by federico-terzi** [comment]
Hey @jgroboredo,

Thanks for reporting! Which keyboard layout are you using? IIRC, if you start espanso too early in the startup process, the system will default to a US layout, which could cause these issues

Anyway, I'll close this issue as you found a valid workaround :) Thanks!
