### ISSUE TITLE
Regex that works in Windows 11 does not work in Windows 10

### ISSUE THREAD

**Issue by marcohuertaroldan** [espanso/espanso#1610]
I am trying to use the following regex match:
  - regex: ":greet\\d"
and while it works fine in my Windows 11 computer, when I try to run it in Windows 10, it does not work. In fact, in Windows 10 the rest of the non-regex triggers in my base.yml file from my Windows 11 work fine. I wonder if I need to install Rust or some library. I have tried to reinstall Espanso to no avail
The only noticeable difference I see in the log is Windows 10 reads "system info: Windows v10 (19044) - kernel: 19044", while Windows 11 reads "system info: Windows v10 (22000) - kernel: 22000

**Comment by kpym** [comment]
This doesn't look like a Win10/Win11 issue. This is a problem with how yaml strings are handled. You can fix this in two ways: 

by escaping the backslash
```yaml
- regex: ":greet\\d"
```

or simply by removing the quotes
```yaml
- regex: :greet\d
```

To learn more about yaml strings, you can check out [yaml-multiline.info](https://yaml-multiline.info)

If this solves your problem, please consider closing this issue.
