### ISSUE TITLE
Issue with Capslock in Wayland

### ISSUE THREAD

**Issue by idr4n** [espanso/espanso#1628]
**Describe the bug**

I'm using Sway/Wayland and have setup caps to work as ctrl. For that I have in my Sway config `input "type:keyboard" { xkb_options ctrl:nocaps }`

This works as expected in the system, however when using espanso, every time I use the Capslock key as ctrl, which is all the time, espanso "sees" that as if Caps are activated nonetheless and so the espanso matches are not expanded. Note that caps are not activated really as the characters typed are in small case, but espanso sees this as if caps are activated. Not sure if it makes sense.

Maybe I am missing some config somewhere?

Thanks in advance for pointing me in the right direction on solving this issue.

**Setup information**
- OS: What OS are you using? Sway/Wayland/Arch
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal): 2.2.0

**Logs**
10:50:54 [daemon(7806)] [INFO] reading configs from: "/home/iduran/.config/espanso"
10:50:54 [daemon(7806)] [INFO] reading packages from: "/home/iduran/.config/espanso/match/packages"
10:50:54 [daemon(7806)] [INFO] using runtime dir: "/home/iduran/.cache/espanso"
10:50:54 [daemon(7806)] [INFO] system info: Arch Linux vrolling - kernel: 6.3.8-arch1-1
10:50:54 [daemon(7806)] [WARN] keyboard layout watcher couldn't determine active layout.
10:50:54 [daemon(7806)] [INFO] watching for changes in path: "/home/iduran/.config/espanso"
10:50:54 [daemon(7806)] [INFO] espanso version: 2.2.0
10:50:54 [daemon(7806)] [INFO] spawning the worker process...
10:50:54 [daemon(7806)] [INFO] binded to IPC unix socket: /home/iduran/.cache/espanso/espansodaemonv2.sock
10:50:54 [worker(7812)] [INFO] reading configs from: "/home/iduran/.config/espanso"
10:50:54 [worker(7812)] [INFO] reading packages from: "/home/iduran/.config/espanso/match/packages"
10:50:54 [worker(7812)] [INFO] using runtime dir: "/home/iduran/.cache/espanso"
10:50:54 [worker(7812)] [INFO] system info: Arch Linux vrolling - kernel: 6.3.8-arch1-1
10:50:54 [worker(7812)] [INFO] binded to IPC unix socket: /home/iduran/.cache/espanso/espansoworkerv2.sock
10:50:54 [worker(7812)] [INFO] using WaylandAppInfoProvider
10:50:54 [worker(7812)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us, V=, O=]
10:50:54 [worker(7812)] [INFO] monitoring the status of the daemon process
10:50:54 [worker(7812)] [INFO] using EVDEVSource
10:50:55 [worker(7812)] [INFO] Querying modifier status...
10:50:55 [worker(7812)] [INFO] inject module will use this keyboard layout: [R=, M=, L=us, V=, O=]
10:50:55 [worker(7812)] [INFO] using EVDEVInjector
10:50:55 [worker(7812)] [INFO] using WaylandFallbackClipboard
10:50:55 [worker(7812)] [ERROR] Unable to show notification: The name org.freedesktop.Notifications was not provided by any .service files

**Comment by Steve-V** [comment]
This also happens on Fedora 39 Wayland when capslock is swapped with ctrl.

**Comment by Steve-V** [comment]
I've solved this issue with the addition of `options: ctrl:swapcaps` to my Espanso keyboard layout config.

**Comment by idr4n** [comment]
> I've solved this issue with the addition of `options: ctrl:swapcaps` to my Espanso keyboard layout config.

Thanks a lot @Steve-V. That seems to have solved the issue for me as well! I have not experienced it after adding this option.

**Comment by bekoeppel** [comment]
I had a very similar issue, and your hint to configure `options` turned out to be the right path. I set `options: ctrl:nocaps` to disable Espanso from (mistakenly) turn on/off my caps lock.

See https://github.com/espanso/espanso/issues/1783#issuecomment-2254251623
