### ISSUE TITLE
package install fails on debian trixie

### ISSUE THREAD

**Issue by khimaros** [espanso/espanso#1662]
**Logs**

```
The following packages have unmet dependencies:
 espanso-wayland : Depends: libwxgtk3.0-gtk3-0v5 but it is not installable
                   Depends: libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg) but it is not installable
                   Depends: libwxbase3.0-0v5 (>= 3.0.4+dfsg) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Setup information**
- OS: What OS are you using? debian trixie (testing)
- Version: which version of Espanso are you running? attempting to install 2.1.8

**Analysis**

the issue is that debian does not have these versions of wx any longer:

```
$ apt search '^libwx(base|gtk3)'
Sorting... Done
Full Text Search... Done
libwxbase3.2-1/testing,unstable,now 3.2.2+dfsg-2 amd64 [installed,automatic]
  wxBase library (runtime) - non-GUI support classes of wxWidgets toolkit

libwxgtk3.2-1/testing,unstable,now 3.2.2+dfsg-2 amd64 [installed,automatic]
  wxWidgets Cross-platform C++ GUI toolkit (GTK 3 runtime)

libwxgtk3.2-dev/testing,unstable,now 3.2.2+dfsg-2 amd64 [installed,automatic]
  wxWidgets Cross-platform C++ GUI toolkit (GTK 3 development)
```

however, this seems to be more than simply a packaging issue. when i extract the deb and manually execute the binary, it fails because it is linked to `libwx_gtk3u_html-3.0.so` which doesn't exist on my system. i'm not sure if there were breaking APi changes between these versions of libgtk.

**Comment by KwisatzJim** [comment]
I ran into the same problem and got around it by manually compiling and installing libwxgtk3.2-dev instead of libwxgtk3.0-gtk3-dev
