### ISSUE TITLE
changing search shortcut

### ISSUE THREAD

**Issue by MrWonka00** [espanso/espanso#1673]
**Describe the bug**
changing or turnig of the search shortcut doesn't work
even if copy & pasting "search_shortcut: ALT+SHIFT+SPACE" or "search_shortcut: off!"  from the website
I then get the report to fix the error in the file

**To Reproduce**
1.add "search_shortcut: ALT+SHIFT+SPACE" or "search_shortcut: off!" to $CONFIG/config/default.yml in a new line and safe the document
2.error occours and program sometimes stops to work completely

**Expected behavior**
changing search shortcut to ALT + SHIFT + SACE or turning the search shortcut off

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://github.com/espanso/espanso/assets/101603872/02302009-11f9-49dd-addf-a950263050b4)
![image](https://github.com/espanso/espanso/assets/101603872/165f093d-9f83-4390-b661-119e1376ce92)

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem
21:33:55 [daemon(11572)] [INFO] reading configs from: "C:\\Users\\willi\\AppData\\Roaming\\espanso"
21:33:55 [daemon(11572)] [INFO] reading packages from: "C:\\Users\\willi\\AppData\\Roaming\\espanso\\match\\packages"
21:33:55 [daemon(11572)] [INFO] using runtime dir: "C:\\Users\\willi\\AppData\\Local\\espanso"
21:33:55 [daemon(11572)] [INFO] system info: Windows v10 (19045) - kernel: 19045
21:33:55 [daemon(11572)] [INFO] watching for changes in path: "C:\\Users\\willi\\AppData\\Roaming\\espanso"
21:34:07 [daemon(11572)] [INFO] config change detected, reloading configs...
21:34:07 [daemon(11572)] [INFO] espanso version: 2.1.8
21:34:07 [daemon(11572)] [INFO] spawning the worker process...
21:34:07 [daemon(11572)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
21:34:07 [worker(16788)] [INFO] reading configs from: "C:\\Users\\willi\\AppData\\Roaming\\espanso"
21:34:07 [worker(16788)] [INFO] reading packages from: "C:\\Users\\willi\\AppData\\Roaming\\espanso\\match\\packages"
21:34:07 [worker(16788)] [INFO] using runtime dir: "C:\\Users\\willi\\AppData\\Local\\espanso"
21:34:07 [worker(16788)] [INFO] system info: Windows v10 (19045) - kernel: 19045
21:34:08 [worker(16788)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
21:34:08 [worker(16788)] [INFO] monitoring the status of the daemon process
21:34:08 [worker(16788)] [INFO] using Win32AppInfoProvider
21:34:08 [worker(16788)] [INFO] using Win32Source
21:34:08 [worker(16788)] [INFO] using Win32Injector
21:34:08 [worker(16788)] [INFO] using Win32Clipboard
21:34:13 [worker(16788)] [INFO] toggled enabled state, is_enabled = false
21:34:22 [daemon(11572)] [INFO] configuration change detected, restarting worker process...
21:34:22 [daemon(11572)] [ERROR] critical error while loading config, could not restart worker
21:34:35 [daemon(11572)] [INFO] configuration change detected, restarting worker process...
21:34:35 [worker(16788)] [INFO] engine eventloop has terminated, propagating exit event...
21:34:35 [worker(16788)] [INFO] waiting for engine exit mode...
21:34:35 [worker(16788)] [INFO] exiting worker process...
21:34:35 [daemon(11572)] [INFO] spawning the worker process...
21:34:35 [worker(17228)] [INFO] reading configs from: "C:\\Users\\willi\\AppData\\Roaming\\espanso"
21:34:35 [worker(17228)] [INFO] reading packages from: "C:\\Users\\willi\\AppData\\Roaming\\espanso\\match\\packages"
21:34:35 [worker(17228)] [INFO] using runtime dir: "C:\\Users\\willi\\AppData\\Local\\espanso"
21:34:35 [worker(17228)] [INFO] system info: Windows v10 (19045) - kernel: 19045
21:34:36 [worker(17228)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
21:34:36 [worker(17228)] [INFO] monitoring the status of the daemon process
21:34:36 [worker(17228)] [INFO] using Win32AppInfoProvider
21:34:36 [worker(17228)] [INFO] using Win32Source
21:34:36 [worker(17228)] [INFO] using Win32Injector
21:34:36 [worker(17228)] [INFO] using Win32Clipboard
21:39:50 [daemon(11572)] [INFO] configuration change detected, restarting worker process...
21:39:50 [daemon(11572)] [ERROR] critical error while loading config, could not restart worker
21:43:13 [daemon(11572)] [INFO] configuration change detected, restarting worker process...
21:43:15 [daemon(11572)] [ERROR] critical error while loading config, could not restart worker

**Setup information**
- OS: What OS are you using? Windows 10
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal) 2.1.8

**Comment by jwigg-netscout** [comment]
i think it's an indentation issue: i believe you need to have 2 blank spaces before the setting because it's part of a YAML collection. For example, see the toggle_key setting directly above the search_shortcut setting

**Comment by MrWonka00** [comment]
Works :)

**Comment by kpym** [comment]
@MrWonka00 If it works, you can close this issue ;)
