### ISSUE TITLE
Espanso does not work in GTK4 apps.

### ISSUE THREAD

**Issue by victorandraderam** [espanso/espanso#1689]
**Describe the bug**
When I have tried to expand text using my registered triggers, nothing happens in GTK4 apps. In GTK3 apps, everything goes smoothly.
**To Reproduce**
1. Try to use an espanso trigger (e.g. : espanso) in a GTK 4 (e.g. Blackbox or Nautilus) nothing happens. In GTK3 apps (e.g. Gnome-terminal) there is no problem.

**Expected behavior**
Proper expansion of a trigger

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
18:29:14 [worker(2519)] [INFO] using X11AppInfoProvider
18:29:14 [worker(2519)] [INFO] monitoring the status of the daemon process
18:29:14 [worker(2519)] [INFO] using X11Source
18:29:14 [worker(2519)] [INFO] using X11ProxyInjector
18:29:14 [worker(2519)] [INFO] using X11Clipboard
09:49:47 [daemon(2511)] [INFO] configuration change detected, restarting worker process...
09:49:47 [worker(2519)] [INFO] engine eventloop has terminated, propagating exit event...
09:49:47 [worker(2519)] [INFO] waiting for engine exit mode...
09:49:47 [worker(2519)] [INFO] exiting worker process...
09:49:47 [daemon(2511)] [INFO] spawning the worker process...
09:49:47 [worker(23601)] [INFO] reading configs from: "/home/victorandrade/.config/espanso"
09:49:47 [worker(23601)] [INFO] reading packages from: "/home/victorandrade/.config/espanso/match/packages"
09:49:47 [worker(23601)] [INFO] using runtime dir: "/home/victorandrade/.cache/espanso"
09:49:47 [worker(23601)] [INFO] system info: EndeavourOS vrolling - kernel: 6.4.12-arch1-1
09:49:47 [worker(23601)] [INFO] binded to IPC unix socket: /home/victorandrade/.cache/espanso/espansoworkerv2.sock
09:49:47 [worker(23601)] [INFO] using X11AppInfoProvider
09:49:47 [worker(23601)] [INFO] monitoring the status of the daemon process
09:49:47 [worker(23601)] [INFO] using X11Source
09:49:47 [worker(23601)] [INFO] using X11ProxyInjector
09:49:47 [worker(23601)] [INFO] using X11Clipboard
[victorandrade@casa ~]$ 

**Setup information**
Archlinux, X11, Gnome 44.

**Comment by diegonz** [comment]
Same issue here using `gnome-text-editor` in Ubuntu 23.04, X11 and GNOME 44.

**Comment by eclipseo** [comment]
I manage to make it work with gnome -text-editor on X11:

```
filter_class: "gnome-text-editor"
backend: Inject

disable_x11_fast_inject: true
```

**Comment by victorandraderam** [comment]
> I manage to make it work with gnome -text-editor on X11:
> 
> ```
> filter_class: "gnome-text-editor"
> disable_x11_fast_inject: true
> ```

Your proposed workaround works perfectly,Thank you  :) . I've added to my default.yml
