### ISSUE TITLE
3 "espansod.exe" tasks in Windows manager : expected behavior ?

### ISSUE THREAD

**Issue by Elaws** [espanso/espanso#1713]
![image](https://github.com/espanso/espanso/assets/52013479/dc61ef0b-bfa3-4cea-bb76-4cd5133d2f3b)

Is this the expected behavior ?

Thank you.

**Comment by an7wu** [comment]
Same on my machine. But I'm not sure that's an error. There are other programs with double or triple entries in my task manager.

**Comment by federico-terzi** [comment]
Yes it's expected, Espanso divides its work into multiple processes :)
