### ISSUE TITLE
Python Scripts Running Very Slow

### ISSUE THREAD

**Issue by andrewcincotta** [espanso/espanso#1719]
I have a text replacement that should run a python script. It works, but takes 5+ seconds to execute.
Attached are screenshots detailing the text expansion in base.yml and the python script's contents.

<img width="464" alt="image" src="https://github.com/espanso/espanso/assets/116472178/eb6226a0-5969-49f8-9e3d-6b2edbeca18b">

<img width="789" alt="image" src="https://github.com/espanso/espanso/assets/116472178/97a46a95-4164-4c53-a797-531b7cf25d48">

**Comment by kpym** [comment]
I'm trying to understand the situation better. From what I know, Espanso executes the script provided and waits for its output. If the script takes 5 seconds to run, Espanso waits for that duration. Could you please provide more details on why you suspect an Espanso issue in this case?

**Comment by AucaCoyan** [comment]
No response. Closing
