### ISSUE TITLE
open -a Espanso.app not working

### ISSUE THREAD

**Issue by lucaesse** [espanso/espanso#1725]
**Describe the bug**
I'm an IT admin and I'm deploying  the Espanso app to my users' macs. I need the app to open automatically after installation but running the "sudo open -a Espanso" command nothing happens because the command is run as administrator.
If I try to run the same command as a standard user it works. 

**To Reproduce**
1. Try to open Espanso from shell using sudo.

**Expected behavior**
I need to open the app on user's Mac as logged-in user. 

**Screenshots**

**Logs**

**Setup information**
- OS: macOS Ventura?
- Version: v2.1.8 .app

**Comment by mistahBen** [comment]
what happens when you try running it *as* the signed in user?

`sudo -u {username} open -a Epanso`

if you need to look for the current user:

`stat -f '%u %Su' /dev/console` will return the user currently signed into the GUI.

**Comment by AucaCoyan** [comment]
Closing because of not receiving the input from the user 😢
