### ISSUE TITLE
Disable "Espanso is already running!" window

### ISSUE THREAD

**Issue by alfureu** [espanso/espanso#1726]
**Describe the bug**
Whenever I start my PC, the espanso window pops up. Would it be please possible to provide a setting to disable this - as I never had any issue with Espanso startup (and the window wastes my time)

**To Reproduce**
1. Start Windows with Espanso

**Expected behavior**
Allow disabling pop-up window from startup

**Screenshots**
![image](https://github.com/espanso/espanso/assets/10846169/322a5546-41be-4f7a-821a-cd6a1f012aab)

**Logs**
N/A

**Setup information**
- OS: Windows 10
- Version: 2.1.8

**Comment by marsender** [comment]
Same for me, as a linux user

**Comment by kpym** [comment]
@alfureu It looks like you are running espanso twice, not just once as you describe. Check your startup configuration.

**Comment by AucaCoyan** [comment]
Closing by age. If somebody has the same issue, I will gladly re-open!
