### ISSUE TITLE
Regex substitution does not work with comma while it works with other characters

### ISSUE THREAD

**Issue by ricir** [espanso/espanso#1727]
**Describe the bug**
Regex substitution does not work with comma while it works with other characters
The below regex match should remove spaces between a word and a punctuation sign (, . ; :)
It is working correctly with all signs but not with comma.

**To Reproduce**
Try the following:
```
- regex: "(?P<word>\\S+)(?P<space>\\s+)(?P<comma>[;:,\\.])"
  replace: "{{word}}{{punct}}"`
```
This is working correctly removing the spaces, keeping the punctuation but not for comma.

When using the **comma**  it works only for **one space** between word and comma, while if there is more than one space the comma disappears ad the last character of the word is cut.

The regex has been tested with success in regex testing websites.

![image](https://github.com/espanso/espanso/assets/52215524/bfb799d4-58fa-4876-a639-93f49be25db9)
Line 1 without espanso running, line 2 with espanso running.

**Logs**
Just after the error has occurred. The log is identical when no error occurs.
```
$ espanso log
14:50:28 [daemon(303690)] [INFO] reading configs from: "/home/ricir/.config/espanso"
14:50:28 [daemon(303690)] [INFO] reading packages from: "/home/ricir/.config/espanso/match/packages"
14:50:28 [daemon(303690)] [INFO] using runtime dir: "/home/ricir/.cache/espanso"
14:50:28 [daemon(303690)] [INFO] system info: Debian GNU/Linux v11 - kernel: 5.14.0-4mx-amd64
14:50:28 [daemon(303690)] [INFO] watching for changes in path: "/home/ricir/.config/espanso"
14:50:28 [daemon(303690)] [INFO] espanso version: 2.1.8
14:50:28 [daemon(303690)] [INFO] spawning the worker process...
14:50:28 [daemon(303690)] [INFO] binded to IPC unix socket: /home/ricir/.cache/espanso/espansodaemonv2.sock
14:50:28 [worker(303698)] [INFO] reading configs from: "/home/ricir/.config/espanso"
14:50:28 [worker(303698)] [INFO] reading packages from: "/home/ricir/.config/espanso/match/packages"
14:50:28 [worker(303698)] [INFO] using runtime dir: "/home/ricir/.cache/espanso"
14:50:28 [worker(303698)] [INFO] system info: Debian GNU/Linux v11 - kernel: 5.14.0-4mx-amd64
14:50:28 [worker(303698)] [INFO] binded to IPC unix socket: /home/ricir/.cache/espanso/espansoworkerv2.sock
14:50:28 [worker(303698)] [INFO] using X11AppInfoProvider
14:50:28 [worker(303698)] [INFO] monitoring the status of the daemon process
14:50:28 [worker(303698)] [INFO] using X11Source
14:50:28 [worker(303698)] [INFO] using X11ProxyInjector
14:50:29 [worker(303698)] [INFO] using X11Clipboard

```
**Setup information**
- OS: Linux MX-21.3_ahs_x64 Wildflower
- Version: 2.1.8

**Comment by smeech** [comment]
I can't duplicate the above. It generates the error: “[Espanso]: An error occurred during rendering, please examine the logs for more information.”, for all the punctuation marks here (Linux Mint 21.2, Xfce 4.18, espanso 2.1.8). From some experimentation it's the same error when the variables names don't match so it's possible the Regex isn't generating the variables.

```yaml
matches:
  - regex: (?P<word>\S+)\s+(?P<punct>[.,;:!?])
    replace: "{{word}}{{punct}} "
```
appears to work though.

**Comment by ricir** [comment]
Thank you @smeech the regex is working. 

Unfortunately I completely forgot a previous simple (not regex) replacement I made in another package (replacing space comma with comma ) and this caused the problem by overlapping of the two replacements..
