### ISSUE TITLE
Not expanding in LibreOffice writer when using searchbox

### ISSUE THREAD

**Issue by ismakoch** [espanso/espanso#1738]
**Describe the bug**
When working on LibreOffice writer and typing a trigger that opens the search bar, once I select (by clicking or hitting enter on) the expanded text to be inserted, no expansion happens. Instead, some LibreOffice menu or command is started. It seems like the search bar sends an "Alt+(some number)" to LOWriter which triggers a menu to be opened.

**To Reproduce**
1. use espanso portable
2. open LibreOffice writer 7.5.6.2
3. enter a trigger that pops up the search bar presenting the options for that trigger to be inserted.
4. select the expanded text by click or with the keyboard arrows + Enter

**Expected behavior**
Some menu or LibreOffice command will open, depending on the content of the expanded text.

**Logs**
Nothing appears on log

**Setup information**
- OS: Windows 10
- Version: espanso 2.1.8 (portable)

**Comment by ismakoch** [comment]
After a few more tests, I found out that by disabling LibreOffice's classic menu bar the text expansion works as expected and doesn't trigger any menus or windows of LibreOffice. Enabling only LibreOffice's ribbon menu solved the problem.

**Comment by gcailly** [comment]
I filled a bug on LibreOffice bugzilla about this issue : https://bugs.documentfoundation.org/show_bug.cgi?id=164008

I found another workaround : pressing ALT one time, then ALT + SPACE. And the string is pasted.
