### ISSUE TITLE
option to turn off espanso popup window at startup

### ISSUE THREAD

**Issue by atanasj** [espanso/espanso#1740]
It would be great if the espanso popup window on startup window could be disabled. I am on Arch linux running Hyprland.

**Comment by smeech** [comment]
You can use `show_notifications: false` in default.yml but it will turn them all off, which may not be a problem unless you're actively configuring espanso.

**Comment by AucaCoyan** [comment]
Hi! Thanks for submiting an issue. I'm going to close it because the feature is already implemented
