### ISSUE TITLE
unable to start service: timed out

### ISSUE THREAD

**Issue by alanef** [espanso/espanso#1751]
**Describe the bug**
`espanso start `                  
unable to start service: timed out
Hint: sometimes this happens because another Espanso process is left running for some reason.
      Please try running 'espanso restart' or manually killing all Espanso processes, then try again.

**To Reproduce**
`espanso start `     

**Expected behavior**
To work
èspanso launcher` works

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

espanso log
11:01:20 [daemon(11868)] [INFO] reading configs from: "/home/alan/.config/espanso"
11:01:20 [daemon(11868)] [INFO] reading packages from: "/home/alan/.config/espanso/match/packages"
11:01:20 [daemon(11868)] [INFO] using runtime dir: "/home/alan/.cache/espanso"
11:01:20 [daemon(11868)] [INFO] system info: Debian GNU/Linux v10 - kernel: 4.19.0-21-amd64
11:01:20 [daemon(11868)] [INFO] watching for changes in path: "/home/alan/.config/espanso"
11:01:20 [daemon(11868)] [INFO] espanso version: 2.2.0
11:01:20 [daemon(11868)] [INFO] spawning the worker process...
11:01:20 [daemon(11868)] [INFO] binded to IPC unix socket: /home/alan/.cache/espanso/espansodaemonv2.sock
11:01:20 [daemon(11868)] [WARN] keyboard layout watcher couldn't determine active layout.
11:01:20 [worker(11876)] [INFO] reading configs from: "/home/alan/.config/espanso"
11:01:20 [worker(11876)] [INFO] reading packages from: "/home/alan/.config/espanso/match/packages"
11:01:20 [worker(11876)] [INFO] using runtime dir: "/home/alan/.cache/espanso"
11:01:20 [worker(11876)] [INFO] system info: Debian GNU/Linux v10 - kernel: 4.19.0-21-amd64
11:01:20 [worker(11876)] [INFO] using X11AppInfoProvider
11:01:20 [worker(11876)] [INFO] binded to IPC unix socket: /home/alan/.cache/espanso/espansoworkerv2.sock
11:01:20 [worker(11876)] [INFO] using X11Source
11:01:20 [worker(11876)] [INFO] monitoring the status of the daemon process
11:01:20 [worker(11876)] [ERROR] X11Source destruction cannot be performed, handle is null
11:01:20 [worker(11876)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:139
11:01:20 [worker(11876)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
11:01:20 [worker(11876)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
11:01:20 [daemon(11868)] [ERROR] received unexpected exit code from worker 101, exiting

**Setup information**
- OS: What OS are you using?
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
`espanso -V`
espanso 2.2.0

echo $XDG_SESSION_TYPE
x11

**Comment by AucaCoyan** [comment]
Hi! Sorry for the delay, I happened to have this issue and I solved with
```bash
sudo setcap "cap_dac_override+p" $(which espanso)
```

it's [here](https://espanso.org/docs/install/linux/#adding-the-required-capabilities) on the documentation

**Comment by alanef** [comment]
Thanks for your feed back.  Since I had teh issue I got a new computer and that runs KDE Neon not Debian  and it works on KDE Neon without setcap.  Perhaps a different distro settings

**Comment by AucaCoyan** [comment]
Whoops, we took a bit I'd time in between.
I'm glad to hear it worked.

**Comment by davidvv** [comment]
after running that command, nothing is better on my end... I am on ubuntu and wayland. Am I completely wrong looking here?

**Comment by AucaCoyan** [comment]
Mmm [another user](https://github.com/espanso/espanso/issues/1826#issuecomment-1941505085) and myself had the same issue about espanso service not starting up. I assumed this can be the only option (which is quite forgettable and a bit deep in the docs).
Let me reopen the issue and investigate if there is any other way to interrupt the service. Maybe we can update the log error to understand better

**Comment by davidvv** [comment]
I was working right now and suddenly espanso opened showing the welcome window, it seems to work now! El 13 feb 2024, a las 14:52, Auca Coyan ***@***.***> escribió:﻿
Mmm another user and myself had the same issue about espanso service not starting up. I assumed this can be the only option (which is quite forgettable and a bit deep in the docs).
Let me reopen the issue and investigate if there is any other way to interrupt the service. Maybe we can update the log error to understand better

**Comment by jwmurray** [comment]
I am seeing the same issue that @davidvv had been seeing.

When I run the setcap, I get this:

` sudo setcap "cap_dac_override+p" /snap/bin/espanso 
Invalid file '/snap/bin/espanso' for capability operation
`

When I run espanso start, it times out:

` sudo setcap "cap_dac_override+p" /snap/bin/espanso 
Invalid file '/snap/bin/espanso' for capability operation
`

Running Ubuntu 24.10 with Wayland.  

here is a complete run:

`
~ uname -a
Linux minis64 6.8.0-52-generic #53-Ubuntu SMP PREEMPT_DYNAMIC Sat Jan 11 00:06:25 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

[jmurray]~/.config/espanso 0 [11:38:59]
~ espanso --version
espanso 2.1.4-beta

[jmurray]~/.config/espanso 0 [11:39:29]
~ espanso service register
service file already exists, this operation will overwrite it
creating service file in "/home/jmurray/.config/systemd/user/espanso.service"
enabling systemd service
service registered correctly!

[jmurray]~/.config/espanso 0 [11:39:41]
~ sudo setcap "cap_dac_override+p" /snap/bin/espanso
Invalid file '/snap/bin/espanso' for capability operation

[jmurray]~/.config/espanso 0 [11:40:04]
~ espanso start
unable to start service: timed out
`

Your help is appreciated!
