### ISSUE TITLE
Improve description of Compilation on Windows

### ISSUE THREAD

**Issue by Elkiwa** [espanso/espanso#1784]
**Describe the bug**

Microsoft's [Visual Studio Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) comes with MSVC, but only support MSBuild-based development. The user who is already using the VS Build Tools would be surprised to know that it is not sufficient. 

**To Reproduce**
Error message during compilation
`unable to locate MSVC compiler, did you install Visual Studio?`

**Expected behavior**

**Screenshots**
![image](https://github.com/espanso/espanso/assets/11015675/f3c65fa7-8187-4ecc-be89-e0383de9ae4f)

**Logs**
None

**Setup information**
- OS: Windows 11 x64
- MSVC: Visual Studio Build Tools 2022 17.8.3

**Comment by AucaCoyan** [comment]
Yep, That's true. Thanks for the PR solving it!
