### ISSUE TITLE
Newlines in trigger

### ISSUE THREAD

**Issue by shaund** [espanso/espanso#205]
Using 
```
  - trigger: '\n"a'
    replace: '\n"A'
```
Causes `\n"a` -> `\n"A`
Instead of the actual newline. I'm trying to have it auto-capitalize the word after a quote when it's the first word on the line, like,

```
"dialog."
"more dialog."
```

But I can't just use `"a` because that would match situations like `"What they’re saying," she pressed on, "is that last night Voldemort turned up in Godric’s Hollow."`

In general I'm trying to get it to capitalize after newlines, even in cases like

```
text.
more text.
```

**Comment by federico-terzi** [comment]
Hey @shaund ,

I'm not really sure if it could fit your needs, but have you taken a look at [Word triggers](https://espanso.org/docs/matches/#word-triggers) combined with [Case propagation](https://espanso.org/docs/matches/#case-propagation)?

Let me know if that solves your problem

Cheers :)

**Comment by shaund** [comment]
I'm not sure I understand. Can you give an example? Because
```
  - trigger: '"a'
    replace: '"A'
    propagate_case: true
    word: true
```
seems to only match `"a` on its own, not words beginning with `a`. And `propgate_case` doesn't appear to be doing anything.

The behavior I'd like is for this
```
uncapitalized text.
more uncapitalized text.
"dialog."
```
to be converted automatically into this
```
Uncapitalized text.
More uncapitalized text.
"Dialog."
```

**Comment by federico-terzi** [comment]
Hey @shaund,

All right, I didn't understand your goal :) This is indeed problematic, as `\n` should work correctly and this is most probably a bug.
Which operating system are you using?

Cheers :)

**Comment by shaund** [comment]
Windows 10

**Comment by federico-terzi** [comment]
All right, thank you. I'll look into it as soon as possible and I'll get back to you once I know something :)

**Comment by malwikl** [comment]
thanks for linking the issues, didn't find this one when searching. I have the same behaviour on MacOS 12.0.1

**Comment by smeech** [comment]
3+ years later, this still doesn't work, as Espanso doesn't respond to a `\n` in a trigger. It does with `\t` but it does have to be enclosed in double-quotes, not single:
```  
  - trigger: "\t\"a"
    replace: "\t\"A"
```
however, it's been superseded by the implementation of Regex triggers, which are much more flexible, e.g.:
```
  - regex: \r"(?P<letter>\w)
    replace: "\n\"{{capital}}"
    vars:
      - name: capital
        type: shell
        params:
          cmd: "echo \"${ESPANSO_LETTER^}\""
```
I'm not familiar with the Windows equivalent of the last line, however.
I suggest we close this discussion, unless implementation of `\n` in plain triggers is planned.
