### ISSUE TITLE
Not Working in Manjaro i3

### ISSUE THREAD

**Issue by Scrymmy** [espanso/espanso#294]
Hey Guys,
So I've installed it through AUR with no problem as well as starting it with `espanso start` causes no issues. But typing for example `:espanso` deletes it but doesn't expand and after doing it once it stop working altogether yet espanso says it's still running. The log doesn't mention anything unusual. espanso -v daemon gives me this log after trying once:

13:58:25 [ INFO] espanso version 0.6.0
13:58:25 [ INFO] using config path: /home/ali/.config/espanso
13:58:25 [ INFO] using package path: /home/ali/.local/share/espanso/packages
13:58:25 [ INFO] spawning worker process...
13:58:25 [ INFO] Binded to IPC unix socket: /home/ali/.local/share/espanso/espanso.sock
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  101 (X_GetKeyboardMapping)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  39
13:59:48 [ERROR] unable to send command to IPC server

I've tried adding `use_system_agent: false` to my default.yml file which got rid of: `Error, can't connect to X11 context` but got me this one. I think it could be a problem with i3 but I don't have a lot of experience. I've had the same issue on another PC running lubuntu with i3. Reinstalling doesn't help. I'm using a German Keyboard layout if that changes anything.

Thanks in advance!

**Comment by Scrumplex** [comment]
Which AUR package are you using?

**Comment by Scrymmy** [comment]
I installed espanso-bin

**Comment by federico-terzi** [comment]
Hey @Scrymmy 

Thank you for reporting this problem. Other users experienced the same thing, it seems like the latest binary version is not playing well with Manjaro/Arch based distros.
I'll try to take a look at it. In the meanwhile, using the `espanso` package instead of `espanso-bin` should solve your problems.

Cheers :)

**Comment by Scrymmy** [comment]
Thanks, installing a different one worked!

**Comment by federico-terzi** [comment]
@Scrymmy glad to hear that! :)

**Comment by AeroNotix** [comment]
Oh #304 seems related then, I will try with the `espanso` package.

**Comment by JPUnD** [comment]
I'm running Manjaro, installed from Manjaro from scratch also running i3 and it's working just fine after the update, and i've already restarted espanso

**Comment by federico-terzi** [comment]
Thank you @JPUnD, it seems only some users are experiencing problems with the `espanso-bin` package and we still have to figure out exactly what changed between version < 0.6 and the latest ones

**Comment by matclab** [comment]
Add a similar problem (wrongly commented on #281), and using `backend: Clipboard` solved it.

**Comment by federico-terzi** [comment]
@matclab Glad you sorted that out :) I've just commented on the other thread, please ignore my message
