### ISSUE TITLE
Failed to expand with error

### ISSUE THREAD

**Issue by AeroNotix** [espanso/espanso#304]
Running with `espanso -v daemon`

ArchLinux / installed with espanso-bin package.

```
11:37:03 [ INFO] espanso version 0.6.1
11:37:03 [ INFO] using config path: /home/xeno/.config/espanso
11:37:03 [ INFO] using package path: /home/xeno/.local/share/espanso/packages
11:37:03 [ INFO] spawning worker process...
11:37:03 [ INFO] Binded to IPC unix socket: /home/xeno/.local/share/espanso/espanso.sock
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  101 (X_GetKeyboardMapping)
  Value in failed request:  0x0
  Serial number of failed request:  34
  Current serial number in output stream:  34
11:37:06 [ERROR] worker process exited with non-zero code: 1, exiting
```

When I try to expand `:date`.

**Comment by federico-terzi** [comment]
Hey @AeroNotix 
We still have to figure out why, but it seems that version >0.6.0 is not playing well with Archlinux.
For now, please use the `espanso` package instead of `espanso-bin`
Cheers :)

**Comment by AeroNotix** [comment]
ok @federico-terzi

**Comment by berdan** [comment]
Same failure on Manjaro, running 0.6.1 from the Arch AUR and having triggers like these:
```
  - trigger: ":gm"
    replace: "myemail@example.com"
```
```
2020-06-09 19:44	espanso	X Error of failed request:  BadValue (integer parameter out of range for operation)
2020-06-09 19:44	espanso	  Major opcode of failed request:  101 (X_GetKeyboardMapping)
2020-06-09 19:44	espanso	  Value in failed request:  0x0
2020-06-09 19:44	espanso	  Serial number of failed request:  29
2020-06-09 19:44	espanso	  Current serial number in output stream:  29
2020-06-09 19:44	systemd	espanso.service: Main process exited, code=exited, status=1/FAILURE
2020-06-09 19:44	systemd	espanso.service: Failed with result 'exit-code'.
```
Switching from the espanso-bin package to espanso worked.

**Comment by federico-terzi** [comment]
Thank you for the feedback @berdan. I recently updated the docs to recommend `espanso` rather than `espanso-bin` by default until we sort out this issue. Most probably it has to do with the CI build step but I didn't have the chance to take a look at it yet.

Cheers :)

**Comment by arturolinares** [comment]
I'm having the same issue in Fedora 32.

**Comment by federico-terzi** [comment]
@arturolinares I'm not much experienced in Fedora, do you use the AUR to install packages? Or have you tried with the prebuilt binary?

**Comment by AucaCoyan** [comment]
Closing the issue because of the age
