### ISSUE TITLE
Some bugs in windows 10

### ISSUE THREAD

**Issue by Masacroso** [espanso/espanso#305]
Thank you very much Federico but I was testing espanso in kubuntu 19.10 and windows 10 and I found some errors in windows (that doesn't happen in kubuntu):

1. In windows 10 you can't disable (or re-enable) espanso tapping two times the ALT key, you need to change to some other key in the configuration file, by example CTRL.

2. In windows 10 substitutions defined for strings like `{{` or `{ñ` doesn't work, however they work very fine in kubuntu.

3. In windows 10 substitutions like `CC` can be triggered by strings like `C\C` where the first `C` remains after the substitution.

**Comment by federico-terzi** [comment]
Hey @Masacroso 
Thank you for the feedback!
1. Indeed this is a bug and I was able to reproduce it, I've opened an issue specifically for that #306 
2. Another bug, but I was only able to reproduce it when using a non-US keyboard. See #307
3. I wasn't able to reproduce this one, could you give me some more detailed steps to reproduce it?

Thanks for your help :)

**Comment by Masacroso** [comment]
> Hey @Masacroso
> Thank you for the feedback!
> 
>     1. Indeed this is a bug and I was able to reproduce it, I've opened an issue specifically for that #306
> 
>     2. Another bug, but I was only able to reproduce it when using a non-US keyboard. See #307
> 
>     3. I wasn't able to reproduce this one, could you give me some more detailed steps to reproduce it?
> 
> 
> Thanks for your help :)

For the third one I just have defined a long list of replacements to type LaTeX code faster. Some replacements are the double tap of a letter in caps like `RR`, `CC` or `NN`, to be replaced by `\mathbb{R}`, `\mathbb C `, `\mathbb N` respectively. They works like a charm in kubuntu but in my windows 10 installation I can trigger them using strings like `C\C`, what produces `C\mathbb C `. This doesn't happen in kubuntu. It is not a big problem, I just discovered it accidentally.

My keyboard layout is spanish, I dont know if this mean something for this behavior.

**Comment by federico-terzi** [comment]
Thank you for the explanation @Masacroso. At this point, I think it has to do with the actual keys you press. For example, to write `CC` do you use caps lock or keep shift pressed?

When you have the chance, could you give me the complete sequence of key presses/releases you do to trigger the replacement with `C\C`? Such as:
- Key press shift
- Key press C
- Key release C
- Key press C
- Key release C
- Key release shift

**Comment by Masacroso** [comment]
> 
> 
> Thank you for the explanation @Masacroso. At this point, I think it has to do with the actual keys you press. For example, to write `CC` do you use caps lock or keep shift pressed?
> 
> When you have the chance, could you give me the complete sequence of key presses/releases you do to trigger the replacement with `C\C`? Such as:
> 
>     * Key press shift
> 
>     * Key press C
> 
>     * Key release C
> 
>     * Key press C
> 
>     * Key release C
> 
>     * Key release shift

I press `LeftShift+c` (to type `C`), and release them, now I press `AltGr+º` to type `\` and release them, and finally I press again `LeftShift+c` to type `C` again. This sequence is to type `C\C`.

To type `CC` I just hold down `LeftShift` and press in sequence `cc`, and after release `LeftShift`.

**Comment by federico-terzi** [comment]
All right, thank you @Masacroso. In the next few days I'll try to reproduce the issue and get back to you :)

**Comment by smeech** [comment]
This is quite an old Issue now. Is it still a problem?

**Comment by Masacroso** [comment]
> This is quite an old Issue now. Is it still a problem?

Nah, it was solved some years ago. I forget to close it. Now is closed, thanks :)

**Comment by smeech** [comment]
Thank you.
