### ISSUE TITLE
Espanso stop working whent hibernate linux host.

### ISSUE THREAD

**Issue by Hammer2900** [espanso/espanso#325]
When i hibernate my linux host with this command, **dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true** espanso stop handle all commands. To fast fix this issue i restart espanso and all working again. For now i use Ubuntu 18.04

**Comment by Scrumplex** [comment]
Works on my machine :tm:

No for real though. I am on KDE Plasma on Arch and suspending and resuming works.

Maybe you could provide some logs?

```
$ journalctl --user -eu espanso.service
```
or to put everything in a logfile

```
$ journalctl --user -u espanso.service > espanso.log
```

**Comment by federico-terzi** [comment]
Hey,
Thank you for reporting this @Hammer2900, this might be a non-handled edge case and it's worth investigating further.

Thank you @Scrumplex as always for your help :)

@Hammer2900 could you please post there both the output of the command @Scrumplex told you as well as `espanso log`?

Cheers :)

**Comment by Hammer2900** [comment]
Sorry for the delay, i check this issue more neatly. All this commands return empty log output. I try hibernate once more and application working... Then i restart my pc, enter the system and find that espanso not handle any commands. Espanso status return "espanso is running" all commands return empty log...

**Comment by federico-terzi** [comment]
Sorry to hear that @Hammer2900. Are you sure also `espanso log` returns an empty log? That's very unusual

**Comment by rauldipeas** [comment]
It's happening something similar here, Espanso stop working after some time...
```
-- Reboot --
jun 15 12:40:43 IdeaPad-320 systemd[1284]: Started espanso daemon.
jun 15 12:40:43 IdeaPad-320 systemd[1284]: espanso.service: Main process exited, code=exited, status=100/n/a
jun 15 12:40:43 IdeaPad-320 systemd[1284]: espanso.service: Failed with result 'exit-code'.
jun 15 12:40:46 IdeaPad-320 systemd[1284]: espanso.service: Scheduled restart job, restart counter is at 1.
jun 15 12:40:46 IdeaPad-320 systemd[1284]: Stopped espanso daemon.
jun 15 12:40:46 IdeaPad-320 systemd[1284]: Started espanso daemon.
jun 15 12:40:46 IdeaPad-320 systemd[1284]: espanso.service: Main process exited, code=exited, status=100/n/a
jun 15 12:40:46 IdeaPad-320 systemd[1284]: espanso.service: Failed with result 'exit-code'.
jun 15 12:40:49 IdeaPad-320 systemd[1284]: espanso.service: Scheduled restart job, restart counter is at 2.
jun 15 12:40:49 IdeaPad-320 systemd[1284]: Stopped espanso daemon.
jun 15 12:40:49 IdeaPad-320 systemd[1284]: Started espanso daemon.
jun 15 12:40:49 IdeaPad-320 systemd[1284]: espanso.service: Main process exited, code=exited, status=100/n/a
jun 15 12:40:49 IdeaPad-320 systemd[1284]: espanso.service: Failed with result 'exit-code'.
jun 15 12:40:52 IdeaPad-320 systemd[1284]: espanso.service: Scheduled restart job, restart counter is at 3.
jun 15 12:40:52 IdeaPad-320 systemd[1284]: Stopped espanso daemon.
jun 15 12:40:52 IdeaPad-320 systemd[1284]: Started espanso daemon.
```

**Comment by Hammer2900** [comment]
Federico

> Sorry to hear that @Hammer2900. Are you sure also `espanso log` returns an empty log? That's very unusual

Yes, log is empty. I update version to 6.2 and get the same strange behavior.

```
journalctl -u espanso.service
-- Logs begin at Thu 2020-05-28 01:34:36 EEST, end at Tue 2020-06-16 10:38:38 EEST. --
-- No entries --
```

**Comment by Scrumplex** [comment]
> Yes, log is empty. I update version to 6.2 and get the same strange behavior.
> 
> ```
> journalctl -u espanso.service

@Hammer2900  you need to use `journalctl --user -u espanso.service`. If you leave out the --user flag it only shows logs for system services, but espanso is running as a user service

**Comment by Hammer2900** [comment]
```
izot@hammer-pc:~$ journalctl --user -u espanso.service
-- Logs begin at Thu 2020-06-11 12:45:50 EEST, end at Tue 2020-06-16 08:43:37 EEST. --
-- No entries --
izot@hammer-pc:~$
```

**Comment by Scrumplex** [comment]
huh. how are you starting espanso on login? `systemctl --user status espanso.service`

**Comment by Hammer2900** [comment]
```
izot@hammer-pc:~$ systemctl --user status espanso.service
● espanso.service - espanso daemon
   Loaded: loaded (/home/izot/.config/systemd/user/espanso.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-06-16 07:38:42 EEST; 1h 19min ago
 Main PID: 10257 (espanso)
   CGroup: /user.slice/user-1000.slice/user@1000.service/espanso.service
           ├─10257 /usr/bin/espanso daemon
           └─10261 /usr/bin/espanso worker
izot@hammer-pc:~$
```
to make service i use register sub command in espanso

register      MacOS and Linux only. Register espanso in the system daemon manager.

**Comment by HaleTom** [comment]
I'm also running on a laptop (Manjaro (Arch-based) Linux) and am needing to manually run `espanso restart` quite frequently.  Subscribed, and will provide logs

**Comment by smeech** [comment]
Is this still a problem?

**Comment by HaleTom** [comment]
> Is this still a problem?

I don't believe so.  I think it can be closed.
