### ISSUE TITLE
Expansions empty on Manjaro (manual install)

### ISSUE THREAD

**Issue by owzim** [espanso/espanso#343]
I installed espanso manually via https://espanso.org/install/linux/#installing-from-the-prebuilt-release on latest and up-to-date Manjaro

Expansions take place but are empty, e.g. `:espanso`

about 3 seconds after that, a notification pops up, saying `espanso is running`

## espanso log

```
00:17:34 [ INFO] espanso version 0.6.2
00:17:34 [ INFO] using config path: /home/foo/.config/espanso
00:17:34 [ INFO] using package path: /home/foo/.local/share/espanso/packages
00:17:34 [ INFO] spawning worker process...
00:17:34 [ INFO] Binded to IPC unix socket: /home/foo/.local/share/espanso/espanso.sock
00:17:34 [ INFO] initializing worker process...
00:17:34 [ INFO] Binded to IPC unix socket: /home/foo/.local/share/espanso/worker.sock
00:17:34 [ INFO] worker is running!
00:17:34 [ INFO] watching for changes in path: /home/foo/.config/espanso
00:19:09 [ INFO] change detected, restarting worker process...
00:19:09 [ INFO] terminating worker process
00:19:09 [ INFO] initializing worker process...
00:19:09 [ INFO] Binded to IPC unix socket: /home/foo/.local/share/espanso/worker.sock
00:19:09 [ INFO] worker is running!
00:19:20 [ INFO] change detected, restarting worker process...
00:19:20 [ERROR] unable to send command to IPC server
00:19:21 [ INFO] initializing worker process...
00:19:21 [ INFO] Binded to IPC unix socket: /home/foo/.local/share/espanso/worker.sock
00:19:21 [ INFO] worker is running!
```

After a restart, the log is errorfree, but still no change in behavior:

```
00:29:21 [ INFO] espanso version 0.6.2
00:29:21 [ INFO] using config path: /home/foo/.config/espanso
00:29:21 [ INFO] using package path: /home/foo/.local/share/espanso/packages
00:29:21 [ INFO] spawning worker process...
00:29:21 [ INFO] Binded to IPC unix socket: /home/foo/.local/share/espanso/espanso.sock
00:29:21 [ INFO] initializing worker process...
00:29:21 [ INFO] Binded to IPC unix socket: /home/foo/.local/share/espanso/worker.sock
00:29:21 [ INFO] worker is running!
00:29:22 [ INFO] watching for changes in path: /home/foo/.config/espanso
```

PS: the snap installation worked but I'd rather not use snap.

**Comment by federico-terzi** [comment]
Hey @owzim,

I'm sorry you experienced this issue! Not sure why, but the prebuilt binary does not play well with Manjaro lately. Are you comfortable using the AUR? If that's the case, installing the `espanso` package should work pretty well in the meanwhile.

I'll make sure to test it out on Manjaro as soon as I get my hands on a VM. Could you please give me this info:
* Which Manjaro version are you using? (i3, KDE, Plasma, ecc..)
* Could you try running `espanso -v daemon` in a terminal and (while leaving it open) type an expansion somewhere and see if that works?

Cheers :)

**Comment by federico-terzi** [comment]
After some investigation, I concluded that this is the same issue as #304

![image](https://user-images.githubusercontent.com/20475953/85918030-74405b00-b85f-11ea-8072-d9246900f50a.png)

I'll see what we can do to fix the error

**Comment by napcok** [comment]
Manjaro user here... espanso from AUR works fine -> https://aur.archlinux.org/packages/espanso
