### ISSUE TITLE
uppercase trigger text left after expansion in xterm

### ISSUE THREAD

**Issue by Konfekt** [espanso/espanso#399]
Espanso's pasting in `xterm` using a file `~/.config/espanso/user/xterm.yml` with content

```
name: XTerm

filter_class: "XTerm"
fast_inject: false
backend: Clipboard
```

does not work:

if the trigger ends with a capital letter, say

```
  - trigger: ":TRIGGER"
    replace:  "replace" 

```

 and thus shift is pressed before expansion, then the trigger is still there before the replacement;
`:TRIGGER` is replaced by

```
:TRIGGERreplace
```

Expected: `replace`.

**Comment by Konfekt** [comment]
This is a follow up to https://github.com/federico-terzi/espanso/issues/389.

**Comment by federico-terzi** [comment]
Thanks for reporting @Konfekt, I'll keep you updated if a solution comes up :)

**Comment by smeech** [comment]
Is this still a problem? The [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) methods might help?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
