### ISSUE TITLE
Suggested documentation improvement

### ISSUE THREAD

**Issue by jamescridland** [espanso/espanso#405]
In [getting started](https://espanso.org/docs/get-started/) you might want to include the existence of the `espanso edit` command, just above the "Creating your own Match" section. As it is, the only discovery that a new user would make of this feature would be under the "Configuration" page, which you get to once you've "got started". As a suggestion, perhaps just above the "Creating your own Match" section, you might write:

> To edit your configuration quickly, use the `espanso edit` command, which will use your default command-line text editor.

(I've only now noticed it hiding at the bottom of "Creating your own Match" - this would benefit users to know _before_ they try to create their own match, not after!)

You might also want to add, for stupid people like me:

> In MacOS, the `/Library/` folder in your home directory is hidden by default in the Finder. The quickest way to get there is to open the "Go" menu in the Finder and then hold down the option key, which will temporarily display a menu item for `Library`.

Thanks!

**Comment by MuhammedZakir** [comment]
> In [getting started](https://espanso.org/docs/get-started/) you might want to include the existence of the `espanso edit` command, just above the "Creating your own Match" section. As it is, the only discovery that a new user would make of this feature would be under the "Configuration" page, which you get to once you've "got started". As a suggestion, perhaps just above the "Creating your own Match" section, you might write:
> 
> > To edit your configuration quickly, use the `espanso edit` command, which will use your default command-line text editor.
> 
> (I've only now noticed it hiding at the bottom of "Creating your own Match" - this would benefit users to know _before_ they try to create their own match, not after!)

I think it's okay. After all, editing in terminal is not something everyone is comfortable with.

> You might also want to add, for stupid people like me:
> 
> > In MacOS, the `/Library/` folder in your home directory is hidden by default in the Finder. The quickest way to get there is to open the "Go" menu in the Finder and then hold down the option key, which will temporarily display a menu item for `Library`.
> 
> Thanks!

The behavior is same for other OS too! So I added below text in 'configuration' section. It's in pull request #407. Do I need to add anything or is this okay? Btw, thanks for that shortcut! I did not know that! 😃 

> By default, configuration folder is hidden in most systems. To open it, copy path of your
configuration folder and paste it in the address bar (aka path bar) of your file manager/explorer.

**Comment by federico-terzi** [comment]
@jamescridland Thank you for the feedback! 

> (I've only now noticed it hiding at the bottom of "Creating your own Match" - this would benefit users to know before they try to create their own match, not after!)

That's true indeed. My first thought (at that time), was to introduce the `edit` subcommand later as it might make the editing process "too magical" for some users. So I'll make sure to include some more info about that command in the Getting Started.
