### ISSUE TITLE
Show a notification for a minimum number of seconds

### ISSUE THREAD

**Issue by MuhammedZakir** [espanso/espanso#412]
If 2+ notifications occur at the same time, only the last one is readable. Others only show for a very brief period. Showing a notification for a minimum of 1-2 seconds will make reading easier.

**Comment by federico-terzi** [comment]
> I am using Mac

I see, sorry for the misunderstanding. The general idea was to avoid flooding the user with unnecessary notifications (such as enabled/disabled, ecc...).

Not sure whether creating a new one for each of them would be a good idea...

**Comment by MuhammedZakir** [comment]
No problem! :-) No need for new notifications, but to make existing ones wait a bit longer, 1-1.5 secs, just enough to ~read~ guess the content.

**Comment by federico-terzi** [comment]
All right, I'll keep an eye on this issue 👍

**Comment by smeech** [comment]
Is this still a problem? In Linux, the duration of notifications is set by the system.

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
