### ISSUE TITLE
espanso crash

### ISSUE THREAD

**Issue by mattmccormick** [espanso/espanso#453]
I'm on Ubuntu 20.04 and espanso seems to crash after starting up.  In order to get it running again, I need to run `espanso unregister && espanso register && espanso start`

The logs show

```
$ espanso log
00:59:56 [ INFO] espanso version 0.7.0
00:59:56 [ INFO] using config path: /home/matt/.config/espanso
00:59:56 [ INFO] using package path: /home/matt/.local/share/espanso/packages
00:59:56 [ INFO] spawning worker process...
00:59:56 [ INFO] Binded to IPC unix socket: /home/matt/.local/share/espanso/espanso.sock
00:59:56 [ INFO] initializing worker process...
00:59:56 [ INFO] Binded to IPC unix socket: /home/matt/.local/share/espanso/worker.sock
00:59:56 [ INFO] worker is running!
00:59:56 [ INFO] watching for changes in path: /home/matt/.config/espanso
01:01:22 [ INFO] change detected, restarting worker process...
01:01:22 [ INFO] terminating worker process
01:01:23 [ INFO] initializing worker process...
01:01:23 [ INFO] Binded to IPC unix socket: /home/matt/.local/share/espanso/worker.sock
01:01:23 [ INFO] worker is running!
03:38:51 [ INFO] Received signal: 15, terminating worker
03:38:51 [ INFO] terminating espanso.
$ espanso start
Failed to start espanso.service: Unit espanso.service not found.
Error starting systemd daemon with status: exit code: 5
```

**Comment by federico-terzi** [comment]
Hey @mattmccormick,

Thanks for reporting!

> I'm on Ubuntu 20.04 and espanso seems to crash after starting up.

That's really strange, does it happen every time you try to start espanso? Also, could you please post the output of `espanso register`?

Cheers :)

**Comment by mattmccormick** [comment]
Yes it happens every time after powering up my computer.

This is the output

```
espanso service is already registered to systemd
If you want to register it again, please uninstall it first with:
    espanso unregister
```

**Comment by federico-terzi** [comment]
@mattmccormick thank you, that's interesting. Could you please follow these steps and post the output here:

1. After powering up your computer, print the service file (and post the output here) with `cat ~/.config/systemd/user/espanso.service`

2. Run `which espanso` and post the output here.
3. Then run `espanso unregister && espanso register` and repeat the first step.

These steps might help us figure out the issue :)

**Comment by mattmccormick** [comment]
Thank you for your reply.  Here's the output of those commands

```
$ cat ~/.config/systemd/user/espanso.service
[Unit]
Description=espanso daemon

[Service]
ExecStart=/snap/espanso/61/bin/espanso daemon
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
```
```
$ which espanso
/snap/bin/espanso
```
```
$ espanso unregister && espanso register
Removed /home/matt/.config/systemd/user/default.target.wants/espanso.service.
Deleted entry at /home/matt/.config/systemd/user/espanso.service
Service unregistered successfully!
Creating service entry: /home/matt/.config/systemd/user/espanso.service
Entry will point to: /snap/espanso/61/bin/espanso
Service file created correctly!
Enabling espanso for systemd...
Created symlink /home/matt/.config/systemd/user/default.target.wants/espanso.service → /home/matt/.config/systemd/user/espanso.service.
Service registered correctly!
```
```
$ cat ~/.config/systemd/user/espanso.service
[Unit]
Description=espanso daemon

[Service]
ExecStart=/snap/espanso/61/bin/espanso daemon
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
```

Also sorry, I realized I'm on Ubuntu 18.04, not 20.04 (I'm on 20.04 on my work computer)

**Comment by federico-terzi** [comment]
@mattmccormick Thanks! That's pretty strange, they look perfect... I'll investigate further

**Comment by adnion** [comment]
@mattmccormick Are you sure you don't run [wayland](https://github.com/federico-terzi/espanso/issues/287)? 
Ubuntu 18.04 LTS can use both but [Xorg is the default](https://ubuntu.com/blog/bionic-beaver-18-04-lts-to-use-xorg-by-default).
Run `echo $XDG_SESSION_TYPE` to check.

**Comment by mattmccormick** [comment]
I'm not familiar with wayland so I don't think I've ever changed to that.
```
$ echo $XDG_SESSION_TYPE
x11
```

**Comment by AucaCoyan** [comment]
Closing the issue because of the age
