### ISSUE TITLE
Document word separator option

### ISSUE THREAD

**Issue by kfeine** [espanso/espanso#493]
Hi,

Would it be possible to configure word separator characters?
For example, in French I would like to ```'``` and ```‘``` to be considered as a word separator: if ```<space>info<space>``` is replaced by ```information```, I also want ```<space>l'info<space>``` to be replaced by ```l'information```
It could be added as an option to the configuration file.

Thanks for your work!

**Comment by federico-terzi** [comment]
Hey @kfeine,

Luckily, you can! It's not documented, but you might be able to customize the word separator chars with the `word_separators` option (even though I haven't tested it much):

```yaml
word_separators: [' ', ',', '.', '?', '!', '\r', '\n', '\'', '‘']
```

in your `default.yml` file.
Let me know if that works, as otherwise I'll need to ship a fix in the next release!

Cheers :)

**Comment by kfeine** [comment]
Hi @federico-terzi,

I tried but I got several errors:
```
word_separators: [' ', ',', '.', '?', '!', '"', '…', '(', ')']
⇒ OK

word_separators: [' ', ',', '.', '?', '!', '"', '…', '(', ')', '\'']
⇒ Error parsing YAML file '/Users/bn/Library/Preferences/espanso/default.yml', invalid syntax: while parsing a flow sequence, expectd ',' or ']' at line 11 column 23

word_separators: [' ', ',', '.', '?', '!', '"', '…', '(', ')', '\r']
⇒ Error parsing YAML file '/Users/bn/Library/Preferences/espanso/default.yml', invalid syntax: word_separators[9]: invalid value: string "\\r", expected a character at line 15 column 65
```

I'm using espanso 0.7.2 on OS X 10.15.7

Thanks,

**Comment by federico-terzi** [comment]
@kfeine thank you for the investigation! The second line seems to be a YAML-related problem, as it seems that if we want to escape a single quote, we need to use another single quote and not a backslash. So your second example could become:

```
word_separators: [' ', ',', '.', '?', '!', '"', '…', '(', ')', '''']
```

Regarding the second one, could you please try adding another backslash and see if that works?

```
word_separators: [' ', ',', '.', '?', '!', '"', '…', '(', ')', '\\r']
```

Let me know if those helps :)

**Comment by kfeine** [comment]
Ok it's working for the single quote, but I still got the error with the newline:
```
word_separators: [' ', ',', '.', '?', '!', '"', '…', '(', ')', '''', '\\r']
⇒ Error parsing YAML file '/Users/bn/Library/Preferences/espanso/default.yml', invalid syntax: word_separators[10]: invalid value: string "\\\\r", expected a character at line 20 column 70```

Thanks for your help!

**Comment by federico-terzi** [comment]
@kfeine All right, thank you. I guess that I'll need to fix this behavior in the next release then :)

**Comment by andylima** [comment]
@federico-terzi @kfeine It's working for me like this:

```
word_separators: [' ', ',', '.', '?', '!', '"', '(', ')', "'", "\r"]
```

So I guess this issue doesn't need fixing…

But could you add this `word_separators` feature to the official documentation? Thanks!

**Comment by kfeine** [comment]
Hello @andylima!
I confirm your configuration is working for me too, thank you very much 👍 
Kind regards,

**Comment by andylima** [comment]
@kfeine Good to hear! Kind regards!

**Comment by nogira** [comment]
> @federico-terzi @kfeine It's working for me like this:
> 
> ```
> word_separators: [' ', ',', '.', '?', '!', '"', '(', ')', "'", "\r"]
> ```

yeah, in yaml escaped characters like `\t`, `\n`, `\r`, etc must use `"` instead of `'`
