### ISSUE TITLE
espanso emoji package not working on Linux Kwrite.

### ISSUE THREAD

**Issue by niksingh710** [espanso/espanso#495]
espanso emoji pack s not working on KDE text editor kwrite.

![espanso_big](https://user-images.githubusercontent.com/60490474/96536748-600ee680-12b2-11eb-95ca-a4f1f9f92ebe.gif)

**Comment by federico-terzi** [comment]
Hey @niksingh710,

I'm sorry you experienced this problem! What shortcut do you use to paste some text inside KWrite?
You might need a patch file to correct the paste shortcut (espanso inject text when it's ascii, but when it's unicode it pastes it using the clipboard, so if CTRL+V is not working, neither the emojis are).

Cheers :)

**Comment by niksingh710** [comment]
> Hey @niksingh710,
> 
> I'm sorry you experienced this problem! What shortcut do you use to paste some text inside KWrite?
> You might need a patch file to correct the paste shortcut (espanso inject text when it's ascii, but when it's unicode it pastes it using the clipboard, so if CTRL+V is not working, neither the emojis are).
> 
> Cheers :)
My paste shortcut is CTRL+V all triggers that I set in espanso default.yml is working fine but the emoji package that I had installed is not working.

the package I installed all-emojis by command `espanso install all-emojis`

**Comment by federico-terzi** [comment]
@niksingh710 That's unfortunate... If you copy and paste some emojis from the web, are they pasting correctly on KWrite?

**Comment by niksingh710** [comment]
@federico-terzi Yes Copying online emojis work even the custom emojis I set in default.yml also works. only package one doesn't work on kwrite.

![espanso_bug](https://user-images.githubusercontent.com/60490474/96755064-d5340600-13ef-11eb-936c-db92da955936.gif)

**Comment by federico-terzi** [comment]
@niksingh710 This is really interesting, thanks for the investigation. As a reference, this is the `all-emojis` package configuration: https://github.com/FoxxMD/espanso-all-emojis/blob/master/all-emojis/0.1.0/package.yml

I'll investigate, maybe it's related to the way the package defines emojis (as unicode codes). I'll keep you posted :)

**Comment by niksingh710** [comment]
@federico-terzi I tried one more thing I copied the whole syntax from https://github.com/FoxxMD/espanso-all-emojis/blob/master/all-emojis/0.1.0/package.yml and pasted it in default.yml to check.
It is not working then also.

**Comment by federico-terzi** [comment]
@niksingh710 Thank you. Then it's most likely an issue with the Unicode encoding used...

**Comment by niksingh710** [comment]
@federico-terzi anything i can give a try to solve the issue?

**Comment by niksingh710** [comment]
I found that all emojis package is using Ctrl+Shift+v to paste emoji and that's Y it is not working as it didn't work in vscode too.

is there any way to do changes in espanso installed packages?

**Comment by federico-terzi** [comment]
@niksingh710 Good find! Thank you

> is there any way to do changes in espanso installed packages?

Packages are no different from your usual configuration files. If you want to find the location, you can use `espanso path` and that will give you the path. Then you can simply edit them :)

**Comment by smeech** [comment]
Does changing the injection method ([`backend:` ](https://espanso.org/docs/configuration/options/#options-reference)or [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism)) help?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
