### ISSUE TITLE
Forms not Visible on Ubuntu 20.04

### ISSUE THREAD

**Issue by ajmarkow** [espanso/espanso#506]
When I try to invoke snippets that use a form, I get the following error in my logs and the form never appears. How would I fix this? I assume it is a user error on my part.

17:08:55 [ERROR] Attempt to invoke modulo even though it's not configured.

I've tried the steps to manually install modulo, as well as reinstalling espanso.  i'm on ubuntu 20.04 and lightdm is my display manager.

**Comment by federico-terzi** [comment]
Hey @ajmarkow,

I'm sorry you experienced this problem! Indeed, there is a problem with the modulo installation. Somehow, espanso is not able to find the `modulo` executable. A couple of things you could try:
* Do you see any output by entering `which modulo` in the terminal?
* Following [the instructions](https://espanso.org/install/linux/#installing-modulo) are you sure you created the link correctly? (latest `ln` command)

If you run the following in the terminal:

```
echo "layout: Hi" | modulo form -i -
```

do you see anything?

Cheers :)
