### ISSUE TITLE
[Package] AutoCorrect word list from ahk

### ISSUE THREAD

**Issue by cmcneal** [espanso/espanso#561]
Hi, I've converted an autocorrect word list from ahk over to espanso - https://github.com/cmcneal/espanso-autocorrect-package

**Comment by smeech** [comment]
Sorry about the late reply - I am trying to mop up and sort the old Issues and Discussions.

Have you considered adding the package to [Espanso hub](https://github.com/espanso/hub)?

I recognise it's been a while!
