### ISSUE TITLE
First colon is not replaced on Ubuntu 20.0.4

### ISSUE THREAD

**Issue by ohare93** [espanso/espanso#569]
I will type `:clap:` and the result I get is `:`:clap:

Happens with any expansion from the emoji addon, but not ones I make myself.

**Comment by ohare93** [comment]
Other times I have typed `:thumbsup:` and ended with `:t`:thumbsup: It seems repeatable for this one, I always end up with the extra `:t` at the start. Then if I hit backspace to cancel I sometimes get `::thumbsup:` :sob:

**Comment by federico-terzi** [comment]
Hey @ohare93,

I'm sorry you experienced this problem! Does it happen also with other matches? And most importantly, is it happening on every application?

Cheers :)

**Comment by ohare93** [comment]
Thanks mate, and no worries, just reporting for the greater good :+1: 

Hmm, now that you mention it, it works fine in a few applications.

Anki: :ok: no problems at all in this app

Firefox: not okay. Expansions for emojis rarely work without leftovers at the start. Sometimes 1, sometimes 2. 
None of my personal expansions have the extra parts leftover at the start, though they sometimes get that when I press backspace. 

Signal: ...begins an audio recording? :sweat_smile:

**Comment by federico-terzi** [comment]
> Firefox: not okay. Expansions for emojis rarely work without leftovers at the start. Sometimes 1, sometimes 2.
None of my personal expansions have the extra parts leftover at the start, though they sometimes get that when I press backspace.

I'm sorry you experienced this problem! This is a known issue, I'm working to solve it in one of the next versions. For now, you can use this patch: https://github.com/federico-terzi/espanso/issues/248#issuecomment-624258027

> Signal: ...begins an audio recording? 😅

This one is funny, thank you for sharing! You might need to create a patch here as well, this section might give you a starting point: https://espanso.org/docs/configuration/#application-specific-configurations
At that point, I would try setting the `backend: Clipboard` property in the patch and see if that helps

Cheers :)
