### ISSUE TITLE
Improve error message with non-UTF8 encoding

### ISSUE THREAD

**Issue by kahironimashte** [espanso/espanso#584]
Hi, this was kind of strange: 

On one Windows PC I used to edit files with Notepad++ and everything worked nicely. 

On a different Windows PC I used the default editor (notepad.exe) via "powershell -> espanso edit". But when I started copying the config over from the other machine via clipboard espanso failed to load the config. The problem seem to be special characters like ö ä ü ß in German. Without them the config loaded even, when editing with notepad.exe.

Error from c:/usr/kahiro/AppData/Local/espanso.log was: 

`09:26:23 [ INFO] change detected, restarting worker process...`
`09:26:23 [ERROR] Unable to reload configuration due to an error: Unable to read config file`

When I opened the config file in notepad++ and pasted in the config and saved. Everything worked fine. Even the sopecial characters.

I suppose this was some kind of encoding issue.

**Comment by federico-terzi** [comment]
Hey @kahironimashte,

Thanks for reporting this issue!

> I suppose this was some kind of encoding issue.

Yes, most likely. Espanso only supports UTF-8 encoding, so this might be the case. I'll make sure to specify a more user-friendly error message in the future!

Cheers :)

**Comment by smeech** [comment]
I have added some notes on UTF-8 coding to the documentation.
If this is still a problem, I'm happy to reopen the Issue.
