### ISSUE TITLE
Think about ways to make invalid YAML syntax errors more clear and actionable

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#589]

**Comment by leggewie** [comment]
Are external yaml-linters insufficient?  How?

**Comment by federico-terzi** [comment]
@leggewie Those might be a good option indeed, thanks for the feedback!

**Comment by smeech** [comment]
It is a pain when Espanso reports an error a few lines after the offending line, especially if there are blank lines and comments between.
[Yamllint](https://pypi.org/project/yamllint/)'s `yamllint -d relaxed %f` works fine in my Geany editor and is a little more explicit about formatting errors.
