### ISSUE TITLE
Not watching linked configs

### ISSUE THREAD

**Issue by moltar** [espanso/espanso#591]
I moved the config file to my dotfile repo, and then linked it from the original location.

Espanso stopped reloading after the config file was changed.

**Comment by federico-terzi** [comment]
Hey @moltar,

Thanks for reporting this issue! This is interesting... Does running `espanso restart` solve the problem afterward?

Cheers :)

**Comment by moltar** [comment]
No, restart does not solve. Thank you.

**Comment by TSSlade** [comment]
@federico-terzi - I have been having the same issue on `0.7.3`.

With `default.yml` at AppData/Roaming/espanso, the application works perfectly. All CLI commands work, all expansions seem to work, I get a little icon in the system tray, and I'm able to get satisfactory responses from `$ espanso log` and `$ espanso restart` and `$ espanso daemon` and the like.

With `default.yml` symlinked to another folder, the only command which elicits a response is `$ espanso help` from the CLI. Attempts to launch from the Windows Start Menu fail in that a command IS sent (and my Thycotic software sees the request, approves it, and allows it to pass), but there is no visible result. `$ espanso log`, `$ espanso restart`, `$ espanso config`, etc. from the CLI do not generate any response. Expansions fail. No espanso icon appears in the system tray, etc.

**Comment by federico-terzi** [comment]
@TSSlade @moltar Thank you guys, I'll investigate!

@moltar Are you using Windows as well?

**Comment by moltar** [comment]
I'm on the macOS Big Sur. Using soft links.

**Comment by federico-terzi** [comment]
@moltar Thanks! 
That's actually pretty strange, I've been using symlinked configs on both macOS and Windows successfully with autoreload for the past few months. I'll investigate

**Comment by moltar** [comment]
But to clarify, have you been using hard or soft links?

**Comment by federico-terzi** [comment]
@moltar I'm using soft links, but I think I understood the problem. I'm actually linking the whole directory rather than the single files. I suppose you are linking the individual files right? That might be the reason...

**Comment by TSSlade** [comment]
I was definitely linking individual files. Do you recommend linking the entire folder instead, @federico-terzi ?

**Comment by federico-terzi** [comment]
@TSSlade That's really up to your needs! I personally just link the whole espanso directory so that synchronization is very easy, but individual files should be supported as well. I'll investigate to see whether auto-reload could be possible even with the individual files :)

**Comment by TSSlade** [comment]
It definitely *used* to be. It's only the 0.7.3 tennessee where that broke for me.

**Comment by moltar** [comment]
Linking files too

**Comment by federico-terzi** [comment]
> It definitely used to be

That's interesting, as looking at the changelog nothing related to auto-reload has changed in the last few months... Do you have any idea on when it used to work?

**Comment by TSSlade** [comment]
Right up until that issue I opened regarding Thycotic - the failures I started experiencing then led me to checking for an update. I'm not sure I was on 0.7.2 before - might've been an older one. But at any right up through December everything was smooth.

**Comment by federico-terzi** [comment]
@TSSlade Thank you, I'll investigate

**Comment by TSSlade** [comment]
Just a quick update, @federico-terzi - I tried to use your suggested approach of linking the entire folder rather than individual files:

`(base) tslade@RTI-107301:~$ ln -s "C:\Users\tslade\Documents\projects\dotfiles\espanso" "C:\Users\tslade\AppData\Roaming\espanso"`

Still no joy, still misbehaved the same way as the other.

When I changed that to only symlink the `user` folder, the main (base) espanso expansions worked as expected, but the custom ones in the symlinked `user` folder did not.

**Comment by federico-terzi** [comment]
@TSSlade Interesting, thank you!

**Comment by lmcgrath** [comment]
I'm facing the same issue on macos catalina with Espanso 0.7.3:
- linking the folder to my dotfiles does not work (espanso icon indicates it's disabled) but there's nothing in the log indicating that there's a problem
- restarting espanso does not fix the problem
- creating the folder and linking default.yml does not work either

I've been browsing the code to see if anything stands out, but for now it looks like I'm not going to be able to use my dotfiles to manage the config. Espanso works with the linked folder in the previous version, though.

**Comment by lmcgrath** [comment]
Looks like it doesn't work at all even with an actual file. This is both on 0.7.3 and 0.7.2.

**Comment by federico-terzi** [comment]
@lmcgrath Thank you for the feedback! 

> The enable/disable toggle is still not right, though.

Did you see any notification related to SecureInput? Perhaps that might be the cause... Anyway, I'll investigate :)

**Comment by jonnywilliamson** [comment]
Evening. 

Just wanted to add some information here.

I have windows PC and Macbook with latest Espanso 2.1.2-alpha installed on both. I've setup sync using dropbox, with `<dropbox>\espanso` as the folder to keep the config files in.

I've done one thing very slightly differently, I didn't want to sync my `config\default.yml` file because I wanted to use 
`toggle_key: RIGHT_CMD` on my mac and
`toggle_key: RIGHT_CTRL` on my PC, 

and so I wanted each machine to use it's own `config\default.yml` to set that up (is there any other way to do this?). All I wanted to sync was the `match\*.yml` files.



On the MAC I made a `symlink` as follows: `ln -s ~/Dropbox/espanso/match ~/Library/Application Support/espanso/match`
On the PC I made a junction as follows: `mklink -j c:\espanso\match c:\dropbox\espanso\match`

Restarted espanso on both machines, and everything is working fine. Both machines can read their own `config file`, and the synced `match files`.

However! NOW any changes in the `match folder` never get detected. If I edit `<dropbox>\espanso\match\base.yml` and save it, the new changes are not automatcially picked up. They were BEFORE I made the sym links.

BOTH config files  have `auto_restart: true` set correctly.

If I manually restart espanso, then the changes ARE detected and work fine.

It's as if espanso can't monitor file changes through a symlink.

I hope that's enough information to help in finding the bug or discovering if it's even possible.

Thank you very much!

**Comment by federico-terzi** [comment]
Hey @jonnywilliamson,

Thank you for the investigation! That's definitely helpful, I'll investigate further.

> so I wanted each machine to use it's own config\default.yml to set that up (is there any other way to do this?). All I wanted to sync was the match\*.yml files.

Regarding this use case, if you are using the new v2 there's another possible setup that avoids symlinks completely, by using the new [include and exclude rules](https://espanso.org/docs/next/configuration/include-and-exclude/).

Note: at the time of writing this, I realized that the following setup does not pick up changes automatically, so it wouldn't solve this problem (though it would provide a slightly cleaner solution once solved). I've opened an issue for that: https://github.com/federico-terzi/espanso/issues/923

This is an high-level overview:
* Create a folder on Dropbox containing the match files you want to use, let's call it `/path/to/Dropbox/espansomatches`
  * This folder will contain the _match files_, so `base.yml` and so on (not the `default.yml`).
* Then, inside each machine's `$CONFIG/config/default.yml` file, you can define the include rules with the absolute paths and glob patterns:

```yaml
extra_includes:
  - "/path/to/Dropbox/espansomatches/**.yml"
```

Keep in mind that the `$CONFIG/match/base.yml` file should still be present. You can leave it empty though

Cheers :)

**Comment by jonnywilliamson** [comment]
@federico-terzi 

Thanks for replying so fast. Yes I totally get that high-level overview of the include and exclude rules and I absolutely love the idea. That's much cleaner and simplier (for my brain anyway) that having to create symlinks etc. Although to be fair it wasn't that hard either.

I will definiately switch to this method if you manage to crack the file monitoing issue. I have a very simple setup, `config\default.yml` for each computer and about 5 match files that I always want loaded - so your suggestion is perfect.

I'll subscribe to #923 !

Thank you and happy new year to you too!

**Comment by federico-terzi** [comment]
@jonnywilliamson Sounds great! I'll keep you posted :)

**Comment by smeech** [comment]
This is now quite an old issue. Is this still a problem with the new version?

**Comment by AucaCoyan** [comment]
No response, closing!

**Comment by wezm** [comment]
It would be good if this could be reopened. The issue still applies. My config looks like this:

```
.
├── config
│   └── default.yml
└── match
    ├── base.yml
    ├── packages
    └── private.yml ⇒ /home/wmoore/.dotfiles/private/espanso/private.yml
```

If I edit `private.yml` the config is not auto-reloaded.

**Version:** espanso 2.2.1

**Comment by AucaCoyan** [comment]
Allright! Let us investigate what's happening and we will come back with either questions or a solution 😄

**Comment by wezm** [comment]
Hmm it is possible that the workaround in https://github.com/espanso/espanso/issues/591#issuecomment-1003544525 could work for me. I'll have to try that out.

**Comment by AucaCoyan** [comment]
Hi wez! Could you try the workaround you mentioned? did it work?

**Comment by wezm** [comment]
> Hi wez! Could you try the workaround you mentioned? did it work?

I have now tried it but it only partially works. I have a working configuration without resorting to a symbolic link but auto-reload does not work for the imported file. It does however reload if I re-save `private.yml`, which has the `import` in it. Previously when this was a symbolic link it would not reload in that case either.

My structure:

```
espanso
├── config
│   └── default.yml
└── match
    ├── base.yml
    ├── packages
    └── private.yml
```

Content of `private.yml`, which is importing this path: `/home/wmoore/.dotfiles/private/espanso/private.yml`:

```yaml
imports:
  - "../../../private/espanso/private.yml"
```
