### ISSUE TITLE
vowel accent

### ISSUE THREAD

**Issue by PietroMB** [espanso/espanso#592]
Hi all, I've an issue with accent in espanso,

I'm running on Ubuntu 20.10 on X11
my ~/.config/espanso/default.yml looks like this

```
matches:
  - trigger: "é"
    replace: 'è'
```

but when I type é the output is this this: ®.

Any suggestion? Thx

**Comment by federico-terzi** [comment]
Hey @PietroMB,

I'm sorry you experienced this problem! What keyboard layout are you using?

Cheers :)

**Comment by PietroMB** [comment]
Hi, I'm using English (int, with AltGr dead keys) layout, and I've a ANSI layout real keyboard.
![Schermata da 2021-02-16 15-10-38](https://user-images.githubusercontent.com/15186555/108074166-2d5eda00-7069-11eb-9e56-cbae978f346e.png)
Thx for support @federico-terzi

**Comment by federico-terzi** [comment]
Thanks! The upcoming version (#594) might solve this problem, so your best bet is to wait for that :)
In the meantime, you could also try with `force_clipboard: true` option:

```yaml
matches:
  - trigger: "é"
    force_clipboard: true
    replace: 'è'
```

Cheers :)

**Comment by PietroMB** [comment]
I've tried but same error, I'll waiting for the next release np

PS sorry for the missing tags and congratulations for the work is really good!

**Comment by federico-terzi** [comment]
@PietroMB I'm sorry about that! And thanks for the kind words :)
