### ISSUE TITLE
form variable type:choice GUI failure when controlled with keyboard

### ISSUE THREAD

**Issue by nicholasdunbar** [espanso/espanso#599]
DESCRIPTION:
GUI driven for works when using mouse but fails when one tries to control the form with key strokes

OPERATING SYSTEM:
mac os 10.11.6
application textedit

REPRODUCTION STEPS:
1. turn on keyboard control in system preferences -> keyboard -> shortcuts click Full Keyboard access all controls

2. update config file on expanse
```- trigger: ":sign\t"
    form: |
      {{choice}},
      - {{name}}
    form_fields:
      choice:
          type: choice
          values:
            - Love
            - Sincerely
            - 🐝 well
            - Hope you are doing well
      name:
        type: choice
        values:
          - Nick
          - Nicholas
          - Nicholas Dunbar
          - Nicholas G. Dunbar
          - Nicholas Dunbar - ACE Certified Health Coach
```

3. In textedit type :sign and hit tab
4. down arrow key to select "🐝 well", hit space 
5. tab
6. down key to Nicholas Dunbar - ACE Certified Health Coach
7. hit space
8. hit tab to focus the submit button
9. hit space to enter submit
10. go to step 3 and repeat 2 more times

EXPECTED RESULT:
```
🐝 well,
- Nicholas Dunbar - ACE Certified Health Coach
🐝 well,
- Nicholas Dunbar - ACE Certified Health Coach
🐝 well,
- Nicholas Dunbar - ACE Certified Health Coach
```
ACTUAL RESULT:
```
🐝 well,
- Nicholas Dunbar - ACE Certified Health Coach
🐝 well,
- Nicholas Dunbar - 
🐝 well,
- Nicholas Dunbar -  Coach
```

**Comment by federico-terzi** [comment]
Hey @nicholasdunbar,

Thanks for reporting this issue! As soon as I get my hands on a mac I'll investigate :)
PS: any chance you could include a screen recording of this happening?

Cheers :)

**Comment by nicholasdunbar** [comment]
I'll try to get to it later. In the mean time the work around is to use ctrl+enter to submit the form.

**Comment by smeech** [comment]
This is now a rather old issue. 
Is it still a problem with the current version, and, if so, have the `backend:` global or `force_mode:` for individual trigger, options been fully explored?
