### ISSUE TITLE
Umlaut replacement not working in Signal Linux Client 

### ISSUE THREAD

**Issue by sebkouba** [espanso/espanso#621]
Not sure this is worth looking into but I thought I'd report it. Using the signal linux client, my replacement for my email address works everywhere but my script that replaces 'a%' with 'ä' works in the search box but it doesn't work in chat message box. Typing 'llg' expands to my email but 'a%' does not turn into 'ä' like it otherwise does.

When I type the letter 'a' it shows up and as soon as I hit the '%' the 'a' disappears but isn't replaced with 'ä'. It only deletes the 'a'. I have no idea what's going on here.

I'm using v 0.7.3 on Xubuntu with i3. Signal is v1.40.1

```
 - trigger: "a%"
   replace: "ä"
```

Cheers

edit: just noticed the desired latter ends up in the clipboard but the pasting mechanism seems to get hijacked by Signal...

**Comment by federico-terzi** [comment]
Hey @sebkouba,

Thanks for reporting this issue! 

>  just noticed the desired latter ends up in the clipboard but the pasting mechanism seems to get hijacked by Signal...

I've experienced this myself with other editors, so it's not related to Signal in particular. With the new version (#594) we might be able to work around this issue, so your best bet is to wait for a while :)

Cheers :)

**Comment by smeech** [comment]
Is this the problem with non-English keyboards, or is it soluble by changing the `backend:` globally or via `force_mode:` for individual triggers?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
