### ISSUE TITLE
Add option to discard the trigger character

### ISSUE THREAD

**Issue by shaneknysh** [espanso/espanso#626]
I use 
`"eml" -> "email address"` 
but when triggered with space I get 
`"eml" -> "email address "` 
That extra space at the end causes a fight between me and  the backspace to undo feature when all I want to do is remove the trigger character.

**Comment by federico-terzi** [comment]
Hey @shaneknysh,

Thank you for the feedback! Not sure how we can solve it exactly, are you using the `word` option?
In the meanwhile, a little trick you could use is pressing the "shift" key before the backspace, which disables the undo feature for that match

Cheers :)

**Comment by joonro** [comment]
I'm having the same issue. I think it would be great to have an option to suppress the trigger character (space) when using the `word` option (I think that is how it works with autohotkey). Anyway, thanks for the great utility!

**Comment by federico-terzi** [comment]
@joonro Sounds good, thank you! I'll investigate, it shouldn't be too hard to implement, although I can't give you any estimate date :)

**Comment by smeech** [comment]
Is this still a problem with the recent release?

**Comment by shaneknysh** [comment]
Yes

**Comment by smeech** [comment]
Thank you for replying after so long!
Does:
```
  - trigger: ":eml "
    replace: email address
```
meet your needs, or have I misunderstood the problem?

**Comment by shaneknysh** [comment]
No.

Adding a space to the trigger doesn't remove the trigger character after triggering it only adds an additional character to the precursor

"eml " -> "email address"
when triggered with space I get
"eml " -> "email address "

"eml " -> "email address "<--- this space at the end is the issue. 

If I am filling in a contact form this is the desired text entry
```
typed text | desired result
---------------------------
 tab       | enter email field
 eml       | "eml" entered into email field
 space     | "eml" is expanded to "email address"
 tab       | leave email field
```

actual text entry
```
typed text | desired result
---------------------------
 tab       | enter email field
 eml       | "eml" entered into email field
 space     | "eml" is expanded to "email address "
 tab       | leave email field, email address displays an error as an invalid email address
```

actual text entry
```
typed text | desired result
---------------------------
 tab       | enter email field
 eml       | "eml" entered into email field
 space     | "eml" is expanded to "email address "
 backspace | "email address " is reverted to "eml"
```

work around text entry
```
typed text | desired result
---------------------------
 tab       | enter email field
 eml       | "eml" entered into email field
 space     | "eml" is expanded to "email address "
 shift     | cancels the revert option
 backspace | "email address " is corrected to "email address"
 tab       | leave email field
```

**Comment by smeech** [comment]
Thank you. That's very helpful. 

It's not what happens here with the code I posted, or if I use `- regex:` instead of `- trigger:`:
`":eml "` gets replaced by `"email address"` with _no_ space suffix, which is what _should_ happen, and I think is what you want?

I presume your contact form is in a specialist program? Does the same space suffix occur if you try the trigger in a plain text editor?

Have you tried changing the backend using the [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) trigger options?

**Comment by shaneknysh** [comment]
I will test again later but I was still getting the additional space this morning. 

What mode are you using? I think my config is set to keys but I can't check right now.

**Comment by smeech** [comment]
> I will test again later but I was still getting the additional space this morning.
> 
> What mode are you using? I think my config is set to keys but I can't check right now.

My (Linux Mint Xfce) default is `Clipboard` except for my terminal (`Auto`), and LibreOffice Calc (`Inject`).
To save repeatedly editing `default.yml`, the `force_mode:` options are useful for testing individual triggers to determine if an app-specific configuration, or global change to `default.yml`, might be helpful.

**Comment by shaneknysh** [comment]
I will test with clipboard and update.

I wrote my config and replacements long before individual trigger option was added.

**Comment by shaneknysh** [comment]
Changed my config from "keys" to "clipboard" to "auto" and I still get "email address "

also tested before and after updating from 2.1.x to 2.2.1 and I still get the trigger character.

does case matter? Keys vs keys etc

**Comment by smeech** [comment]
`force_mode:` accepts `clipboard` or `keys`. I haven't tried changing the case. For `backend:` it's `Clipboard`, `Inject` or `Auto` but it's only worth changing this global setting if you find a general change beneficial.
You could try generating an intermediate `echo:` variable for the email address before outputting the variable - I've seen that help once.
What's your OS and the program concerned?
Do you _always_ get the extra spaces (in other editors/word-processors/terminal, etc.)?

**Comment by shaneknysh** [comment]
I always get the trigger character its not an space being injected

```
typed text | result
---------------------------
 space     | "eml" is expanded to "email address "
 ,         | "eml" is expanded to "email address,"
 .         | "eml" is expanded to "email address."
```

The trigger character is inserted by design but there are cases when it is not wanted

**Comment by smeech** [comment]
Only if you're using `word: true` should it leave the `word_separator` (it's useful for entering triggers within blocks of text) but if you're not (and you don't need it for a single-field input) you shouldn't. I'd need to see your actual trigger code.

**Comment by shaneknysh** [comment]
default.yml

```
# Automatically generated by espanso migration tool
# Original file: default.yml

backend: Clipboard
toggle_key: RIGHT_ALT
auto_restart: true
undo_backspace: true
```

contact.yml
```
matches:
  - trigger: eml
    replace: email address
    word: true
```

**Comment by smeech** [comment]
If you take out `word: true` it should work as you want, but you may wish to add a disambiguation character on the beginning of your trigger to prevent it expanding in general text (not that there are any words in common use that ChatGPT could come up with in this instance).

**Comment by shaneknysh** [comment]
I have tested word: true / false but that was quite some time ago.

I don't want to turn off undo I use it when I get an expansion I don't want like if I am typing eml in this response.

Where did you use `-regex` I'm not familiar with that setting?

**Comment by smeech** [comment]
I didn't use [`- regex:`](https://espanso.org/docs/matches/regex-triggers/) here but did mention that it works.
Apologies for mentioning `undo_backspace` - I misread your code. When I noticed, I edited my addition in the GitHub Issue thread, but you won't have seen it if you're relying on the emails.

**Comment by stewcam** [comment]
Adding a space character works for me. However, I prefer to stick with `word: true` and add `$|$` at the end of the replacement text.

**Comment by shaneknysh** [comment]
This still keeps the trigger character but moves the cursor to be in front
of the trigger character

So instead of
`replaced word |`
you get
`replaced word| `

so instead of having to hit [backspace] to remove the trigger character you
need to hit [delete]

**Comment by stewcam** [comment]
@shaneknysh Yes, although it does allow you to avoid that fight between backspace and undo!

**Comment by stewcam** [comment]
@shaneknysh If you want to avoid the trailing space altogether you add `$` to your word separators and then enter your replacement text as ending in `$|`. On triggering with `$` you should then get the desired replacement text without either `$|` or a trailing space (tested).

**Comment by shaneknysh** [comment]
It's not a trailing space it's a trailing replacement character.

**Comment by stewcam** [comment]
@shaneknysh Yes, but you should find that the replacement character (word separator) `$` will combine with the replacement text ending in `$|` to give you what you want. The strings `$|` and `$` eat each other when they meet.

**Comment by shaneknysh** [comment]
Still occuring.

**Comment by smeech** [comment]
I think Espanso is working as it should, and you may need to adjust your code, along the lines discussed, to make it do what you want. Espanso doesn't have trigger characters, by the way.

**Comment by shaneknysh** [comment]
I'm glad espanso doesn't have trigger characters. 

How would you like me to refer to the character I type to trigger a replacement with espanso?

You can close this as won't fix or working as intended but it is not fixed. The behavior is still present. The solutions presented are workarounds and do not repress the inclusion on the "character typed that triggers a replacement."

the $| "fix" only works if the "character typed to trigger replacement" is a space and I found it did not work at all in online forms asking for email address.

**Comment by smeech** [comment]
I think we're not understanding one another, as I still don't see what needs to be fixed.

As far as I can see, Espanso doesn't have any characters that trigger a replacement. It works by continually monitoring all text typed, and implementing a replacement if it encounters a sequence of characters that match the entirety of a `trigger:` or `regex:` value.

May I suggest you pose the question on [Discord](https://discord.gg/4QARseMS6k), where there are generally more users available to discuss such issues?

**Comment by shaneknysh** [comment]
Leave it fixed, reopen it, I no longer care. I'm moving on either with espanso or another solution.

If you want to understand the problem go to a web form and in place of your email address put in your email address and a space.

**Comment by ernstki** [comment]
Hi, all.

I'm a long-time user of TextExpander on macOS and I'm familiar—at least conceptually—with the behavior @shaneknysh is aiming for here.

The workaround for me was exactly as @smeech described in [this comment above](https://github.com/espanso/espanso/issues/626#issuecomment-1941872977): a literal space at the _end_ of the `trigger` as part of a quoted string.

```yaml
matches:
  - trigger: ":eml "
    replace: email address
```

My `~/.config/espanso/config/default.yml` doesn't have anything special in it:

```yaml
toggle_key: "OFF"
search_shortcut: ALT+SHIFT+SPACE
undo_backspace: false
```

As far as I can _tell_—and I've been using Espanso for a few years now—this re-creates the behavior I expected coming from TextExpander, where that behavior is described as "Expand abbreviations: at delimiter (abandon delimiter)."

As we learned here, though, Espanso doesn't _have_ the notion of a "delimiter" or "trigger character"—at least not in the out-of-the box setup. It performs the expansion as soon as the last character of the `trigger` hits the input buffer. That also confused me at first, having used different snippet expanders in the past.

![Screenshot of the TextExpander settings, showing the 'Expansion' tab, with the settings for expansion at a delimiter highlighted with a bright-colored box](https://github.com/user-attachments/assets/87878964-aea6-4017-9013-d725ab982837)
![Screenshot of the TextExpander settings, showing the 'Expansion' tab, having clicked on the 'Set Delimiters…' button, with "pill"-style UI elements showing 'tab' and 'space' having been chosen from the list of possible delimiter keys](https://github.com/user-attachments/assets/317d9ab2-c748-42b0-8735-ffdb780472a5)

I had no desire to look beyond the quick-and-dirty solution of adding a trailing space to the `trigger`, into matching _either_ space _or_ a tab as the "trigger character," although I expect this is possible with newer versions of Espanso.

**Edit**: To add clarity, I did (more) carefully re-read the issue, and it looks like from [this comment](https://github.com/espanso/espanso/issues/626#issuecomment-1942071274) @shaneknysh _did_ try adding an additional space character to no apparent avail. Just wanted to confirm that the suggested workaround of adding a space to the `trigger` _does_ appear to work, with a relatively recent Espanso from the 2.x series, at least on the two OSes I use (Mac and Linux).

**Comment by ernstki** [comment]
Just to add, I _believe_ that the crucial misunderstanding that propelled this whole issue thread was that **Espanso triggers immediately once the last character of `trigger` has entered the keyboard buffer**, which _is_ a very, very relatable misunderstanding, having come from some other snippet expander software.

It doesn't _have_ a notion of a "trigger character" in the sense that that phrase is being used here, at least not in the out-of-the-box setup. I'm not a pro at Espanso's configuration format, though, so I don't rule out some feature flags that I'm just not aware of.

**Comment by shaneknysh** [comment]
I reinstalled Espanso and tested

The expansion is not triggered for me until the next character is typed AFTER the match word is completed. I only tested the last config file I had I did not test with the regex, with an added space, or any of the above fixes I have already tested.

```
espanso version: 2.1.6-beta
system info: Windows v10 (22631) - kernel: 22631

tested in VSCodium, Notepad, and the GitHub comment box
```

![image](https://github.com/user-attachments/assets/823991c9-5763-4588-8e86-56f1127ef225)

I've unsubscribed and will no longer be seeing any responses nor will I be testing further releases or suggested fixes.

**Comment by ernstki** [comment]
Well, bummer. Guess we'll never get to the bottom of that one.

**Comment by AlbatorLaho** [comment]
I don't know for sure what the OP's problem was/is... but I _think_ I'm having a similar issue/experience.

When using a match with `word: true` then Espanso uses a character from `word_separators` to "trigger" the expansion.

So a match with `trigger: "eml "` and `word: false` should work as "expected". But this requires the character at the end of the trigger, instead of one from `word_separators`.

So what I think the OP wanted (and what I want), is when a match uses `word: true`, that whatever character is used from `word_separators` to "trigger" the match, should (optionally) be removed along with the rest of the `trigger`, when it gets replaced.

**Comment by shaneknysh** [comment]
Good luck getting a working solution.

I can recommend Breezy (now abreevy8 https://abreevy8.io/) as an alternative but I am still working through other OSS options.

**Comment by AlbatorLaho** [comment]
It's not annoying enough for me to move to something else, that isn't OSS... (and free)
Plus I'm using MacOS, and it looks like abreevy8 is Windows only.

**Comment by shaneknysh** [comment]
If you don't mind renting software Text Expander was one of the OG offerings.

**Comment by AlbatorLaho** [comment]
Yeah, I'm sure there's alternatives... but I think this is something that should easily be fixed in Espanso. (I can't think of any technical limitations as to why it couldn't be implemented)

I wouldn't totally be against trying to implement this myself, but I've not used Rust before, nor have it installed.

**Comment by smeech** [comment]
> So a match with `trigger: "eml "` and `word: false` should work as "expected". But this requires the character at the end of the trigger, instead of one from `word_separators`.
> 
> So what I think the OP wanted (and what I want), is when a match uses `word: true`, that whatever character is used from `word_separators` to "trigger" the match, should (optionally) be removed along with the rest of the `trigger`, when it gets replaced.

A Regex trigger provides this:
```yml
  - regex: eml\W
    replace: something@something.com
```   
if needed, although one would need a longer Regex to limit the matches to the Espanso default list of word terminators.

**Comment by AlbatorLaho** [comment]
Ok, that does not ensure that `elm` is a "word" on its own, and not just the end of another word.
To get that, you have to do:
```yaml
# works, but not at beginning of lines
- regex: (?P<mark>\W)test\W
  replace: "{{mark}}something"

# seems to trigger fine, but the "expanded" text is ¿empty? at beginning of lines...
- regex: (?P<mark>(^|\W))test\W
  replace: "{{mark}}something"
```
Also, this (obviously) doesn't respect `word_separators`, and to do that, would require manually implementing that regex in each match that you want to behave in this way.

I personally don't understand why this would be hard to implement... should nearly be as easy as adding a config option for it, and an if statement?
