### ISSUE TITLE
newlines are stripped off from replacement text when typing in MS Teams

### ISSUE THREAD

**Issue by diabolic-preacher** [espanso/espanso#642]
a sample entry like
\- trigger: ;br
   replace: Best Regards,\nDP

or even..

\- trigger: ;br
   replace: |
      Best Regards,
      DP

when triggered in MS Teams  chat window, gets pasted as **Best RegardsDP** and gets sent as well without giving me a chance to correct the message.

My typing including repetitive stuff happens mostly in MS Teams and I was hoping espanso would fit right in. 
An alternate software I was using before learning about espanso, added newlines correctly (it has GUI so I dunno if they use \n) but did not add the last return to send the message,

p.s. the text pastes correctly in other apps like notepad.exe

OS Windows 10 (1909)

**Comment by federico-terzi** [comment]
Hey @diabolic-preacher,

Thanks for reporting this issue! The injection system is currently being rewritten, so things will change in the future. In the meanwhile, you might want to use the `force_clipboard: true` option or enable the Clipboard backend for MS Teams (you can find an example of patch described in [this thread](https://github.com/federico-terzi/espanso/issues/544)).

```yaml
- trigger: ;br
  force_clipboard: true
  replace: Best Regards,\nDP
```

Cheers :)

**Comment by diabolic-preacher** [comment]
thanks for the tip, i will refer to the other thread and find out what is possible.
