### ISSUE TITLE
Issues when using Synergy/Barrier

### ISSUE THREAD

**Issue by CubeTheThird** [espanso/espanso#666]
I currently use [Barrier](https://github.com/debauchee/barrier) as a virtual KVM, allowing me to share my mouse and keyboard with a different PC virtually.
I want to disable espanso from being triggered when on the other PC, as the text replacements do not work properly there anyways. When running the detection, this is the output I receive:

```
Detected change, current window has properties:
==> Title: ''
==> Class: ''
==> Executable: ''

XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
...
```

I also tried applying a filter for window title to ensure it is not blank, but this does not appear to work.

**Comment by federico-terzi** [comment]
Hey @CubeTheThird,

Thanks for reporting this issue! This might be tricky to solve, as the detect command can't extract any information about that application... I'm wondering if you could figure out a way to extract that information for example using `xdotool`, in particular if you can "read" some properties (such as title, class or exec) of barrier when it's currently focused

**Comment by CubeTheThird** [comment]
So I've played around a bit with xdotool, and the only command that seem to return anything besides an error was with the `getwindowfocus` option. I am however not certain to which window the ID belonged.

As a possible solution, might we block espanso from executing when window properties are not being returned? Personally I would not expect it to behave normally outside the regular desktop experience in any case.

**Comment by federico-terzi** [comment]
@CubeTheThird I see, thank you for the investigation!

> As a possible solution, might we block espanso from executing when window properties are not being returned? Personally I would not expect it to behave normally outside the regular desktop experience in any case.

Have you tried setting `filter_class: "^$"`? I haven't personally tested it, but it might work

**Comment by CubeTheThird** [comment]
Yes, I have tested that filter, and it has no effect.

**Comment by federico-terzi** [comment]
@CubeTheThird All right, thank you! Then I don't have any other idea yet... I'll think about it

**Comment by smeech** [comment]
This is a rather old Issue now. Is this still a problem with the current release?

**Comment by CubeTheThird** [comment]
I have no idea, and unfortunately I can't test currently. I haven't been using KVM software in some time now.

**Comment by smeech** [comment]
Thank you very much for replying. I'll close the issue for now.
