### ISSUE TITLE
: appended to edge browser

### ISSUE THREAD

**Issue by bambooyip** [espanso/espanso#685]
Hi,

I'd like to say thank you to your great work on espanso first. However, recently, I encounter some incompatibility using espanso on edge. It always appends : on all my triggers but only happens on Edge.

Thanks and regards,
Ben

**Comment by federico-terzi** [comment]
Hey @bambooyip,

I'm sorry you experienced this problem! Could you please tell me:
1. What operating system are you using?
2. Where are you trying to insert the snippets? (address bar, inside a page, etc)

Cheers :)

**Comment by andrea-prado** [comment]
Hi, 
I have the same issue/ a similar issue  on firefox (address bar and inside the page) and also on libreOffice, I use linux mint btw.
So it goes like this
I type ```":espanso"``` and get ```:espHi there!``` or sometimes ```:eHi there!``` or rarely ```:Hi there!```

I would like to add that I find espanso pretty great so far. Thanks for the Software!!
Best Regards,
Andrea

**Comment by federico-terzi** [comment]
Hey @andrea-prado,
Thank you for the feedback! Please take a look at these issues for a workaround https://github.com/federico-terzi/espanso/issues/248#issuecomment-624258027 https://github.com/federico-terzi/espanso/issues/130#issuecomment-559881358

The need for these workarounds should go away as #310 is implemented :)

**Comment by AucaCoyan** [comment]
Hi! fast-forward to the present. I tested `:espanso` and edge responded `:Hi there!` in the address bar, but in most webpages responds `Hi there!` correctly
I could not reproduce the other cases `:espHi there!` or `:eHi there!`

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue.
