### ISSUE TITLE
problem when fast triggering expansions

### ISSUE THREAD

**Issue by as3ii** [espanso/espanso#686]
when _fast triggering expansions_ some character may be overwritten or miss
For example, when using:
```
matches:
    - trigger: "'"
      replace: "'$|$'"
```
and quickly typing `'`, some of the `'` may disappear

some info:
- espanso version: 0.7.3
- OS: ArchLinux

**Comment by as3ii** [comment]
I'm using bspwn as window manager and yes, could be related. Sorry for opening another issue, I hadn't seen that one

**Comment by federico-terzi** [comment]
@as3ii No problem! This is slightly different, as it doesn't seem to be related to word triggers
