### ISSUE TITLE
espanso won't start on Ubuntu 20:  Could not initialize linux context, error: -2

### ISSUE THREAD

**Issue by zopyx** [espanso/espanso#694]
What is this error about when trying to start espanso on Ubuntu 20?

```
14:32:42 [ INFO] espanso version 0.7.3
14:32:42 [ INFO] using config path: /home/ajung/.config/espanso
14:32:42 [ INFO] using package path: /home/ajung/.local/share/espanso/packages
14:32:42 [ INFO] spawning worker process...
14:32:42 [ INFO] Binded to IPC unix socket: /home/ajung/.local/share/espanso/espanso.sock
14:32:42 [ INFO] initializing worker process...
14:32:42 [ERROR] Could not initialize linux context, error: -2
14:32:42 [ERROR] worker process exited with non-zero code: 10, exiting

```

**Comment by federico-terzi** [comment]
Hey @zopyx,

I'm sorry you experienced this problem! Looking at the log, it seems that espanso fails to initialize a X Record Extension context (which should be installed by default on ubuntu). A couple of questions:

* What desktop environment are you using?
* Are you under Wayland?

Cheers :)

**Comment by zopyx** [comment]
This is Ubuntu 20.04 LTS with the KDE default installation. No particular idea about the underlying window manager stuff.

**Comment by federico-terzi** [comment]
@zopyx I see, thank you. I'll investigate and get back to you if I discover something :)

**Comment by bayronbarquero** [comment]
Mine was working but stopped last week. Failing with the same error. 
I'm using the same Ubuntu 20.04 LTS with the KDE default installation, X11.

**Comment by smeech** [comment]
Is this still a problem, with current editions of Ubuntu & Espanso?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
