### ISSUE TITLE
Notifications with invalid title stuck on Linux login screen

### ISSUE THREAD

**Issue by tkainrad** [espanso/espanso#697]
I am using Ubuntu and experienced a minor issue with how notifications are handled.

They are displayed fine when they are triggered:

![image](https://user-images.githubusercontent.com/7394822/122540273-c3f7d380-d028-11eb-93ed-d805edf0c9d6.png)

However, this is how they look like on the login screen:

![espanso-notifications](https://user-images.githubusercontent.com/7394822/122550057-7f256a00-d033-11eb-96f5-6e4262066abd.jpeg)

I have not been able to get rid of them, except via restarting the computer. Other software that sends notifications doesn't seem to have this problem. So, I guess there is some minor problem with how notifications are created.

---
PS: Thanks for this awesome software!

**Comment by federico-terzi** [comment]
Hey @tkainrad,

Thanks for reporting this issue! Not sure how we could solve it yet, but in the meanwhile, you could add this options:

```
show_notifications: false
```

to your `default.yml` file to avoid them entirely

Cheers :)

**Comment by smeech** [comment]
Is this still a problem, with current editions of Ubuntu & Espanso?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
