### ISSUE TITLE
Espanso not working inside Windows virtual machine (VMware on macOS)

### ISSUE THREAD

**Issue by stfnr** [espanso/espanso#716]
I wanted to use espanso inside a Windows virtual machine (VMware) running on a macOS host. 
Somehow, I was not able to get it working. The pasting/injection somehow does not seem to work, but some backspace action are performed after the extension. 

I tried both backends (clipboard, inject) without success. They appear to have the same behavior. 

Any ideas how to get this to work? 

Software versions running: 

espanso 0.7.3 running on host
Windows 10 (guest)
macOS 10.15.7 (host)
VMware 11.5.7

PS: Thanks for creating, maintaining and sharing this great tool! Keep up the awesome work!

**Comment by federico-terzi** [comment]
Hey @stfnr,

I'm sorry you experienced this problem! Unfortunately, this is a known issue with VMs and Remote desktop software (see #640). There might be a way to make it work, but it will require a non-trivial implementation of an alternative macOS and Windows backend. It will probably happen in the future, but I don't have an ETA yet :)

Until then, we'll keep the issue open!

Cheers :)

**Comment by AucaCoyan** [comment]
Remote Desktop is something that is outside of scope 😢 . We couldn't do it until today!
