### ISSUE TITLE
Problem with the Outlook web app in Firefox on Mac OS X

### ISSUE THREAD

**Issue by mrtnj** [espanso/espanso#731]
Hi!

When using the Microsoft Outlook Web app Firefox  on Mac OS X (Big Sur 11.5.1) in Firefox (90.0.2), my triggers expand to two blank spaces. The issue occurs only in the html mode but not in plaintext, so it seems to be related to how the web app handles formatting.

The issue seems oddly specific to this site and browser -- other sites in Firefox and the Outlook web app in Safari both seem to work; I have not noticed this issue on any other combination of browser and site I've used.

Best wishes, 

Martin (that was an expanso trigger, showing that it works fine in Github on Firefox ;) )

**Comment by federico-terzi** [comment]
Hey @mrtnj,

Thanks for reporting this issue! Hopefully, we'll be able to figure this out :) 

Cheers :)

**Comment by smeech** [comment]
Most of these problems can be resolved by changing the `backend:` globally or via `force_mode:` for individual triggers, and occasionally with other options. Have these been fully explored?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
