### ISSUE TITLE
password downshift problem

### ISSUE THREAD

**Issue by McThump** [espanso/espanso#742]
Hi,

I am using Espanso on Linux and created the following to enter complex passwords from the clipboard when remotely accessing Windows computers:

```
  - trigger: "c2k"
    replace: "{{clipboard}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
```

Windows will not allow the pasting of passwords from the clipboard into the login box, but this Espanso match can enter them. The problem is that any uppercase characters in the clipboard are downshifted to lower case. So, for example, a password of "aAbBcC!@" is entered into the Windows password box as "aabbcc12".  This problem only occurs for text inserted into password fields. Anywhere else is fine. I connect to these remote machines many times during the day. Getting this to work would be very helpful.

**Comment by federico-terzi** [comment]
Hey @McThump,

Thanks for reporting this issue! It seems like the remote access software is not passing the SHIFT events. What software are you using for remote access?

Cheers :)

**Comment by McThump** [comment]
Hi @federico-terzi,

Yes.  When I manually enter passwords using the keyboard there is no problem, but when they are inserted by Espanso the shift is not preserved. I am using AnyDesk and Remmina (for RDP connections) on Ubuntu for remote access and it happens with both of them.  I tested this with Espanso on Windows 10 using the native Windows RDP client to remote to another Windows host. In this case, the shift is preserved and the problem does not occur.

**Comment by federico-terzi** [comment]
@McThump Interesting, thank you. 

Does this problem happen also with other applications **in the same remote session**? I mean, I understand that you can't login because of this problem, but can you expand correctly on other applications inside the remote host?

**Comment by McThump** [comment]
@federico-terzi - Ah, excellent question! Yes, the problem occurs for all apps! So far, I had only been using it for password entry.

**Comment by federico-terzi** [comment]
@McThump I see, thank you! We'll investigate :)

**Comment by jtmackoy** [comment]
@federico-terzi, @McThump:  I'm not sure exactly *why* this is happening, but I too had a similar problem and found a work-around.

I'm using a QEMU/KVM host (Pop!-OS 21.04) and run both Windows 10 and Windows 7 guests that leverage SPICE/QXL for displays and am using both `virt-viewer` and `remote-viewer` as clients.  Like @McThump, I too was trying to simplify entering passwords in login prompts within these guests and was also experiencing the "downshifting" problem.  This occurred *anywhere* text expansion was triggered inside of the Windows guests.

More specifically, if I were to have a bit of text like:
`ThIsIsCoMpLiCaTeD!,>@;"`
... it would end up expanded into the guest (irrespective of whether it was a password field or simply in notepad) like this:
`thisiscomplicated1,.2;'`

Thus, all "shift+character" keystrokes are converted to simply "character" ones.

Before using espanso, I used another utility for typing text in Linux hosts: `xdotool`.  This tool simulates typing or mouse movement when using X11 as the host system's display server (doesn't work on wayland).  Interestingly enough, using this in conjunction with an espanso shell extension match like this:

```bash
  - trigger: ":my_pw"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "xdotool type 'ThIsIsCoMpLiCaTeD!,>@;"'"
          trim: false
```

results in a successful expansion of `:my_pw` to `ThIsIsCoMpLiCaTeD!,>@;"` in a Windows guest.

As an aside, [a reddit post](https://www.reddit.com/r/espanso/comments/pc82dm/downshift_problem/) led me to search for this issue in the repo.  Cross-posting in case anyone else follows the same path I did.

**Comment by jtmackoy** [comment]
Hey @federico-terzi!

Sorry for the delay, here's the info on the client I'm using for this issue, with some personal info `<snip>`'d out:

```
Detected change, current window has properties:
==> Title: '<snip> - Remote Viewer'
==> Class: 'Remote-viewer'
==> Executable: ''
```

Interestingly, the `Executable` path wasn't shown, however; I can confirm that for you manually:

```
whereis remote-viewer
remote-viewer: /usr/bin/remote-viewer
```

Hope this helps with your filter work.

BTW, just tried the the 2.1.1-alpha version and my workaround broke there.  Will open a separate issue on that.

**Comment by federico-terzi** [comment]
@jtmackoy Thanks! Sorry for the late reply

> BTW, just tried the the 2.1.1-alpha version and my workaround broke there. Will open a separate issue on that. Opened #912 for that.

Could you please try adding a `$CONFIG/config/remote-viewer.yml` file with this content:

```yaml
filter_class: "Remote-viewer"

backend: Inject
key_delay: 10
inject_delay: 15
disable_x11_fast_inject: true
```

And see if that helps?

If that works, we can integrate the patch into Espanso itself

Cheers :)

**Comment by ajkerrigan** [comment]
Being a bit of an issue necromancer here - I was seeing this lowercasing issue while using triggers in vim (either locally or on remote machines via SSH).

`disable_x11_fast_inject: true` reliably got espanso to start sending those shift keypresses, and the `*_delay` settings prevented the shift from affecting more characters than intended. Thank you @McThump for filing this issue and @federico-terzi for the effective workaround :heart:

**Comment by smeech** [comment]
`x11_use_xdotool_backend` may also be helpful for these cases.
