### ISSUE TITLE
Package installer not working correctly "espanso install obsidian-in-colour --external"

### ISSUE THREAD

**Issue by LtanHonor** [espanso/espanso#752]
Preliminary Information:
Obsidian version: 0.12.15
Espanso version: 0.7.3

Copied verbatim from my reddit post: https://www.reddit.com/r/espanso/comments/pkc5ke/obsidian_in_colour_woes_package_installer_not/

As the title hints at, when I installed obsidian-in-colour using the command line the script never executes. After looking in the logs and then the yml file I found:

YML "%CONFIG%/scripts/obsidian_colour.py"

LOG 14:29:48 [ WARN] Script command reported error: C:\Users\name\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'C:\Users\name\AppData\Roaming\espanso\scripts\obsidian_colour.py': [Errno 2] No such file or directory

When I hard code the YML to point to the correct location everything works correctly.

Modified YML

"C:/Users/name/AppData/Local/espanso/packages/obsidian-in-colour/scripts/obsidian_colour.py"

The %CONFIG% variable is looking for the Scripts folder just under the espanso folder, while the installer puts it into the packages\PACKAGENAME\scripts folder. Is this an ESPANSO issue, or the package?

My work around has been, on Windows 10, to use mklink and junction link the /apps/remote and the /apps/local/ Espanso folders to use only the /apps/local location.  Don't hate on this solution, I know it is not the ideal way to deal with it :)

**Comment by federico-terzi** [comment]
Hey @LtanHonor,

Thanks for reporting this issue! This is a bug, we'll look into it

Cheers :)

**Comment by smeech** [comment]
Is this still a problem with the current version of Espanso?

**Comment by smeech** [comment]
This is a problem with the package, which apparently has the incorrect link to the script. If you can tell us where it's hosted, we can suggest a correction.

Packages need to link to scripts within their own directory.
