### ISSUE TITLE
Forms taking almost exactly 25 seconds to open on Ubuntu 20 fresh install

### ISSUE THREAD

**Issue by adam-ahern** [espanso/espanso#763]
If there are any logs I can upload or do any tests with this let me know. 

uname -a
Linux latitude-7400 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I am seeing the following in journalctl -xe:
Oct 06 15:30:47 latitude-7400 systemd[1]: Started Run anacron jobs.
-- Subject: A start job for unit anacron.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit anacron.service has finished successfully.
-- 
-- The job identifier is 2093.
Oct 06 15:30:47 latitude-7400 anacron[6250]: Anacron 2.3 started on 2021-10-06
Oct 06 15:30:47 latitude-7400 anacron[6250]: Normal exit (0 jobs run)
Oct 06 15:30:47 latitude-7400 systemd[1]: anacron.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit anacron.service has successfully entered the 'dead' state.
Oct 06 15:31:20 latitude-7400 systemd[1]: tmp-.mount_moduloKDKpMK.mount: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit tmp-.mount_moduloKDKpMK.mount has successfully entered the 'dead' state.
Oct 06 15:31:20 latitude-7400 systemd[1502]: tmp-.mount_moduloKDKpMK.mount: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support

**Comment by federico-terzi** [comment]
@noriom42 Thanks!

> So nothing I can do for now?

I don't have any easy solution in mind, so I'd wait for the alpha version to come out and then give it a try :)
