### ISSUE TITLE
Evaluate optimal destination for migrate backup directory

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#772]
Currently, the migration tool backs up the previous configuration inside a folder in the Documents folder.

As pointed out in [this thread](https://github.com/federico-terzi/espanso/issues/769#issuecomment-939331952), it might be more logical to backup the directory nearby the previous location.

So for example, if the previous config was located in `/home/xircon/.config/espanso`, we might want to backup in `/home/xircon/.config/espanso-backup` instead of the Documents folder

**Comment by smeech** [comment]
As most people should now be on the new release I'll close this for now but will be happy to reopen it if needed.
