### ISSUE TITLE
Show regex triggers in search bar

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#773]
As described [here](https://github.com/federico-terzi/espanso/issues/762#issuecomment-939360857), it would be nice to have regex triggers displayed on the search bar

![image](https://user-images.githubusercontent.com/20475953/136689563-e5b25650-5e8f-47ff-b1fa-95845a979283.png)

**Comment by AucaCoyan** [comment]
I tried this and it's still missing on v2.2.1

**Comment by ghost** [comment]
Just a note that I am working on this.
