### ISSUE TITLE
Improve 'espanso env-path register' handling when entries are already present

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#776]
If an entry is already registered (for example due to a previous version being installed), the `espanso env-path register` command fails on Linux (verify also on other OSes):

```
Unable to add 'espanso' command to PATH: symlink error: `File exists (os error 17)`
```

From a UX perspective, it would be better to either:
* Overwrite the previous entry, or
* Ask the user if they want to overwrite the entry (here we would need a flag to forcefully overwrite it anyway)

It's not obvious for the user that they should run `espanso env-path unregister` first after an upgrade

**Comment by jfml** [comment]
Thanks for this, I had this error when switching back from Wayland to X and wasn't sure how to unregister the Wayland version from $PATH.

**Comment by smeech** [comment]
I'll close this as I hope this is now resolved or covered in the documentation now that most people have moved to v2.
