### ISSUE TITLE
Improved rendering of emojis in search dialog

### ISSUE THREAD

**Issue by JeppeKlitgaard** [espanso/espanso#790]
The search dialog currently renders emojis in black and white and using an odd set of symbols.

If instead the font was either customizable or had a better default, the search dialog would work much better with emojis.

It could be worth considering whether to bundle https://openmoji.org/ with espanso - it is open source and the folks behind it seem very friendly. I imagine they would love to feature in espanso!

**Comment by federico-terzi** [comment]
Hey @JeppeKlitgaard,

Thanks for pointing this out, this might be interesting indeed! As far as I've noticed, Emoji rendering in the search box depends on the operating system, for example on macOS they look pretty good:

![image](https://user-images.githubusercontent.com/20475953/137199609-2b4f8aa3-1f62-4a3c-b56d-ef0ac2626a1d.png)

I suspect you are on Linux or Windows, am I right?

Cheers :)

**Comment by JeppeKlitgaard** [comment]
Ideally I think it would just use the font for emojis that the system is configured to use.

For reference, on Windows:
![image](https://user-images.githubusercontent.com/1814611/137218267-841abee4-ac4f-46a8-b9ba-517963e4b722.png)

As opposed to the Windows Emoji Keyboard:
![image](https://user-images.githubusercontent.com/1814611/137218314-1d5b1e61-8068-48ea-884b-90bf134d8446.png)

Note also how the Windows Emoji Keyboard has more matches, which would be achievable using #789.

Super excited to see where espanso v2 will end up!

**Comment by smeech** [comment]
Is this still a problem with the current release? I'll close it for now but am happy to reopen if necessary.
