### ISSUE TITLE
espanso is giving me error although module  "atk-bridge" is installed.

### ISSUE THREAD

**Issue by rajeshXYZ** [espanso/espanso#807]
espanso log
11:13:01 [ INFO] espanso version 0.7.3
11:13:01 [ INFO] using config path: /home/rajesh/.config/espanso
11:13:01 [ INFO] using package path: /home/rajesh/.local/share/espanso/packages
11:13:01 [ INFO] spawning worker process...
11:13:01 [ INFO] Binded to IPC unix socket: /home/rajesh/.local/share/espanso/espanso.sock
11:13:01 [ INFO] initializing worker process...
11:13:01 [ INFO] Binded to IPC unix socket: /home/rajesh/.local/share/espanso/worker.sock
11:13:01 [ INFO] watching for changes in path: /home/rajesh/.config/espanso
11:13:01 [ INFO] Using modulo at "modulo"
11:13:01 [ INFO] worker is running!
11:13:53 [ERROR] modulo reported an error: Gtk-Message: 16:43:47.425: Failed to load module "atk-bridge"

**Comment by federico-terzi** [comment]
Hey @rajeshXYZ,

I'm sorry you experienced this problem! It seems that this error is related to `modulo`. Given that the new alpha version (v2) ships with a completely new GUI layer, I think that might solve your issue :)

Could you please give the new alpha version a try? The documentation is still being written, but you should be able to get it running following the [migration](https://espanso.org/docs/next/migration/overview/) section and then the [installation](https://espanso.org/docs/next/install/linux/)

Cheers :)

**Comment by smeech** [comment]
Is this still a problem with the current release? I'll close it for now but am happy to reopen if necessary.
