### ISSUE TITLE
Investigate changing markdown to HTML library

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#818]
Currently, espanso uses the `markdown` crate, which seems unmaintained and has some problems #759 

We might want to give `pulldown-cmark` a try, as it comes with an HTML writer built-in: https://github.com/raphlinus/pulldown-cmark/blob/master/examples/string-to-string.rs

**Comment by smeech** [comment]
Is this still a problem with the current release? I'll close it for now, but am happy to reopen if necessary.
