### ISSUE TITLE
espanso 2.0.4-alpha, Debian 11, Wayland: documentation suggestions

### ISSUE THREAD

**Issue by neilzone** [espanso/espanso#830]
I have successfully installed espanso 2.0.4-alpha on Debian 11, with Wayland.

All the tests I have carried out so far have worked, including things which did not work with the previous version of espanso I was using. In particular:

- I can now use pop-up forms, into which I can put variables
- It works in evolution and other applications in which it did not work before.

So very positive.

Some quick notes on [the documentation](https://espanso.org/docs/next/install/linux/#install-on-wayland), in case they help others:

# cargo version

The documentation says to install `cargo make` with:

```
cargo install --force cargo-make --version 0.34.0
```

The docs do not say if v.0.34.0 is a requirement, or if any (later?) version of cargo will suffice.

I used this command but, on first run, cargo prompted me that a newer version was available. I did the upgrade, to - I believe; not sure how to check now - v.0.35.5 - and ran the remainder of the commands with that.

It worked.

# cargo added to path, but not immediately available

After installation, `cargo` was added to my $PATH, but (as is usual) you need to force the system to pick up the new path:

```
source ~/.bashrc
```
should work, else log out and log back in.

# espanso status problems

After installation, I realised I probably should have deleted the old version of espanso first. I used the .deb installer previously, so I uninstalled it by deleting it from /usr/bin/espanso manually.

However, I did not touch the systemd services, and perhaps I should have done.

After moving the new alpha binary to /usr/local/bin, I ran the commands to register the service, and these completed successfully.

However, running `espanso service status` showed "espanso is not running".

Rebooting the machine fixed this.

# Backup and migrate worked

I selected the "backup and migrate" option, rather than compatibility mode, and this appears to have worked.

**Comment by federico-terzi** [comment]
Hey @neilzone,

Thank you for the feedback! This is really helpful, I'll make sure to update the docs to (hopefully) make some step clearer :)

> The docs do not say if v.0.34.0 is a requirement, or if any (later?) version of cargo will suffice.

Good point, we recently had this bug (https://github.com/federico-terzi/espanso/issues/817), that caused the latest version of cargo make to not work correctly, that's why I specified a previous version in the docs. I decided to keep that version fixed because I've noticed that cargo make evolves pretty fast, sometimes in breaking ways, so keeping a stable version for a while would make troubleshooting easier :)

> After moving the new alpha binary to /usr/local/bin, I ran the commands to register the service, and these completed successfully.
> However, running espanso service status showed "espanso is not running".

Interesting! Do you remember if you also ran `espanso start` afterwards? Because not running it would explain this behavior, otherwise this is a bug :)

> I selected the "backup and migrate" option, rather than compatibility mode, and this appears to have worked.

Nice!

Out of curiosity, what desktop environment are you using? Gnome/Sway/etc

Cheers :)

**Comment by neilzone** [comment]
> > The docs do not say if v.0.34.0 is a requirement, or if any (later?) version of cargo will suffice.
> 
> Good point, we recently had this bug (#817), that caused the latest version of cargo make to not work correctly, that's why I specified a previous version in the docs. I decided to keep that version fixed because I've noticed that cargo make evolves pretty fast, sometimes in breaking ways, so keeping a stable version for a while would make troubleshooting easier :)

That makes sense. 
> 
> > After moving the new alpha binary to /usr/local/bin, I ran the commands to register the service, and these completed successfully.
> > However, running espanso service status showed "espanso is not running".
> 
> Interesting! Do you remember if you also ran `espanso start` afterwards? Because not running it would explain this behavior, otherwise this is a bug :)

Yes, I ran `espanso start`.

It might be a bug, or it might be me messing up my systemd config somehow.

> 
> > I selected the "backup and migrate" option, rather than compatibility mode, and this appears to have worked.
> 
> Nice!
> 
> Out of curiosity, what desktop environment are you using? Gnome/Sway/etc

Gnome (GDM 3.38.2.1).

**Comment by federico-terzi** [comment]
> It might be a bug, or it might be me messing up my systemd config somehow.

At this stage, a bug isn't unlikely :) I'll keep an eye on it, thank you

> Gnome (GDM 3.38.2.1).

Thanks!

**Comment by neilzone** [comment]
> > It might be a bug, or it might be me messing up my systemd config somehow.
> 
> At this stage, a bug isn't unlikely :) I'll keep an eye on it, thank you

Something strange is going on, but I cannot work out where to look to help diagnose it.

1.) Laptop is rebooted.
2.) `espanso service status` returns "espanso is running"
3.) `espanso restart` returns "unable to stop espanso: worker timed out  espanso is already running!"
4.) I tried to restart the systemd service, but failed (as I could not remember what was called)
5.) `espanso status` returns "espanso is not running"
6.) `espanso start` returns "espanso started correctly!"
7.) and it works

Could you show me where the log is, please, to see if I can help work this out?

**Comment by jacostag** [comment]
I did all the steps from the guide, is not working for me, I rebooted, nothing, I restarted the service/noservice is not working.
I am running pop_os! 20.10.
Is there any log that we can see to help to trace the issue?

**Comment by federico-terzi** [comment]
> > > It might be a bug, or it might be me messing up my systemd config somehow.
> > 
> > 
> > At this stage, a bug isn't unlikely :) I'll keep an eye on it, thank you
> 
> Something strange is going on, but I cannot work out where to look to help diagnose it.
> 
> 1.) Laptop is rebooted. 2.) `espanso service status` returns "espanso is running" 3.) `espanso restart` returns "unable to stop espanso: worker timed out espanso is already running!" 4.) I tried to restart the systemd service, but failed (as I could not remember what was called) 5.) `espanso status` returns "espanso is not running" 6.) `espanso start` returns "espanso started correctly!" 7.) and it works
> 
> Could you show me where the log is, please, to see if I can help work this out?

@neilzone Thank you for reporting this issue! Could you please post the output of `espanso log` here?

> I did all the steps from the guide, is not working for me, I rebooted, nothing, I restarted the service/noservice is not working. I am running pop_os! 20.10. Is there any log that we can see to help to trace the issue?

@jacostag I'm sorry you experienced this problem! Could you please open another issue, specifying that you are on Wayland, and also posting the output of `espanso log`?

Cheers :)

**Comment by AucaCoyan** [comment]
This was before v2 was stable, closing
