### ISSUE TITLE
Docs use %CONFIG% when $CONFIG is correct

### ISSUE THREAD

**Issue by pocc** [espanso/espanso#847]
On this page, 0.7.3, %CONFIG% is used twice. Only $CONFIG works. Macos.

https://espanso.org/docs/matches/#:~:text=-%20%22-,%25CONFIG%25,-/scripts/script.py

**Comment by federico-terzi** [comment]
Hey @pocc,

Thanks for reporting this issue! I'll investigate :)

Cheers :)
