### ISSUE TITLE
Make developer documentation

### ISSUE THREAD

**Issue by pocc** [espanso/espanso#864]
Like a developer-readme.md in root that details how to run tests and how to set up your environment.

**Comment by federico-terzi** [comment]
Hey @pocc,

Thank you for the feedback! Good point, I'll add it to the roadmap

Cheers :)

**Comment by tobiasbueschel** [comment]
Hi @federico-terzi,

Is there a single roadmap where you track all upcoming priorities?

- https://github.com/federico-terzi/espanso/projects/1
- https://github.com/federico-terzi/espanso/issues/255 (is this still the current version?)
- https://www.reddit.com/r/espanso/comments/gadphc/roadmap_the_future_of_espanso/

I'm new to Espanso and wasn't sure where to look for the roadmap!

Thanks for everyone's efforts with it :)

**Comment by federico-terzi** [comment]
@tobiasbueschel https://github.com/federico-terzi/espanso/projects/1 is the most up-to-date one :)

**Comment by tobiasbueschel** [comment]
Awesome, thanks @federico-terzi!
