### ISSUE TITLE
Document v2 Hub Packaging

### ISSUE THREAD

**Issue by JeppeKlitgaard** [espanso/espanso#911]
I believe this is definitely something that is already planned, but I thought it could be useful to have an issue tracking process nonetheless.

I would like to expand my personal [`barista`](https://github.com/JeppeKlitgaard/barista) project to publish Espanso hub package(s). Currently the format required is undocumented: https://espanso.org/docs/next/packages/

I personally quite like the idea of an espanso config 'build tool', which is what barista is gravitating towards. This would eventually be superseded by a scripting API (see: #813) or built-in `jsonnet` configuration support (see: #679 and #632)

**Comment by federico-terzi** [comment]
Hey @JeppeKlitgaard,

You're absolutely right! That's something that needs some real documentation. Given that the rest of the docs are almost ready, that is likely the next section I'll tackle. I'll make sure to let you know once it's ready :)

Cheers :)

**Comment by smeech** [comment]
I think this is now covered by the [docs](https://espanso.org/docs/packages/creating-a-package/), so I'll close the issue.
