### ISSUE TITLE
Could not generate output for clipboard variable

### ISSUE THREAD

**Issue by crsov** [espanso/espanso#924]
**Describe the bug**
Espanso could not generate output for any clipboard variables (type: clipboard)

**To Reproduce**
1. Add match with clipboard variable to config:
```
- trigger: ":clip"
    replace: "{{clip}}"
    vars:
      - name: clip
        type: clipboard
        params:
          debug: true
```
2. Copy something to the clipboard and trigger match with clipboard variable
3. Check log and see `Could not generate output for variable: clip`

**Expected behavior**
Match :clip replaces with clipboard content

**Screenshots**
[Terminal record](https://asciinema.org/a/PPkNJnY1ypU6QJtVmlXGV5VAL)

**Logs**
```
11:50:24 [ INFO] espanso version 0.7.3
11:50:24 [ INFO] using config path: /home/aru/.config/espanso
11:50:24 [ INFO] using package path: /home/aru/.local/share/espanso/packages
11:50:24 [ INFO] spawning worker process...
11:50:24 [ INFO] Binded to IPC unix socket: /home/aru/.local/share/espanso/espanso.sock
11:50:24 [ INFO] initializing worker process...
11:50:24 [ INFO] Binded to IPC unix socket: /home/aru/.local/share/espanso/worker.sock
11:50:24 [ INFO] worker is running!
11:50:24 [ INFO] watching for changes in path: /home/aru/.config/espanso
11:50:35 [ WARN] Could not generate output for variable: clip
``` 

**Setup information**
- OS: Linux Fedora 33 x86_64
- Version: 0.7.3
- Display server: Xorg
- Backend: Default for linux - auto

**Comment by federico-terzi** [comment]
Hey @crsov,

Thanks for reporting this issue! A couple of possible suggestions:
* If you want to keep using version 0.7.3 for now, make sure to have the `xclip` command line binary installed
* I'd highly suggest, whenever possible, to migrate to the new v2, which might solve this problem for you: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)

**Comment by smeech** [comment]
I think this is now resolved with the current version, and I've not had any problems with testing the clipboard extension, so I'll close it for now.
