### ISSUE TITLE
Espanso causes clipboard manager false dings/sounds/visual bells on every expansion

### ISSUE THREAD

**Issue by dougpagani** [espanso/espanso#930]
**Describe the bug**
Hi! Just downloaded the app after a friend of mine raved about it on linux, and I'm using it on macos.

I have a clipboard manger installed and it registers clipboard events for every espanso expansion I do. I use the sound or visual bell equivalent, to register that a copy went through to my clipboard, and the false-dings that espanso causes are pretty distracting.

I haven't looked into the implementation details, but from the behavior I would assume it uses the clipboard to push text to the screen with a quick succession of copy-paste-delete events. I know that 1password, for example, is able to copy text to the system clipboard while dodging a clipboard manager (so as not to be a security flaw). This may be possible with espanso, if this indeed is the implementation.

**To Reproduce**
1. Download a clipboard manager with a sound notification. (I'm using [Paste](https://pasteapp.io/))
2. enable sound notifications
3. expand an espanso match
_(if you do not have the clipboard manger process running, it will inversely not make a sound)_

**Expected behavior**
I would expect espanso, since it does not modify the clipboard, to not register as a new item copied on every expansion.

**Screenshots**
`n/a`

**Logs**
```log
23:51:54 [ INFO] espanso version 0.7.3
23:51:54 [ INFO] using config path: /Users/dougpa/Library/Preferences/espanso
23:51:54 [ INFO] using package path: /Users/dougpa/Library/Application Support/espanso/packages
23:51:54 [ INFO] spawning worker process...
23:51:54 [ INFO] Binded to IPC unix socket: /Users/dougpa/Library/Application Support/espanso/espanso.sock
23:51:55 [ INFO] initializing worker process...
23:51:55 [ INFO] Status icon already initialized, skipping.
23:51:55 [ INFO] Status icon (disabled) already initialized, skipping.
23:51:55 [ INFO] Initializing EspansoNotifyHelper in /Users/dougpa/Library/Application Support/espanso
23:51:55 [ INFO] EspansoNotifyHelper already initialized, skipping.
23:51:55 [ INFO] Binded to IPC unix socket: /Users/dougpa/Library/Application Support/espanso/worker.sock
23:51:55 [ INFO] Using modulo at "/usr/local/bin/modulo"
23:51:55 [ INFO] Created Modulo APP stub at: "/Users/dougpa/Library/Application Support/espanso/Modulo.app/Contents/MacOS/modulo"
23:51:55 [ INFO] worker is running!
23:51:55 [ INFO] watching for changes in path: /Users/dougpa/Library/Preferences/espanso
```

**Setup information**
- OS: macos Catalina (`10.15.7`)
- Version: espanso `0.7.3`

Thanks for all your hard work contributing to open source!

**Comment by federico-terzi** [comment]
Hey @dougpagani,

Thanks for reporting this issue! This is interesting, as Espanso _can_ use the clipboard as injection mechanism, but it shouldn't do that by default in version 0.7.3. I'll investigate :)

Cheers :)

**Comment by dougpagani** [comment]
Federico -- from your post I learned about `backend` and so I tried it with either `Inject`/`Clipboard` and I can confirm that, in fact, `Inject` **was the default, as designed.** However, Inject seems to still throw an errant clipboard event (even though it doesn't seem to modify the clipboard, besides, strangely, updating the timestamp). 

To compare:
`Clipboard` :
- terminal interprets it as a clipboard event (and consequently, it is highlighted which indicates its protected against unintentional `^M`-returns being included in the pasted content)
- there are two modifications to the clipboard
  1. the expansion
  2. copied-over, in order to restore state from espanso's usage of the clipboard, is the "old" clipboard item

`Inject` (same behavior as if I didn't explicitly configure any `backend` in `default.yml`:
- terminal doesn't interpret it as a clipboard event (notice how it isn't highlighted)
- BUT the timestamp of the item I had copied 3 minutes ago was updated to _"Just now"_

So, maybe photos will help you to understand.

-----

with `backend: Clipboard`
![image](https://user-images.githubusercontent.com/18250753/148664763-c36dfc5e-b2aa-48dc-94b9-2fd356e848ac.png)
![image](https://user-images.githubusercontent.com/18250753/148664767-ba3efe74-bf85-42b4-8edb-77f2a9d241ae.png)

-----

with `backend: Inject`:
![image](https://user-images.githubusercontent.com/18250753/148664776-feec3ef9-868c-491c-af3e-d26b2512aa39.png)
![image](https://user-images.githubusercontent.com/18250753/148664778-8d21b2c6-6bd9-4af0-ae65-46ca7ada4e56.png)

**Comment by dougpagani** [comment]
Again, I know nothing of the implementation. But if I had to guess, maybe there is a "save/restore clipboard" call that's unnecessarily firing-off even if the mode is not in `backend: Clipboard`. It would be important to have that codepath consistently fire in the case that espanso were using the clipboard, so there may be a "just in case" clause that's before the engine decides which backend to use. But of course, in the event that `backend: Inject` is used, this is not necessary.

**Comment by federico-terzi** [comment]
Hey @dougpagani,

Thanks for the detailed report! I suspect the new version v2 might solve this issue, so when you have the chance, I highly suggest trying it out :) More info here: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)

**Comment by dougpagani** [comment]
Will do! Thanks!

**Comment by smeech** [comment]
Is this still a problem, with the current release?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, for an edge-case, and may not be a problem with the current release.
