### ISSUE TITLE
Using ctrl+backspace after expanding :date results in loss of information

### ISSUE THREAD

**Issue by lucainnocenti** [espanso/espanso#952]
**Describe the bug**
I have an extremely regular setup. Pretty much the default one I got after installing espanso. 

I regularly use ctrl+backspace to delete the last word. Using ctrl+backspace immediately after expanding the default `:date` macro results in a lot of text being deleted which really shouldn't. For example, if I do it right here in this textbox, it deletes a good chunk of the row. I discovered this while using it in a note in [Obsidian](https://obsidian.md/), and this somehow completely erased the whole note.

**To Reproduce**

![Animation](https://user-images.githubusercontent.com/10957113/150172279-9ebee79d-7f34-401e-83d8-b71b6f767898.gif)

**Setup information**
- OS: Windows 11
- Version: 0.7.3

**Comment by federico-terzi** [comment]
Hey @lucainnocenti,

I'm sorry you experienced this problem! A couple of ideas:
* You can disable the `undo_backspace` feature by adding `undo_backspace: false` to your `default.yml` file.
* You can try upgrading to the v2 (see https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339), which should handle this edge case correctly (if it doesn't, then it's a bug we'll need to solve soon :))

Cheers :)

**Comment by smeech** [comment]
Is this still a problem with the current release?

**Comment by smeech** [comment]
I presume not. Closing.
