### ISSUE TITLE
Allow for timing based triggers

### ISSUE THREAD

**Issue by padgett1** [espanso/espanso#959]
**Is your feature request related to a problem? Please describe.**
Yes, I'm struggling to trigger a large number of hotkeys, that would normally cause problems and It would fix my issues if I could adjust the timing interval for how long typed letters are kept. 

**Describe the solution you'd like**
I'd like a line in the config file that adjusts how long in milliseconds it keeps the typed keys (set 0) to disable
when you set it to 50ms, it will only consider the keys typed within the last 50 ms for replacement. 

**Describe alternatives you've considered**
I have tried triggering it on the spacebar, but because some shorter words appear in longer words, this has not worked very well.

**Comment by federico-terzi** [comment]
Hey @rhit-padgett1,

I'm sorry you experienced this problem! Perhaps, [word triggers](https://espanso.org/docs/matches/#word-triggers) might already solve your problem?

Cheers :)

**Comment by smeech** [comment]
This is now a rather old thread. Is this still an issue worth pursuing?
Most people get around these problems using trigger-characters before or after triggers, or [word triggers](https://espanso.org/docs/matches/basics/#word-triggers), or [regex:](https://espanso.org/docs/matches/regex-triggers/).
