### ISSUE TITLE
Constant restart with live editing config file while config file is in an exotic location

### ISSUE THREAD

**Issue by shaneknysh** [espanso/espanso#982]
**Describe the bug**
This bug is the result of a rather specific configuration I have but I do not know which part is the trigger and now to mitigate it (other than not using live editing). I keep forgetting to exit Espanso when I need to make a quick edit or addition. 

I have also asked IceDrive about this issue and I am awaiting their response.

**To Reproduce**
1. Install Espanso, configure, add any custom yml files to roaming folder
2. Exit Espanso
3. Install IceDrive, configure 
4. Copy Expanso file from roaming to IceDrive
5. delete Espanso folder form roaming
6. create mklink form IceDrive to roaming folder
7. restart Espanso
8. Navigate to the yml files in IceDrive
9. Edit a yml file while Espansoi is running
10. Save yml file
11. Espanso will enter a loop where there are two Espanso tasks running and every 120 seconds the "Reloaded Config" mesage is displayed
12. restart PC or open task manager and kill both Espanso tasks between the "Reloaded Config" popups 

**Expected behavior**
Espanso loads the configs once

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
partially redacted log
01:57:17 [ INFO] espanso version 0.7.3
01:57:17 [ INFO] using config path: D:\Users\user\AppData\Roaming\espanso
01:57:17 [ INFO] using package path: D:\Users\shane\AppData\Local\espanso\packages
01:57:17 [ INFO] spawning worker process...
01:57:17 [ INFO] Binding to named pipe: \\.\pipe\espansodaemon
01:57:18 [ INFO] initializing worker process...
01:57:18 [ INFO] Initializing Espanso resources in D:\Users\user\AppData\Local\espanso
01:57:18 [ INFO] BMP already initialized, skipping.
01:57:18 [ INFO] ICO already initialized, skipping.
01:57:18 [ INFO] red ICO already initialized, skipping.
01:57:18 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
01:57:18 [ INFO] watching for changes in path: D:\Users\user\AppData\Roaming\espanso
01:57:18 [ INFO] Using modulo at "D:\\Users\\user\\AppData\\Local\\Programs\\espanso\\modulo"
01:57:18 [ INFO] worker is running!
01:59:12 [ INFO] change detected, restarting worker process...
01:59:12 [ INFO] terminating worker process
01:59:12 [ INFO] initializing worker process...
01:59:12 [ INFO] Initializing Espanso resources in D:\Users\user\AppData\Local\espanso
01:59:12 [ INFO] BMP already initialized, skipping.
01:59:12 [ INFO] ICO already initialized, skipping.
01:59:12 [ INFO] red ICO already initialized, skipping.
01:59:12 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
01:59:13 [ INFO] Using modulo at "D:\\Users\\user\\AppData\\Local\\Programs\\espanso\\modulo"
01:59:13 [ INFO] worker is running!
01:59:14 [ INFO] change detected, restarting worker process...
01:59:14 [ INFO] terminating worker process
01:59:14 [ INFO] initializing worker process...
01:59:14 [ INFO] Initializing Espanso resources in D:\Users\user\AppData\Local\espanso
01:59:14 [ INFO] BMP already initialized, skipping.
01:59:14 [ INFO] ICO already initialized, skipping.
01:59:14 [ INFO] red ICO already initialized, skipping.
01:59:14 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
01:59:15 [ INFO] Using modulo at "D:\\Users\\user\\AppData\\Local\\Programs\\espanso\\modulo"
01:59:15 [ INFO] worker is running!
01:59:16 [ INFO] change detected, restarting worker process...
and repeat...

**Setup information**
- OS: Windows 11
- Version: 0.7.3

**Comment by shaneknysh** [comment]
Can I install the alpha side by side? How alpha is it?

**Comment by federico-terzi** [comment]
@shaneknysh Sorry for the late reply!

> Can I install the alpha side by side?

You can't have them side by side, but you can uninstall 0.7.3 and run the v2 in "compatibility mode" (which keeps the old configuration format).  Worst case you uninstall the v2 and go back to 0.7.3, though most users were happy with the new version :)

> How alpha is it?

Should be pretty stable (I've been using it since September), it should be promoted to beta soon :)

**Comment by shaneknysh** [comment]
I'm looking forward to the next version but I might defer until you promote it to beta.

For now I am avoiding doing live edits.

If I can set up and test on another computer I will install the alpha and test.

**Comment by smeech** [comment]
Is this still a problem with the current release?

**Comment by shaneknysh** [comment]
Unknown. I changed my configuration location to avoid this issue over a year ago.

**Comment by smeech** [comment]
Fair enough! I'll close the issue for now and leave it to someone else to raise it again if necessary.
Development is taking off now there are more people involved.
Thank you very much for replying after so long.

**Comment by shaneknysh** [comment]
You could follow the steps to reproduce to check the status in the latest release rather than waiting for someone else to report the problem in the future.

Using a sync service to copy configuration is a fairly common use case for utilities. Writing a test to check if the configuration and data folder can be a hard or soft link would be a valuable test case.
