### ISSUE TITLE
Cannot use Finder alias (like shortcut on Windows)

### ISSUE THREAD

**Issue by BNolet** [espanso/espanso#992]
**Describe the bug**
When using the **right-click > Make Alias** function in Finder to create a shortcut to a separate folder, espanso throws an error saying that the file already exists

**To Reproduce**
1. Right click any folder
2. Select Make Alias
3. Move the alias into `$HOME/Library/Preferences/` and name it `espanso`
4. Reload config in espanso or run `espanso start` in the terminal.

**Expected behavior**
I would have expected it to work since there's no warning about this in the documentation.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
```
thread 'main' panicked at 'Error creating espanso config directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/context/mod.rs:154:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
❯ ls -la Library/Preferences/e*
-rw-------@ 1 brandonnolet  staff  940 20 Feb 13:04 Library/Preferences/espanso
-rw-------  1 brandonnolet  staff   92  5 Feb 13:21 Library/Preferences/espanso.plist
```

**Setup information**
- OS: macOS Monterey 12.2.1
- Version: 0.7.3

**Comment by federico-terzi** [comment]
Hey @BNolet,

I'm sorry you experienced this problem! I currently don't have my mac around to try your setup, but this section of the docs might help: https://espanso.org/docs/sync/

Cheers :)

**Comment by BNolet** [comment]
No worries, I was able to get the symbolic link working already, I just wanted to try out the alias and I noticed it didn’t work for me. 

The alias seems to act something like Windows’ `lnk` shortcut filetype.
